      SUBROUTINE SP9_gg_epveemvexbbx1(P,ANS)
C     
C     Generated by MadGraph 5 v. 1.5.13, 2013-11-04
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     MadGraph for Madevent Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL_BORN)
C     
C     Process: g g > e+ ve e- ve~ b b~ QCD=2 QED=4 @9
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'genps.inc'
      INCLUDE 'maxconfigs.inc'
      INCLUDE 'nexternal_born.inc'
      INCLUDE 'maxamps_P9_gg_epveemvexbbx.inc'
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=256)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=203)
      INTEGER    NDIAGS
      PARAMETER (NDIAGS=203)
      INTEGER    THEL
      PARAMETER (THEL=2*NCOMB)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL_BORN),ANS
C     
C     LOCAL VARIABLES 
C     
      INTEGER NHEL(NEXTERNAL_BORN,NCOMB),NTRY(2)
      INTEGER ISHEL(2)
      REAL*8 T,P9_gg_epveemvexbbx1
      REAL*8 R,SUMHEL,TS(NCOMB)
      INTEGER I,IDEN
      INTEGER JC(NEXTERNAL_BORN),II
      LOGICAL GOODHEL(NCOMB,2)
      REAL*8 HWGT, XTOT, XTRY, XREJ, XR, YFRAC(0:NCOMB)
      INTEGER NGOOD(2), IGOOD(NCOMB,2)
      INTEGER JHEL(2), J, JJ
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS_P9_gg_epveemvexbbx/  AMP2,       JAMP2

      CHARACTER*101         HEL_BUFF
      COMMON/TO_HELICITY/  HEL_BUFF

      INTEGER IMIRROR
      COMMON/TO_mirror_GL/ IMIRROR

      REAL*8 POL(2)
      COMMON/TO_polarization_GL/ POL

      INTEGER          ISUM_HEL
      LOGICAL                    MULTI_CHANNEL
      COMMON/TO_matrix_GL/ISUM_HEL, MULTI_CHANNEL
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      COMMON/TO_MCONFIGS/MAPCONFIG, ICONFIG
      INTEGER SUBDIAG(MAXSPROC),IB(2)
      COMMON/TO_SUB_DIAG/SUBDIAG,IB
      DATA XTRY, XREJ /0,0/
      DATA NTRY /0,0/
      DATA NGOOD /0,0/
      DATA ISHEL/0,0/
      SAVE YFRAC, IGOOD, JHEL
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(I,   1),I=1,8) /-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,   2),I=1,8) /-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,   3),I=1,8) /-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,   4),I=1,8) /-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,   5),I=1,8) /-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,   6),I=1,8) /-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,   7),I=1,8) /-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,   8),I=1,8) /-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,   9),I=1,8) /-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  10),I=1,8) /-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  11),I=1,8) /-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  12),I=1,8) /-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  13),I=1,8) /-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  14),I=1,8) /-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  15),I=1,8) /-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  16),I=1,8) /-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  17),I=1,8) /-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  18),I=1,8) /-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  19),I=1,8) /-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  20),I=1,8) /-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  21),I=1,8) /-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  22),I=1,8) /-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  23),I=1,8) /-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  24),I=1,8) /-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  25),I=1,8) /-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  26),I=1,8) /-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  27),I=1,8) /-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  28),I=1,8) /-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  29),I=1,8) /-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  30),I=1,8) /-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  31),I=1,8) /-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  32),I=1,8) /-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  33),I=1,8) /-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  34),I=1,8) /-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  35),I=1,8) /-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  36),I=1,8) /-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  37),I=1,8) /-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  38),I=1,8) /-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  39),I=1,8) /-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  40),I=1,8) /-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  41),I=1,8) /-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  42),I=1,8) /-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  43),I=1,8) /-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  44),I=1,8) /-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  45),I=1,8) /-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  46),I=1,8) /-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  47),I=1,8) /-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  48),I=1,8) /-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  49),I=1,8) /-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  50),I=1,8) /-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  51),I=1,8) /-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  52),I=1,8) /-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  53),I=1,8) /-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  54),I=1,8) /-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  55),I=1,8) /-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  56),I=1,8) /-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  57),I=1,8) /-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  58),I=1,8) /-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  59),I=1,8) /-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  60),I=1,8) /-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  61),I=1,8) /-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  62),I=1,8) /-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  63),I=1,8) /-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  64),I=1,8) /-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  65),I=1,8) /-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  66),I=1,8) /-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  67),I=1,8) /-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I,  68),I=1,8) /-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I,  69),I=1,8) /-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I,  70),I=1,8) /-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I,  71),I=1,8) /-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I,  72),I=1,8) /-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I,  73),I=1,8) /-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I,  74),I=1,8) /-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I,  75),I=1,8) /-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I,  76),I=1,8) /-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I,  77),I=1,8) /-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I,  78),I=1,8) /-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I,  79),I=1,8) /-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I,  80),I=1,8) /-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I,  81),I=1,8) /-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I,  82),I=1,8) /-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I,  83),I=1,8) /-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I,  84),I=1,8) /-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I,  85),I=1,8) /-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I,  86),I=1,8) /-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I,  87),I=1,8) /-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I,  88),I=1,8) /-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I,  89),I=1,8) /-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I,  90),I=1,8) /-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I,  91),I=1,8) /-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I,  92),I=1,8) /-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I,  93),I=1,8) /-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I,  94),I=1,8) /-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I,  95),I=1,8) /-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I,  96),I=1,8) /-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I,  97),I=1,8) /-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I,  98),I=1,8) /-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I,  99),I=1,8) /-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 100),I=1,8) /-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 101),I=1,8) /-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 102),I=1,8) /-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 103),I=1,8) /-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 104),I=1,8) /-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 105),I=1,8) /-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 106),I=1,8) /-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 107),I=1,8) /-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 108),I=1,8) /-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 109),I=1,8) /-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 110),I=1,8) /-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 111),I=1,8) /-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 112),I=1,8) /-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 113),I=1,8) /-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 114),I=1,8) /-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 115),I=1,8) /-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 116),I=1,8) /-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 117),I=1,8) /-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 118),I=1,8) /-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 119),I=1,8) /-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 120),I=1,8) /-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 121),I=1,8) /-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 122),I=1,8) /-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 123),I=1,8) /-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 124),I=1,8) /-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 125),I=1,8) /-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 126),I=1,8) /-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 127),I=1,8) /-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 128),I=1,8) /-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 129),I=1,8) / 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 130),I=1,8) / 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 131),I=1,8) / 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 132),I=1,8) / 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 133),I=1,8) / 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 134),I=1,8) / 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 135),I=1,8) / 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 136),I=1,8) / 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 137),I=1,8) / 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 138),I=1,8) / 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 139),I=1,8) / 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 140),I=1,8) / 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 141),I=1,8) / 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 142),I=1,8) / 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 143),I=1,8) / 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 144),I=1,8) / 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 145),I=1,8) / 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 146),I=1,8) / 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 147),I=1,8) / 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 148),I=1,8) / 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 149),I=1,8) / 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 150),I=1,8) / 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 151),I=1,8) / 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 152),I=1,8) / 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 153),I=1,8) / 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 154),I=1,8) / 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 155),I=1,8) / 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 156),I=1,8) / 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 157),I=1,8) / 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 158),I=1,8) / 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 159),I=1,8) / 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 160),I=1,8) / 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 161),I=1,8) / 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 162),I=1,8) / 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 163),I=1,8) / 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 164),I=1,8) / 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 165),I=1,8) / 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 166),I=1,8) / 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 167),I=1,8) / 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 168),I=1,8) / 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 169),I=1,8) / 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 170),I=1,8) / 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 171),I=1,8) / 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 172),I=1,8) / 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 173),I=1,8) / 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 174),I=1,8) / 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 175),I=1,8) / 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 176),I=1,8) / 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 177),I=1,8) / 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 178),I=1,8) / 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 179),I=1,8) / 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 180),I=1,8) / 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 181),I=1,8) / 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 182),I=1,8) / 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 183),I=1,8) / 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 184),I=1,8) / 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 185),I=1,8) / 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 186),I=1,8) / 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 187),I=1,8) / 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 188),I=1,8) / 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 189),I=1,8) / 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 190),I=1,8) / 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 191),I=1,8) / 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 192),I=1,8) / 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 193),I=1,8) / 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 194),I=1,8) / 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 195),I=1,8) / 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 196),I=1,8) / 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 197),I=1,8) / 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 198),I=1,8) / 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 199),I=1,8) / 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 200),I=1,8) / 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 201),I=1,8) / 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 202),I=1,8) / 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 203),I=1,8) / 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 204),I=1,8) / 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 205),I=1,8) / 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 206),I=1,8) / 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 207),I=1,8) / 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 208),I=1,8) / 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 209),I=1,8) / 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 210),I=1,8) / 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 211),I=1,8) / 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 212),I=1,8) / 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 213),I=1,8) / 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 214),I=1,8) / 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 215),I=1,8) / 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 216),I=1,8) / 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 217),I=1,8) / 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 218),I=1,8) / 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 219),I=1,8) / 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 220),I=1,8) / 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 221),I=1,8) / 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 222),I=1,8) / 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 223),I=1,8) / 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 224),I=1,8) / 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(I, 225),I=1,8) / 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(I, 226),I=1,8) / 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(I, 227),I=1,8) / 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(I, 228),I=1,8) / 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(I, 229),I=1,8) / 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(I, 230),I=1,8) / 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(I, 231),I=1,8) / 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(I, 232),I=1,8) / 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(I, 233),I=1,8) / 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(I, 234),I=1,8) / 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(I, 235),I=1,8) / 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(I, 236),I=1,8) / 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(I, 237),I=1,8) / 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(I, 238),I=1,8) / 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(I, 239),I=1,8) / 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(I, 240),I=1,8) / 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(I, 241),I=1,8) / 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(I, 242),I=1,8) / 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(I, 243),I=1,8) / 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(I, 244),I=1,8) / 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(I, 245),I=1,8) / 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(I, 246),I=1,8) / 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(I, 247),I=1,8) / 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(I, 248),I=1,8) / 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(I, 249),I=1,8) / 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(I, 250),I=1,8) / 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(I, 251),I=1,8) / 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(I, 252),I=1,8) / 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(I, 253),I=1,8) / 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(I, 254),I=1,8) / 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(I, 255),I=1,8) / 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(I, 256),I=1,8) / 1, 1, 1, 1, 1, 1, 1, 1/
      DATA IDEN/256/
C     ----------
C     BEGIN CODE
C     ----------
      NTRY(IMIRROR)=NTRY(IMIRROR)+1
      DO I=1,NEXTERNAL_BORN
        JC(I) = +1
      ENDDO

      IF (MULTI_CHANNEL) THEN
        DO I=1,NDIAGS
          AMP2(I)=0D0
        ENDDO
        JAMP2(0)=2
        DO I=1,INT(JAMP2(0))
          JAMP2(I)=0D0
        ENDDO
      ENDIF
      ANS = 0D0
      WRITE(HEL_BUFF,'(20I5)') (0,I=1,NEXTERNAL_BORN)
      DO I=1,NCOMB
        TS(I)=0D0
      ENDDO
      IF (ISHEL(IMIRROR) .EQ. 0 .OR. NTRY(IMIRROR) .LE. MAXTRIES) THEN
        DO I=1,NCOMB
          IF (GOODHEL(I,IMIRROR) .OR. NTRY(IMIRROR).LE.MAXTRIES) THEN
            T=P9_gg_epveemvexbbx1(P ,NHEL(1,I),JC(1))
            DO JJ=1,NINCOMING
              IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0
     $         ,POL(JJ)))) THEN
                T=T*ABS(POL(JJ))
              ELSE IF(POL(JJ).NE.1D0)THEN
                T=T*(2D0-ABS(POL(JJ)))
              ENDIF
            ENDDO
            ANS=ANS+DABS(T)
            TS(I)=T
          ENDIF
        ENDDO
        JHEL(IMIRROR) = 1
        IF(NTRY(IMIRROR).LE.MAXTRIES)THEN
          DO I=1,NCOMB
            IF (.NOT.GOODHEL(I,IMIRROR) .AND. (DABS(TS(I)).GT.ANS
     $       *LIMHEL/NCOMB)) THEN
              GOODHEL(I,IMIRROR)=.TRUE.
              NGOOD(IMIRROR) = NGOOD(IMIRROR) +1
              IGOOD(NGOOD(IMIRROR),IMIRROR) = I
              PRINT *,'Added good helicity ',I,TS(I)*NCOMB/ANS
     $         ,' in event ',NTRY(IMIRROR)
            ENDIF
          ENDDO
        ENDIF
        IF(NTRY(IMIRROR).EQ.MAXTRIES)THEN
          ISHEL(IMIRROR)=MIN(ISUM_HEL,NGOOD(IMIRROR))
        ENDIF
      ELSE  !LOOP OVER GOOD HELICITIES
        DO J=1,ISHEL(IMIRROR)
          JHEL(IMIRROR)=JHEL(IMIRROR)+1
          IF (JHEL(IMIRROR) .GT. NGOOD(IMIRROR)) JHEL(IMIRROR)=1
          HWGT = REAL(NGOOD(IMIRROR))/REAL(ISHEL(IMIRROR))
          I = IGOOD(JHEL(IMIRROR),IMIRROR)
          T=P9_gg_epveemvexbbx1(P ,NHEL(1,I),JC(1))
          DO JJ=1,NINCOMING
            IF(POL(JJ).NE.1D0.AND.NHEL(JJ,I).EQ.INT(SIGN(1D0,POL(JJ)))
     $       ) THEN
              T=T*ABS(POL(JJ))
            ELSE IF(POL(JJ).NE.1D0)THEN
              T=T*(2D0-ABS(POL(JJ)))
            ENDIF
          ENDDO
          ANS=ANS+DABS(T)*HWGT
          TS(I)=T*HWGT
        ENDDO
        IF (ISHEL(IMIRROR) .EQ. 1) THEN
          WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL_BORN)
C         Set right sign for ANS, based on sign of chosen helicity
          ANS=DSIGN(ANS,TS(I))
        ENDIF
      ENDIF
      IF (ISHEL(IMIRROR) .NE. 1) THEN
        SUMHEL=0D0
        DO I=1,NCOMB
          SUMHEL=SUMHEL+DABS(TS(I))/ANS
          IF(R.LT.SUMHEL)THEN
            WRITE(HEL_BUFF,'(20i5)')(NHEL(II,I),II=1,NEXTERNAL_BORN)
C           Set right sign for ANS, based on sign of chosen helicity
            ANS=DSIGN(ANS,TS(I))
            GOTO 10
          ENDIF
        ENDDO
 10     CONTINUE
      ENDIF
      IF (MULTI_CHANNEL) THEN
        XTOT=0D0
        DO I=1,NDIAGS
          XTOT=XTOT+AMP2(I)
        ENDDO
        IF (XTOT.NE.0D0) THEN
          ANS=ANS*AMP2(SUBDIAG(1))/XTOT
        ELSE
          ANS=0D0
        ENDIF
      ENDIF
      ANS=ANS/DBLE(IDEN)
      END


      REAL*8 FUNCTION P9_gg_epveemvexbbx1(P,NHEL,IC)
C     
C     Generated by MadGraph 5 v. 1.5.13, 2013-11-04
C     By the MadGraph Development Team
C     Please visit us at https://launchpad.net/madgraph5
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL_BORN)
C     
C     Process: g g > e+ ve e- ve~ b b~ QCD=2 QED=4 @9
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=203)
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal_born.inc'
      INCLUDE 'maxamps_P9_gg_epveemvexbbx.inc'
      INTEGER    NWAVEFUNCS,     NCOLOR
      PARAMETER (NWAVEFUNCS=42, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL_BORN)
      INTEGER NHEL(NEXTERNAL_BORN), IC(NEXTERNAL_BORN)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C     Needed for v4 models
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(MAXAMPS), JAMP2(0:MAXFLOW)
      COMMON/TO_AMPS_P9_gg_epveemvexbbx/  AMP2,       JAMP2
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM(1)/3/
      DATA (CF(I,  1),I=  1,  2) /   16,   -2/
C     1 T(1,2,7,8)
      DATA DENOM(2)/3/
      DATA (CF(I,  2),I=  1,  2) /   -2,   16/
C     1 T(2,1,7,8)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1*IC(1),W(1,1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1*IC(2),W(1,2))
      CALL IXXXXX(P(0,3),ZERO,NHEL(3),-1*IC(3),W(1,3))
      CALL OXXXXX(P(0,4),ZERO,NHEL(4),+1*IC(4),W(1,4))
      CALL OXXXXX(P(0,5),ZERO,NHEL(5),+1*IC(5),W(1,5))
      CALL IXXXXX(P(0,6),ZERO,NHEL(6),-1*IC(6),W(1,6))
      CALL OXXXXX(P(0,7),MB,NHEL(7),+1*IC(7),W(1,7))
      CALL IXXXXX(P(0,8),MB,NHEL(8),-1*IC(8),W(1,8))
      CALL VVV1P0_1(W(1,1),W(1,2),GC_10,ZERO,ZERO,W(1,9))
      CALL FFV2_3(W(1,3),W(1,4),GC_100,MW,WW,W(1,10))
      CALL FFV1_1(W(1,7),W(1,9),GC_11,MB,ZERO,W(1,11))
      CALL FFV2_1(W(1,5),W(1,10),GC_100,ZERO,ZERO,W(1,12))
      CALL FFV2_3_3(W(1,8),W(1,11),GC_50,GC_58,MZ,WZ,W(1,13))
C     Amplitude(s) for diagram number 1
      CALL FFV2_0(W(1,6),W(1,12),W(1,13),GC_62,AMP(1))
      CALL FFV2_2(W(1,6),W(1,10),GC_100,ZERO,ZERO,W(1,14))
      CALL FFV1P0_3(W(1,8),W(1,11),GC_1,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(1,14),W(1,5),W(1,15),GC_3,AMP(2))
C     Amplitude(s) for diagram number 3
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,13),GC_50,GC_59,AMP(3))
      CALL FFV1_2(W(1,8),W(1,9),GC_11,MB,ZERO,W(1,16))
      CALL FFV2_3_3(W(1,16),W(1,7),GC_50,GC_58,MZ,WZ,W(1,17))
C     Amplitude(s) for diagram number 4
      CALL FFV2_0(W(1,6),W(1,12),W(1,17),GC_62,AMP(4))
      CALL FFV1P0_3(W(1,16),W(1,7),GC_1,ZERO,ZERO,W(1,18))
C     Amplitude(s) for diagram number 5
      CALL FFV1_0(W(1,14),W(1,5),W(1,18),GC_3,AMP(5))
C     Amplitude(s) for diagram number 6
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,17),GC_50,GC_59,AMP(6))
      CALL FFV2_3(W(1,6),W(1,5),GC_100,MW,WW,W(1,19))
      CALL VVV1P0_1(W(1,19),W(1,10),GC_4,ZERO,ZERO,W(1,20))
C     Amplitude(s) for diagram number 7
      CALL FFV1_0(W(1,8),W(1,11),W(1,20),GC_1,AMP(7))
      CALL VVS1_3(W(1,19),W(1,10),GC_72,MH,WH,W(1,21))
C     Amplitude(s) for diagram number 8
      CALL FFS4_0(W(1,8),W(1,11),W(1,21),GC_83,AMP(8))
      CALL VVV1_3(W(1,19),W(1,10),GC_53,MZ,WZ,W(1,22))
C     Amplitude(s) for diagram number 9
      CALL FFV2_3_0(W(1,8),W(1,11),W(1,22),GC_50,GC_58,AMP(9))
      CALL FFV2_2(W(1,8),W(1,19),GC_100,MT,WT,W(1,23))
C     Amplitude(s) for diagram number 10
      CALL FFV2_0(W(1,23),W(1,11),W(1,10),GC_100,AMP(10))
C     Amplitude(s) for diagram number 11
      CALL FFV1_0(W(1,16),W(1,7),W(1,20),GC_1,AMP(11))
C     Amplitude(s) for diagram number 12
      CALL FFS4_0(W(1,16),W(1,7),W(1,21),GC_83,AMP(12))
C     Amplitude(s) for diagram number 13
      CALL FFV2_3_0(W(1,16),W(1,7),W(1,22),GC_50,GC_58,AMP(13))
      CALL FFV2_1(W(1,7),W(1,10),GC_100,MT,WT,W(1,24))
C     Amplitude(s) for diagram number 14
      CALL FFV2_0(W(1,16),W(1,24),W(1,19),GC_100,AMP(14))
C     Amplitude(s) for diagram number 15
      CALL FFV1_0(W(1,23),W(1,24),W(1,9),GC_11,AMP(15))
      CALL FFV2_4_3(W(1,3),W(1,5),GC_50,GC_59,MZ,WZ,W(1,25))
      CALL FFV2_1(W(1,4),W(1,25),GC_62,ZERO,ZERO,W(1,26))
C     Amplitude(s) for diagram number 16
      CALL FFV2_0(W(1,6),W(1,26),W(1,13),GC_62,AMP(16))
      CALL FFV2_2(W(1,6),W(1,25),GC_62,ZERO,ZERO,W(1,27))
C     Amplitude(s) for diagram number 17
      CALL FFV2_0(W(1,27),W(1,4),W(1,13),GC_62,AMP(17))
C     Amplitude(s) for diagram number 18
      CALL FFV2_0(W(1,6),W(1,26),W(1,17),GC_62,AMP(18))
C     Amplitude(s) for diagram number 19
      CALL FFV2_0(W(1,27),W(1,4),W(1,17),GC_62,AMP(19))
      CALL FFV1P0_3(W(1,3),W(1,5),GC_3,ZERO,ZERO,W(1,28))
      CALL FFV2_3(W(1,6),W(1,4),GC_62,MZ,WZ,W(1,29))
      CALL FFV1_2(W(1,8),W(1,28),GC_1,MB,ZERO,W(1,30))
C     Amplitude(s) for diagram number 20
      CALL FFV2_3_0(W(1,30),W(1,11),W(1,29),GC_50,GC_58,AMP(20))
      CALL FFV2_3_2(W(1,8),W(1,29),GC_50,GC_58,MB,ZERO,W(1,31))
C     Amplitude(s) for diagram number 21
      CALL FFV1_0(W(1,31),W(1,11),W(1,28),GC_1,AMP(21))
      CALL FFV1_1(W(1,7),W(1,28),GC_1,MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 22
      CALL FFV2_3_0(W(1,16),W(1,32),W(1,29),GC_50,GC_58,AMP(22))
      CALL FFV2_3_1(W(1,7),W(1,29),GC_50,GC_58,MB,ZERO,W(1,33))
C     Amplitude(s) for diagram number 23
      CALL FFV1_0(W(1,16),W(1,33),W(1,28),GC_1,AMP(23))
C     Amplitude(s) for diagram number 24
      CALL FFV1_0(W(1,31),W(1,32),W(1,9),GC_11,AMP(24))
C     Amplitude(s) for diagram number 25
      CALL FFV1_0(W(1,30),W(1,33),W(1,9),GC_11,AMP(25))
      CALL VVS1_3(W(1,25),W(1,29),GC_81,MH,WH,W(1,34))
C     Amplitude(s) for diagram number 26
      CALL FFS4_0(W(1,8),W(1,11),W(1,34),GC_83,AMP(26))
      CALL FFV2_3_2(W(1,8),W(1,25),GC_50,GC_58,MB,ZERO,W(1,35))
C     Amplitude(s) for diagram number 27
      CALL FFV2_3_0(W(1,35),W(1,11),W(1,29),GC_50,GC_58,AMP(27))
C     Amplitude(s) for diagram number 28
      CALL FFV2_3_0(W(1,31),W(1,11),W(1,25),GC_50,GC_58,AMP(28))
C     Amplitude(s) for diagram number 29
      CALL FFS4_0(W(1,16),W(1,7),W(1,34),GC_83,AMP(29))
      CALL FFV2_3_1(W(1,7),W(1,25),GC_50,GC_58,MB,ZERO,W(1,11))
C     Amplitude(s) for diagram number 30
      CALL FFV2_3_0(W(1,16),W(1,11),W(1,29),GC_50,GC_58,AMP(30))
C     Amplitude(s) for diagram number 31
      CALL FFV2_3_0(W(1,16),W(1,33),W(1,25),GC_50,GC_58,AMP(31))
C     Amplitude(s) for diagram number 32
      CALL FFV1_0(W(1,31),W(1,11),W(1,9),GC_11,AMP(32))
C     Amplitude(s) for diagram number 33
      CALL FFV1_0(W(1,35),W(1,33),W(1,9),GC_11,AMP(33))
      CALL FFV2_4_2(W(1,3),W(1,29),GC_50,GC_59,ZERO,ZERO,W(1,9))
C     Amplitude(s) for diagram number 34
      CALL FFV1_0(W(1,9),W(1,5),W(1,15),GC_3,AMP(34))
C     Amplitude(s) for diagram number 35
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,13),GC_50,GC_59,AMP(35))
      CALL FFV2_4_1(W(1,5),W(1,29),GC_50,GC_59,ZERO,ZERO,W(1,16))
C     Amplitude(s) for diagram number 36
      CALL FFV1_0(W(1,3),W(1,16),W(1,15),GC_3,AMP(36))
C     Amplitude(s) for diagram number 37
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,13),GC_50,GC_59,AMP(37))
C     Amplitude(s) for diagram number 38
      CALL FFV1_0(W(1,9),W(1,5),W(1,18),GC_3,AMP(38))
C     Amplitude(s) for diagram number 39
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,17),GC_50,GC_59,AMP(39))
C     Amplitude(s) for diagram number 40
      CALL FFV1_0(W(1,3),W(1,16),W(1,18),GC_3,AMP(40))
C     Amplitude(s) for diagram number 41
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,17),GC_50,GC_59,AMP(41))
      CALL FFV2_2(W(1,3),W(1,19),GC_100,ZERO,ZERO,W(1,36))
C     Amplitude(s) for diagram number 42
      CALL FFV2_0(W(1,36),W(1,4),W(1,13),GC_62,AMP(42))
      CALL FFV2_1(W(1,4),W(1,19),GC_100,ZERO,ZERO,W(1,37))
C     Amplitude(s) for diagram number 43
      CALL FFV1_0(W(1,3),W(1,37),W(1,15),GC_3,AMP(43))
C     Amplitude(s) for diagram number 44
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,13),GC_50,GC_59,AMP(44))
C     Amplitude(s) for diagram number 45
      CALL FFV2_0(W(1,36),W(1,4),W(1,17),GC_62,AMP(45))
C     Amplitude(s) for diagram number 46
      CALL FFV1_0(W(1,3),W(1,37),W(1,18),GC_3,AMP(46))
C     Amplitude(s) for diagram number 47
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,17),GC_50,GC_59,AMP(47))
      CALL FFV1_1(W(1,7),W(1,1),GC_11,MB,ZERO,W(1,17))
      CALL FFV1_2(W(1,8),W(1,2),GC_11,MB,ZERO,W(1,18))
      CALL FFV2_3_3(W(1,18),W(1,17),GC_50,GC_58,MZ,WZ,W(1,13))
C     Amplitude(s) for diagram number 48
      CALL FFV2_0(W(1,6),W(1,12),W(1,13),GC_62,AMP(48))
      CALL FFV1P0_3(W(1,18),W(1,17),GC_1,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 49
      CALL FFV1_0(W(1,14),W(1,5),W(1,15),GC_3,AMP(49))
C     Amplitude(s) for diagram number 50
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,13),GC_50,GC_59,AMP(50))
C     Amplitude(s) for diagram number 51
      CALL VVV1_0(W(1,15),W(1,19),W(1,10),GC_4,AMP(51))
      CALL FFS4_3(W(1,18),W(1,17),GC_83,MH,WH,W(1,38))
C     Amplitude(s) for diagram number 52
      CALL VVS1_0(W(1,19),W(1,10),W(1,38),GC_72,AMP(52))
C     Amplitude(s) for diagram number 53
      CALL VVV1_0(W(1,19),W(1,10),W(1,13),GC_53,AMP(53))
      CALL FFV2_1(W(1,17),W(1,10),GC_100,MT,WT,W(1,39))
C     Amplitude(s) for diagram number 54
      CALL FFV2_0(W(1,18),W(1,39),W(1,19),GC_100,AMP(54))
C     Amplitude(s) for diagram number 55
      CALL FFV2_0(W(1,6),W(1,26),W(1,13),GC_62,AMP(55))
C     Amplitude(s) for diagram number 56
      CALL FFV2_0(W(1,27),W(1,4),W(1,13),GC_62,AMP(56))
      CALL FFV1_1(W(1,17),W(1,28),GC_1,MB,ZERO,W(1,40))
C     Amplitude(s) for diagram number 57
      CALL FFV2_3_0(W(1,18),W(1,40),W(1,29),GC_50,GC_58,AMP(57))
      CALL FFV2_3_1(W(1,17),W(1,29),GC_50,GC_58,MB,ZERO,W(1,41))
C     Amplitude(s) for diagram number 58
      CALL FFV1_0(W(1,18),W(1,41),W(1,28),GC_1,AMP(58))
C     Amplitude(s) for diagram number 59
      CALL VVS1_0(W(1,25),W(1,29),W(1,38),GC_81,AMP(59))
      CALL FFV2_3_1(W(1,17),W(1,25),GC_50,GC_58,MB,ZERO,W(1,38))
C     Amplitude(s) for diagram number 60
      CALL FFV2_3_0(W(1,18),W(1,38),W(1,29),GC_50,GC_58,AMP(60))
C     Amplitude(s) for diagram number 61
      CALL FFV2_3_0(W(1,18),W(1,41),W(1,25),GC_50,GC_58,AMP(61))
C     Amplitude(s) for diagram number 62
      CALL FFV1_0(W(1,9),W(1,5),W(1,15),GC_3,AMP(62))
C     Amplitude(s) for diagram number 63
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,13),GC_50,GC_59,AMP(63))
C     Amplitude(s) for diagram number 64
      CALL FFV1_0(W(1,3),W(1,16),W(1,15),GC_3,AMP(64))
C     Amplitude(s) for diagram number 65
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,13),GC_50,GC_59,AMP(65))
C     Amplitude(s) for diagram number 66
      CALL FFV2_0(W(1,36),W(1,4),W(1,13),GC_62,AMP(66))
C     Amplitude(s) for diagram number 67
      CALL FFV1_0(W(1,3),W(1,37),W(1,15),GC_3,AMP(67))
C     Amplitude(s) for diagram number 68
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,13),GC_50,GC_59,AMP(68))
      CALL FFV1_1(W(1,17),W(1,2),GC_11,MB,ZERO,W(1,13))
      CALL FFV2_3_3(W(1,8),W(1,13),GC_50,GC_58,MZ,WZ,W(1,17))
C     Amplitude(s) for diagram number 69
      CALL FFV2_0(W(1,6),W(1,12),W(1,17),GC_62,AMP(69))
      CALL FFV1P0_3(W(1,8),W(1,13),GC_1,ZERO,ZERO,W(1,15))
C     Amplitude(s) for diagram number 70
      CALL FFV1_0(W(1,14),W(1,5),W(1,15),GC_3,AMP(70))
C     Amplitude(s) for diagram number 71
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,17),GC_50,GC_59,AMP(71))
C     Amplitude(s) for diagram number 72
      CALL FFV1_0(W(1,8),W(1,13),W(1,20),GC_1,AMP(72))
C     Amplitude(s) for diagram number 73
      CALL FFS4_0(W(1,8),W(1,13),W(1,21),GC_83,AMP(73))
C     Amplitude(s) for diagram number 74
      CALL FFV2_3_0(W(1,8),W(1,13),W(1,22),GC_50,GC_58,AMP(74))
C     Amplitude(s) for diagram number 75
      CALL FFV2_0(W(1,23),W(1,13),W(1,10),GC_100,AMP(75))
C     Amplitude(s) for diagram number 76
      CALL FFV1_0(W(1,23),W(1,39),W(1,2),GC_11,AMP(76))
C     Amplitude(s) for diagram number 77
      CALL FFV2_0(W(1,6),W(1,26),W(1,17),GC_62,AMP(77))
C     Amplitude(s) for diagram number 78
      CALL FFV2_0(W(1,27),W(1,4),W(1,17),GC_62,AMP(78))
C     Amplitude(s) for diagram number 79
      CALL FFV2_3_0(W(1,30),W(1,13),W(1,29),GC_50,GC_58,AMP(79))
C     Amplitude(s) for diagram number 80
      CALL FFV1_0(W(1,31),W(1,13),W(1,28),GC_1,AMP(80))
C     Amplitude(s) for diagram number 81
      CALL FFV1_0(W(1,31),W(1,40),W(1,2),GC_11,AMP(81))
C     Amplitude(s) for diagram number 82
      CALL FFV1_0(W(1,30),W(1,41),W(1,2),GC_11,AMP(82))
C     Amplitude(s) for diagram number 83
      CALL FFS4_0(W(1,8),W(1,13),W(1,34),GC_83,AMP(83))
C     Amplitude(s) for diagram number 84
      CALL FFV2_3_0(W(1,35),W(1,13),W(1,29),GC_50,GC_58,AMP(84))
C     Amplitude(s) for diagram number 85
      CALL FFV2_3_0(W(1,31),W(1,13),W(1,25),GC_50,GC_58,AMP(85))
C     Amplitude(s) for diagram number 86
      CALL FFV1_0(W(1,31),W(1,38),W(1,2),GC_11,AMP(86))
C     Amplitude(s) for diagram number 87
      CALL FFV1_0(W(1,35),W(1,41),W(1,2),GC_11,AMP(87))
C     Amplitude(s) for diagram number 88
      CALL FFV1_0(W(1,9),W(1,5),W(1,15),GC_3,AMP(88))
C     Amplitude(s) for diagram number 89
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,17),GC_50,GC_59,AMP(89))
C     Amplitude(s) for diagram number 90
      CALL FFV1_0(W(1,3),W(1,16),W(1,15),GC_3,AMP(90))
C     Amplitude(s) for diagram number 91
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,17),GC_50,GC_59,AMP(91))
C     Amplitude(s) for diagram number 92
      CALL FFV2_0(W(1,36),W(1,4),W(1,17),GC_62,AMP(92))
C     Amplitude(s) for diagram number 93
      CALL FFV1_0(W(1,3),W(1,37),W(1,15),GC_3,AMP(93))
C     Amplitude(s) for diagram number 94
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,17),GC_50,GC_59,AMP(94))
      CALL FFV1_2(W(1,8),W(1,1),GC_11,MB,ZERO,W(1,17))
      CALL FFV1_1(W(1,7),W(1,2),GC_11,MB,ZERO,W(1,15))
      CALL FFV2_3_3(W(1,17),W(1,15),GC_50,GC_58,MZ,WZ,W(1,41))
C     Amplitude(s) for diagram number 95
      CALL FFV2_0(W(1,6),W(1,12),W(1,41),GC_62,AMP(95))
      CALL FFV1P0_3(W(1,17),W(1,15),GC_1,ZERO,ZERO,W(1,38))
C     Amplitude(s) for diagram number 96
      CALL FFV1_0(W(1,14),W(1,5),W(1,38),GC_3,AMP(96))
C     Amplitude(s) for diagram number 97
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,41),GC_50,GC_59,AMP(97))
C     Amplitude(s) for diagram number 98
      CALL VVV1_0(W(1,38),W(1,19),W(1,10),GC_4,AMP(98))
      CALL FFS4_3(W(1,17),W(1,15),GC_83,MH,WH,W(1,13))
C     Amplitude(s) for diagram number 99
      CALL VVS1_0(W(1,19),W(1,10),W(1,13),GC_72,AMP(99))
C     Amplitude(s) for diagram number 100
      CALL VVV1_0(W(1,19),W(1,10),W(1,41),GC_53,AMP(100))
      CALL FFV2_2(W(1,17),W(1,19),GC_100,MT,WT,W(1,40))
C     Amplitude(s) for diagram number 101
      CALL FFV2_0(W(1,40),W(1,15),W(1,10),GC_100,AMP(101))
C     Amplitude(s) for diagram number 102
      CALL FFV2_0(W(1,6),W(1,26),W(1,41),GC_62,AMP(102))
C     Amplitude(s) for diagram number 103
      CALL FFV2_0(W(1,27),W(1,4),W(1,41),GC_62,AMP(103))
      CALL FFV1_2(W(1,17),W(1,28),GC_1,MB,ZERO,W(1,39))
C     Amplitude(s) for diagram number 104
      CALL FFV2_3_0(W(1,39),W(1,15),W(1,29),GC_50,GC_58,AMP(104))
      CALL FFV2_3_2(W(1,17),W(1,29),GC_50,GC_58,MB,ZERO,W(1,42))
C     Amplitude(s) for diagram number 105
      CALL FFV1_0(W(1,42),W(1,15),W(1,28),GC_1,AMP(105))
C     Amplitude(s) for diagram number 106
      CALL VVS1_0(W(1,25),W(1,29),W(1,13),GC_81,AMP(106))
      CALL FFV2_3_2(W(1,17),W(1,25),GC_50,GC_58,MB,ZERO,W(1,13))
C     Amplitude(s) for diagram number 107
      CALL FFV2_3_0(W(1,13),W(1,15),W(1,29),GC_50,GC_58,AMP(107))
C     Amplitude(s) for diagram number 108
      CALL FFV2_3_0(W(1,42),W(1,15),W(1,25),GC_50,GC_58,AMP(108))
C     Amplitude(s) for diagram number 109
      CALL FFV1_0(W(1,9),W(1,5),W(1,38),GC_3,AMP(109))
C     Amplitude(s) for diagram number 110
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,41),GC_50,GC_59,AMP(110))
C     Amplitude(s) for diagram number 111
      CALL FFV1_0(W(1,3),W(1,16),W(1,38),GC_3,AMP(111))
C     Amplitude(s) for diagram number 112
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,41),GC_50,GC_59,AMP(112))
C     Amplitude(s) for diagram number 113
      CALL FFV2_0(W(1,36),W(1,4),W(1,41),GC_62,AMP(113))
C     Amplitude(s) for diagram number 114
      CALL FFV1_0(W(1,3),W(1,37),W(1,38),GC_3,AMP(114))
C     Amplitude(s) for diagram number 115
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,41),GC_50,GC_59,AMP(115))
      CALL FFV1_2(W(1,17),W(1,2),GC_11,MB,ZERO,W(1,41))
      CALL FFV2_3_3(W(1,41),W(1,7),GC_50,GC_58,MZ,WZ,W(1,17))
C     Amplitude(s) for diagram number 116
      CALL FFV2_0(W(1,6),W(1,12),W(1,17),GC_62,AMP(116))
      CALL FFV1P0_3(W(1,41),W(1,7),GC_1,ZERO,ZERO,W(1,38))
C     Amplitude(s) for diagram number 117
      CALL FFV1_0(W(1,14),W(1,5),W(1,38),GC_3,AMP(117))
C     Amplitude(s) for diagram number 118
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,17),GC_50,GC_59,AMP(118))
C     Amplitude(s) for diagram number 119
      CALL FFV1_0(W(1,41),W(1,7),W(1,20),GC_1,AMP(119))
C     Amplitude(s) for diagram number 120
      CALL FFS4_0(W(1,41),W(1,7),W(1,21),GC_83,AMP(120))
C     Amplitude(s) for diagram number 121
      CALL FFV2_3_0(W(1,41),W(1,7),W(1,22),GC_50,GC_58,AMP(121))
C     Amplitude(s) for diagram number 122
      CALL FFV2_0(W(1,41),W(1,24),W(1,19),GC_100,AMP(122))
C     Amplitude(s) for diagram number 123
      CALL FFV1_0(W(1,40),W(1,24),W(1,2),GC_11,AMP(123))
C     Amplitude(s) for diagram number 124
      CALL FFV2_0(W(1,6),W(1,26),W(1,17),GC_62,AMP(124))
C     Amplitude(s) for diagram number 125
      CALL FFV2_0(W(1,27),W(1,4),W(1,17),GC_62,AMP(125))
C     Amplitude(s) for diagram number 126
      CALL FFV2_3_0(W(1,41),W(1,32),W(1,29),GC_50,GC_58,AMP(126))
C     Amplitude(s) for diagram number 127
      CALL FFV1_0(W(1,41),W(1,33),W(1,28),GC_1,AMP(127))
C     Amplitude(s) for diagram number 128
      CALL FFV1_0(W(1,39),W(1,33),W(1,2),GC_11,AMP(128))
C     Amplitude(s) for diagram number 129
      CALL FFV1_0(W(1,42),W(1,32),W(1,2),GC_11,AMP(129))
C     Amplitude(s) for diagram number 130
      CALL FFS4_0(W(1,41),W(1,7),W(1,34),GC_83,AMP(130))
C     Amplitude(s) for diagram number 131
      CALL FFV2_3_0(W(1,41),W(1,11),W(1,29),GC_50,GC_58,AMP(131))
C     Amplitude(s) for diagram number 132
      CALL FFV2_3_0(W(1,41),W(1,33),W(1,25),GC_50,GC_58,AMP(132))
C     Amplitude(s) for diagram number 133
      CALL FFV1_0(W(1,13),W(1,33),W(1,2),GC_11,AMP(133))
C     Amplitude(s) for diagram number 134
      CALL FFV1_0(W(1,42),W(1,11),W(1,2),GC_11,AMP(134))
C     Amplitude(s) for diagram number 135
      CALL FFV1_0(W(1,9),W(1,5),W(1,38),GC_3,AMP(135))
C     Amplitude(s) for diagram number 136
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,17),GC_50,GC_59,AMP(136))
C     Amplitude(s) for diagram number 137
      CALL FFV1_0(W(1,3),W(1,16),W(1,38),GC_3,AMP(137))
C     Amplitude(s) for diagram number 138
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,17),GC_50,GC_59,AMP(138))
C     Amplitude(s) for diagram number 139
      CALL FFV2_0(W(1,36),W(1,4),W(1,17),GC_62,AMP(139))
C     Amplitude(s) for diagram number 140
      CALL FFV1_0(W(1,3),W(1,37),W(1,38),GC_3,AMP(140))
C     Amplitude(s) for diagram number 141
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,17),GC_50,GC_59,AMP(141))
      CALL FFV1_1(W(1,15),W(1,1),GC_11,MB,ZERO,W(1,17))
      CALL FFV2_3_3(W(1,8),W(1,17),GC_50,GC_58,MZ,WZ,W(1,38))
C     Amplitude(s) for diagram number 142
      CALL FFV2_0(W(1,6),W(1,12),W(1,38),GC_62,AMP(142))
      CALL FFV1P0_3(W(1,8),W(1,17),GC_1,ZERO,ZERO,W(1,42))
C     Amplitude(s) for diagram number 143
      CALL FFV1_0(W(1,14),W(1,5),W(1,42),GC_3,AMP(143))
C     Amplitude(s) for diagram number 144
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,38),GC_50,GC_59,AMP(144))
C     Amplitude(s) for diagram number 145
      CALL FFV1_0(W(1,8),W(1,17),W(1,20),GC_1,AMP(145))
C     Amplitude(s) for diagram number 146
      CALL FFS4_0(W(1,8),W(1,17),W(1,21),GC_83,AMP(146))
C     Amplitude(s) for diagram number 147
      CALL FFV2_3_0(W(1,8),W(1,17),W(1,22),GC_50,GC_58,AMP(147))
C     Amplitude(s) for diagram number 148
      CALL FFV2_0(W(1,23),W(1,17),W(1,10),GC_100,AMP(148))
      CALL FFV2_1(W(1,15),W(1,10),GC_100,MT,WT,W(1,13))
C     Amplitude(s) for diagram number 149
      CALL FFV1_0(W(1,23),W(1,13),W(1,1),GC_11,AMP(149))
C     Amplitude(s) for diagram number 150
      CALL FFV2_0(W(1,6),W(1,26),W(1,38),GC_62,AMP(150))
C     Amplitude(s) for diagram number 151
      CALL FFV2_0(W(1,27),W(1,4),W(1,38),GC_62,AMP(151))
C     Amplitude(s) for diagram number 152
      CALL FFV2_3_0(W(1,30),W(1,17),W(1,29),GC_50,GC_58,AMP(152))
C     Amplitude(s) for diagram number 153
      CALL FFV1_0(W(1,31),W(1,17),W(1,28),GC_1,AMP(153))
      CALL FFV1_1(W(1,15),W(1,28),GC_1,MB,ZERO,W(1,13))
C     Amplitude(s) for diagram number 154
      CALL FFV1_0(W(1,31),W(1,13),W(1,1),GC_11,AMP(154))
      CALL FFV2_3_1(W(1,15),W(1,29),GC_50,GC_58,MB,ZERO,W(1,13))
C     Amplitude(s) for diagram number 155
      CALL FFV1_0(W(1,30),W(1,13),W(1,1),GC_11,AMP(155))
C     Amplitude(s) for diagram number 156
      CALL FFS4_0(W(1,8),W(1,17),W(1,34),GC_83,AMP(156))
C     Amplitude(s) for diagram number 157
      CALL FFV2_3_0(W(1,35),W(1,17),W(1,29),GC_50,GC_58,AMP(157))
C     Amplitude(s) for diagram number 158
      CALL FFV2_3_0(W(1,31),W(1,17),W(1,25),GC_50,GC_58,AMP(158))
      CALL FFV2_3_1(W(1,15),W(1,25),GC_50,GC_58,MB,ZERO,W(1,17))
C     Amplitude(s) for diagram number 159
      CALL FFV1_0(W(1,31),W(1,17),W(1,1),GC_11,AMP(159))
C     Amplitude(s) for diagram number 160
      CALL FFV1_0(W(1,35),W(1,13),W(1,1),GC_11,AMP(160))
C     Amplitude(s) for diagram number 161
      CALL FFV1_0(W(1,9),W(1,5),W(1,42),GC_3,AMP(161))
C     Amplitude(s) for diagram number 162
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,38),GC_50,GC_59,AMP(162))
C     Amplitude(s) for diagram number 163
      CALL FFV1_0(W(1,3),W(1,16),W(1,42),GC_3,AMP(163))
C     Amplitude(s) for diagram number 164
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,38),GC_50,GC_59,AMP(164))
C     Amplitude(s) for diagram number 165
      CALL FFV2_0(W(1,36),W(1,4),W(1,38),GC_62,AMP(165))
C     Amplitude(s) for diagram number 166
      CALL FFV1_0(W(1,3),W(1,37),W(1,42),GC_3,AMP(166))
C     Amplitude(s) for diagram number 167
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,38),GC_50,GC_59,AMP(167))
      CALL FFV1_2(W(1,18),W(1,1),GC_11,MB,ZERO,W(1,38))
      CALL FFV2_3_3(W(1,38),W(1,7),GC_50,GC_58,MZ,WZ,W(1,42))
C     Amplitude(s) for diagram number 168
      CALL FFV2_0(W(1,6),W(1,12),W(1,42),GC_62,AMP(168))
      CALL FFV1P0_3(W(1,38),W(1,7),GC_1,ZERO,ZERO,W(1,12))
C     Amplitude(s) for diagram number 169
      CALL FFV1_0(W(1,14),W(1,5),W(1,12),GC_3,AMP(169))
C     Amplitude(s) for diagram number 170
      CALL FFV2_4_0(W(1,14),W(1,5),W(1,42),GC_50,GC_59,AMP(170))
C     Amplitude(s) for diagram number 171
      CALL FFV1_0(W(1,38),W(1,7),W(1,20),GC_1,AMP(171))
C     Amplitude(s) for diagram number 172
      CALL FFS4_0(W(1,38),W(1,7),W(1,21),GC_83,AMP(172))
C     Amplitude(s) for diagram number 173
      CALL FFV2_3_0(W(1,38),W(1,7),W(1,22),GC_50,GC_58,AMP(173))
C     Amplitude(s) for diagram number 174
      CALL FFV2_0(W(1,38),W(1,24),W(1,19),GC_100,AMP(174))
      CALL FFV2_2(W(1,18),W(1,19),GC_100,MT,WT,W(1,22))
C     Amplitude(s) for diagram number 175
      CALL FFV1_0(W(1,22),W(1,24),W(1,1),GC_11,AMP(175))
C     Amplitude(s) for diagram number 176
      CALL FFV2_0(W(1,6),W(1,26),W(1,42),GC_62,AMP(176))
C     Amplitude(s) for diagram number 177
      CALL FFV2_0(W(1,27),W(1,4),W(1,42),GC_62,AMP(177))
C     Amplitude(s) for diagram number 178
      CALL FFV2_3_0(W(1,38),W(1,32),W(1,29),GC_50,GC_58,AMP(178))
C     Amplitude(s) for diagram number 179
      CALL FFV1_0(W(1,38),W(1,33),W(1,28),GC_1,AMP(179))
      CALL FFV1_2(W(1,18),W(1,28),GC_1,MB,ZERO,W(1,27))
C     Amplitude(s) for diagram number 180
      CALL FFV1_0(W(1,27),W(1,33),W(1,1),GC_11,AMP(180))
      CALL FFV2_3_2(W(1,18),W(1,29),GC_50,GC_58,MB,ZERO,W(1,27))
C     Amplitude(s) for diagram number 181
      CALL FFV1_0(W(1,27),W(1,32),W(1,1),GC_11,AMP(181))
C     Amplitude(s) for diagram number 182
      CALL FFS4_0(W(1,38),W(1,7),W(1,34),GC_83,AMP(182))
C     Amplitude(s) for diagram number 183
      CALL FFV2_3_0(W(1,38),W(1,11),W(1,29),GC_50,GC_58,AMP(183))
C     Amplitude(s) for diagram number 184
      CALL FFV2_3_0(W(1,38),W(1,33),W(1,25),GC_50,GC_58,AMP(184))
      CALL FFV2_3_2(W(1,18),W(1,25),GC_50,GC_58,MB,ZERO,W(1,38))
C     Amplitude(s) for diagram number 185
      CALL FFV1_0(W(1,38),W(1,33),W(1,1),GC_11,AMP(185))
C     Amplitude(s) for diagram number 186
      CALL FFV1_0(W(1,27),W(1,11),W(1,1),GC_11,AMP(186))
C     Amplitude(s) for diagram number 187
      CALL FFV1_0(W(1,9),W(1,5),W(1,12),GC_3,AMP(187))
C     Amplitude(s) for diagram number 188
      CALL FFV2_4_0(W(1,9),W(1,5),W(1,42),GC_50,GC_59,AMP(188))
C     Amplitude(s) for diagram number 189
      CALL FFV1_0(W(1,3),W(1,16),W(1,12),GC_3,AMP(189))
C     Amplitude(s) for diagram number 190
      CALL FFV2_4_0(W(1,3),W(1,16),W(1,42),GC_50,GC_59,AMP(190))
C     Amplitude(s) for diagram number 191
      CALL FFV2_0(W(1,36),W(1,4),W(1,42),GC_62,AMP(191))
C     Amplitude(s) for diagram number 192
      CALL FFV1_0(W(1,3),W(1,37),W(1,12),GC_3,AMP(192))
C     Amplitude(s) for diagram number 193
      CALL FFV2_4_0(W(1,3),W(1,37),W(1,42),GC_50,GC_59,AMP(193))
      CALL FFV1_1(W(1,24),W(1,1),GC_11,MT,WT,W(1,42))
C     Amplitude(s) for diagram number 194
      CALL FFV1_0(W(1,23),W(1,42),W(1,2),GC_11,AMP(194))
      CALL FFV1_2(W(1,23),W(1,1),GC_11,MT,WT,W(1,42))
C     Amplitude(s) for diagram number 195
      CALL FFV1_0(W(1,42),W(1,24),W(1,2),GC_11,AMP(195))
      CALL FFV1_1(W(1,32),W(1,1),GC_11,MB,ZERO,W(1,42))
C     Amplitude(s) for diagram number 196
      CALL FFV1_0(W(1,31),W(1,42),W(1,2),GC_11,AMP(196))
      CALL FFV1_2(W(1,31),W(1,1),GC_11,MB,ZERO,W(1,42))
C     Amplitude(s) for diagram number 197
      CALL FFV1_0(W(1,42),W(1,32),W(1,2),GC_11,AMP(197))
      CALL FFV1_2(W(1,30),W(1,1),GC_11,MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 198
      CALL FFV1_0(W(1,32),W(1,33),W(1,2),GC_11,AMP(198))
      CALL FFV1_1(W(1,33),W(1,1),GC_11,MB,ZERO,W(1,32))
C     Amplitude(s) for diagram number 199
      CALL FFV1_0(W(1,30),W(1,32),W(1,2),GC_11,AMP(199))
      CALL FFV1_1(W(1,11),W(1,1),GC_11,MB,ZERO,W(1,30))
C     Amplitude(s) for diagram number 200
      CALL FFV1_0(W(1,31),W(1,30),W(1,2),GC_11,AMP(200))
C     Amplitude(s) for diagram number 201
      CALL FFV1_0(W(1,42),W(1,11),W(1,2),GC_11,AMP(201))
      CALL FFV1_2(W(1,35),W(1,1),GC_11,MB,ZERO,W(1,42))
C     Amplitude(s) for diagram number 202
      CALL FFV1_0(W(1,42),W(1,33),W(1,2),GC_11,AMP(202))
C     Amplitude(s) for diagram number 203
      CALL FFV1_0(W(1,35),W(1,32),W(1,2),GC_11,AMP(203))
      JAMP(1)=-IMAG1*AMP(1)-IMAG1*AMP(2)-IMAG1*AMP(3)-IMAG1*AMP(4)
     $ -IMAG1*AMP(5)-IMAG1*AMP(6)-IMAG1*AMP(7)-IMAG1*AMP(8)-IMAG1
     $ *AMP(9)-IMAG1*AMP(10)-IMAG1*AMP(11)-IMAG1*AMP(12)-IMAG1*AMP(13)
     $ -IMAG1*AMP(14)-IMAG1*AMP(15)+IMAG1*AMP(16)+IMAG1*AMP(17)
     $ +IMAG1*AMP(18)+IMAG1*AMP(19)+IMAG1*AMP(20)+IMAG1*AMP(21)
     $ +IMAG1*AMP(22)+IMAG1*AMP(23)+IMAG1*AMP(24)+IMAG1*AMP(25)
     $ +IMAG1*AMP(26)+IMAG1*AMP(27)+IMAG1*AMP(28)+IMAG1*AMP(29)
     $ +IMAG1*AMP(30)+IMAG1*AMP(31)+IMAG1*AMP(32)+IMAG1*AMP(33)
     $ +IMAG1*AMP(34)+IMAG1*AMP(35)+IMAG1*AMP(36)+IMAG1*AMP(37)
     $ +IMAG1*AMP(38)+IMAG1*AMP(39)+IMAG1*AMP(40)+IMAG1*AMP(41)
     $ -IMAG1*AMP(42)-IMAG1*AMP(43)-IMAG1*AMP(44)-IMAG1*AMP(45)
     $ -IMAG1*AMP(46)-IMAG1*AMP(47)+AMP(48)+AMP(49)+AMP(50)+AMP(51)
     $ +AMP(52)+AMP(53)+AMP(54)-AMP(55)-AMP(56)-AMP(57)-AMP(58)
     $ -AMP(59)-AMP(60)-AMP(61)-AMP(62)-AMP(63)-AMP(64)-AMP(65)
     $ +AMP(66)+AMP(67)+AMP(68)+AMP(69)+AMP(70)+AMP(71)+AMP(72)
     $ +AMP(73)+AMP(74)+AMP(75)+AMP(76)-AMP(77)-AMP(78)-AMP(79)
     $ -AMP(80)-AMP(81)-AMP(82)-AMP(83)-AMP(84)-AMP(85)-AMP(86)
     $ -AMP(87)-AMP(88)-AMP(89)-AMP(90)-AMP(91)+AMP(92)+AMP(93)
     $ +AMP(94)+AMP(168)+AMP(169)+AMP(170)+AMP(171)+AMP(172)+AMP(173)
     $ +AMP(174)+AMP(175)-AMP(176)-AMP(177)-AMP(178)-AMP(179)-AMP(180)
     $ -AMP(181)-AMP(182)-AMP(183)-AMP(184)-AMP(185)-AMP(186)-AMP(187)
     $ -AMP(188)-AMP(189)-AMP(190)+AMP(191)+AMP(192)+AMP(193)
     $ +AMP(194)-AMP(196)-AMP(199)-AMP(200)-AMP(203)
      JAMP(2)=+IMAG1*AMP(1)+IMAG1*AMP(2)+IMAG1*AMP(3)+IMAG1*AMP(4)
     $ +IMAG1*AMP(5)+IMAG1*AMP(6)+IMAG1*AMP(7)+IMAG1*AMP(8)+IMAG1
     $ *AMP(9)+IMAG1*AMP(10)+IMAG1*AMP(11)+IMAG1*AMP(12)+IMAG1*AMP(13)
     $ +IMAG1*AMP(14)+IMAG1*AMP(15)-IMAG1*AMP(16)-IMAG1*AMP(17)
     $ -IMAG1*AMP(18)-IMAG1*AMP(19)-IMAG1*AMP(20)-IMAG1*AMP(21)
     $ -IMAG1*AMP(22)-IMAG1*AMP(23)-IMAG1*AMP(24)-IMAG1*AMP(25)
     $ -IMAG1*AMP(26)-IMAG1*AMP(27)-IMAG1*AMP(28)-IMAG1*AMP(29)
     $ -IMAG1*AMP(30)-IMAG1*AMP(31)-IMAG1*AMP(32)-IMAG1*AMP(33)
     $ -IMAG1*AMP(34)-IMAG1*AMP(35)-IMAG1*AMP(36)-IMAG1*AMP(37)
     $ -IMAG1*AMP(38)-IMAG1*AMP(39)-IMAG1*AMP(40)-IMAG1*AMP(41)
     $ +IMAG1*AMP(42)+IMAG1*AMP(43)+IMAG1*AMP(44)+IMAG1*AMP(45)
     $ +IMAG1*AMP(46)+IMAG1*AMP(47)+AMP(95)+AMP(96)+AMP(97)+AMP(98)
     $ +AMP(99)+AMP(100)+AMP(101)-AMP(102)-AMP(103)-AMP(104)-AMP(105)
     $ -AMP(106)-AMP(107)-AMP(108)-AMP(109)-AMP(110)-AMP(111)-AMP(112)
     $ +AMP(113)+AMP(114)+AMP(115)+AMP(116)+AMP(117)+AMP(118)+AMP(119)
     $ +AMP(120)+AMP(121)+AMP(122)+AMP(123)-AMP(124)-AMP(125)-AMP(126)
     $ -AMP(127)-AMP(128)-AMP(129)-AMP(130)-AMP(131)-AMP(132)-AMP(133)
     $ -AMP(134)-AMP(135)-AMP(136)-AMP(137)-AMP(138)+AMP(139)+AMP(140)
     $ +AMP(141)+AMP(142)+AMP(143)+AMP(144)+AMP(145)+AMP(146)+AMP(147)
     $ +AMP(148)+AMP(149)-AMP(150)-AMP(151)-AMP(152)-AMP(153)-AMP(154)
     $ -AMP(155)-AMP(156)-AMP(157)-AMP(158)-AMP(159)-AMP(160)-AMP(161)
     $ -AMP(162)-AMP(163)-AMP(164)+AMP(165)+AMP(166)+AMP(167)
     $ +AMP(195)-AMP(197)-AMP(198)-AMP(201)-AMP(202)
      P9_gg_epveemvexbbx1 = 0.D0
      DO I = 1, NCOLOR
        ZTEMP = (0.D0,0.D0)
        DO J = 1, NCOLOR
          ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
        ENDDO
        P9_gg_epveemvexbbx1=P9_gg_epveemvexbbx1+ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO
      AMP2(1)=AMP2(1)+AMP(1)*DCONJG(AMP(1))
      AMP2(2)=AMP2(2)+AMP(2)*DCONJG(AMP(2))
      AMP2(3)=AMP2(3)+AMP(3)*DCONJG(AMP(3))
      AMP2(4)=AMP2(4)+AMP(4)*DCONJG(AMP(4))
      AMP2(5)=AMP2(5)+AMP(5)*DCONJG(AMP(5))
      AMP2(6)=AMP2(6)+AMP(6)*DCONJG(AMP(6))
      AMP2(7)=AMP2(7)+AMP(7)*DCONJG(AMP(7))
      AMP2(8)=AMP2(8)+AMP(8)*DCONJG(AMP(8))
      AMP2(9)=AMP2(9)+AMP(9)*DCONJG(AMP(9))
      AMP2(10)=AMP2(10)+AMP(10)*DCONJG(AMP(10))
      AMP2(11)=AMP2(11)+AMP(11)*DCONJG(AMP(11))
      AMP2(12)=AMP2(12)+AMP(12)*DCONJG(AMP(12))
      AMP2(13)=AMP2(13)+AMP(13)*DCONJG(AMP(13))
      AMP2(14)=AMP2(14)+AMP(14)*DCONJG(AMP(14))
      AMP2(15)=AMP2(15)+AMP(15)*DCONJG(AMP(15))
      AMP2(16)=AMP2(16)+AMP(16)*DCONJG(AMP(16))
      AMP2(17)=AMP2(17)+AMP(17)*DCONJG(AMP(17))
      AMP2(18)=AMP2(18)+AMP(18)*DCONJG(AMP(18))
      AMP2(19)=AMP2(19)+AMP(19)*DCONJG(AMP(19))
      AMP2(20)=AMP2(20)+AMP(20)*DCONJG(AMP(20))
      AMP2(21)=AMP2(21)+AMP(21)*DCONJG(AMP(21))
      AMP2(22)=AMP2(22)+AMP(22)*DCONJG(AMP(22))
      AMP2(23)=AMP2(23)+AMP(23)*DCONJG(AMP(23))
      AMP2(24)=AMP2(24)+AMP(24)*DCONJG(AMP(24))
      AMP2(25)=AMP2(25)+AMP(25)*DCONJG(AMP(25))
      AMP2(26)=AMP2(26)+AMP(26)*DCONJG(AMP(26))
      AMP2(27)=AMP2(27)+AMP(27)*DCONJG(AMP(27))
      AMP2(28)=AMP2(28)+AMP(28)*DCONJG(AMP(28))
      AMP2(29)=AMP2(29)+AMP(29)*DCONJG(AMP(29))
      AMP2(30)=AMP2(30)+AMP(30)*DCONJG(AMP(30))
      AMP2(31)=AMP2(31)+AMP(31)*DCONJG(AMP(31))
      AMP2(32)=AMP2(32)+AMP(32)*DCONJG(AMP(32))
      AMP2(33)=AMP2(33)+AMP(33)*DCONJG(AMP(33))
      AMP2(34)=AMP2(34)+AMP(34)*DCONJG(AMP(34))
      AMP2(35)=AMP2(35)+AMP(35)*DCONJG(AMP(35))
      AMP2(36)=AMP2(36)+AMP(36)*DCONJG(AMP(36))
      AMP2(37)=AMP2(37)+AMP(37)*DCONJG(AMP(37))
      AMP2(38)=AMP2(38)+AMP(38)*DCONJG(AMP(38))
      AMP2(39)=AMP2(39)+AMP(39)*DCONJG(AMP(39))
      AMP2(40)=AMP2(40)+AMP(40)*DCONJG(AMP(40))
      AMP2(41)=AMP2(41)+AMP(41)*DCONJG(AMP(41))
      AMP2(42)=AMP2(42)+AMP(42)*DCONJG(AMP(42))
      AMP2(43)=AMP2(43)+AMP(43)*DCONJG(AMP(43))
      AMP2(44)=AMP2(44)+AMP(44)*DCONJG(AMP(44))
      AMP2(45)=AMP2(45)+AMP(45)*DCONJG(AMP(45))
      AMP2(46)=AMP2(46)+AMP(46)*DCONJG(AMP(46))
      AMP2(47)=AMP2(47)+AMP(47)*DCONJG(AMP(47))
      AMP2(48)=AMP2(48)+AMP(48)*DCONJG(AMP(48))
      AMP2(49)=AMP2(49)+AMP(49)*DCONJG(AMP(49))
      AMP2(50)=AMP2(50)+AMP(50)*DCONJG(AMP(50))
      AMP2(51)=AMP2(51)+AMP(51)*DCONJG(AMP(51))
      AMP2(52)=AMP2(52)+AMP(52)*DCONJG(AMP(52))
      AMP2(53)=AMP2(53)+AMP(53)*DCONJG(AMP(53))
      AMP2(54)=AMP2(54)+AMP(54)*DCONJG(AMP(54))
      AMP2(55)=AMP2(55)+AMP(55)*DCONJG(AMP(55))
      AMP2(56)=AMP2(56)+AMP(56)*DCONJG(AMP(56))
      AMP2(57)=AMP2(57)+AMP(57)*DCONJG(AMP(57))
      AMP2(58)=AMP2(58)+AMP(58)*DCONJG(AMP(58))
      AMP2(59)=AMP2(59)+AMP(59)*DCONJG(AMP(59))
      AMP2(60)=AMP2(60)+AMP(60)*DCONJG(AMP(60))
      AMP2(61)=AMP2(61)+AMP(61)*DCONJG(AMP(61))
      AMP2(62)=AMP2(62)+AMP(62)*DCONJG(AMP(62))
      AMP2(63)=AMP2(63)+AMP(63)*DCONJG(AMP(63))
      AMP2(64)=AMP2(64)+AMP(64)*DCONJG(AMP(64))
      AMP2(65)=AMP2(65)+AMP(65)*DCONJG(AMP(65))
      AMP2(66)=AMP2(66)+AMP(66)*DCONJG(AMP(66))
      AMP2(67)=AMP2(67)+AMP(67)*DCONJG(AMP(67))
      AMP2(68)=AMP2(68)+AMP(68)*DCONJG(AMP(68))
      AMP2(69)=AMP2(69)+AMP(69)*DCONJG(AMP(69))
      AMP2(70)=AMP2(70)+AMP(70)*DCONJG(AMP(70))
      AMP2(71)=AMP2(71)+AMP(71)*DCONJG(AMP(71))
      AMP2(72)=AMP2(72)+AMP(72)*DCONJG(AMP(72))
      AMP2(73)=AMP2(73)+AMP(73)*DCONJG(AMP(73))
      AMP2(74)=AMP2(74)+AMP(74)*DCONJG(AMP(74))
      AMP2(75)=AMP2(75)+AMP(75)*DCONJG(AMP(75))
      AMP2(76)=AMP2(76)+AMP(76)*DCONJG(AMP(76))
      AMP2(77)=AMP2(77)+AMP(77)*DCONJG(AMP(77))
      AMP2(78)=AMP2(78)+AMP(78)*DCONJG(AMP(78))
      AMP2(79)=AMP2(79)+AMP(79)*DCONJG(AMP(79))
      AMP2(80)=AMP2(80)+AMP(80)*DCONJG(AMP(80))
      AMP2(81)=AMP2(81)+AMP(81)*DCONJG(AMP(81))
      AMP2(82)=AMP2(82)+AMP(82)*DCONJG(AMP(82))
      AMP2(83)=AMP2(83)+AMP(83)*DCONJG(AMP(83))
      AMP2(84)=AMP2(84)+AMP(84)*DCONJG(AMP(84))
      AMP2(85)=AMP2(85)+AMP(85)*DCONJG(AMP(85))
      AMP2(86)=AMP2(86)+AMP(86)*DCONJG(AMP(86))
      AMP2(87)=AMP2(87)+AMP(87)*DCONJG(AMP(87))
      AMP2(88)=AMP2(88)+AMP(88)*DCONJG(AMP(88))
      AMP2(89)=AMP2(89)+AMP(89)*DCONJG(AMP(89))
      AMP2(90)=AMP2(90)+AMP(90)*DCONJG(AMP(90))
      AMP2(91)=AMP2(91)+AMP(91)*DCONJG(AMP(91))
      AMP2(92)=AMP2(92)+AMP(92)*DCONJG(AMP(92))
      AMP2(93)=AMP2(93)+AMP(93)*DCONJG(AMP(93))
      AMP2(94)=AMP2(94)+AMP(94)*DCONJG(AMP(94))
      AMP2(95)=AMP2(95)+AMP(95)*DCONJG(AMP(95))
      AMP2(96)=AMP2(96)+AMP(96)*DCONJG(AMP(96))
      AMP2(97)=AMP2(97)+AMP(97)*DCONJG(AMP(97))
      AMP2(98)=AMP2(98)+AMP(98)*DCONJG(AMP(98))
      AMP2(99)=AMP2(99)+AMP(99)*DCONJG(AMP(99))
      AMP2(100)=AMP2(100)+AMP(100)*DCONJG(AMP(100))
      AMP2(101)=AMP2(101)+AMP(101)*DCONJG(AMP(101))
      AMP2(102)=AMP2(102)+AMP(102)*DCONJG(AMP(102))
      AMP2(103)=AMP2(103)+AMP(103)*DCONJG(AMP(103))
      AMP2(104)=AMP2(104)+AMP(104)*DCONJG(AMP(104))
      AMP2(105)=AMP2(105)+AMP(105)*DCONJG(AMP(105))
      AMP2(106)=AMP2(106)+AMP(106)*DCONJG(AMP(106))
      AMP2(107)=AMP2(107)+AMP(107)*DCONJG(AMP(107))
      AMP2(108)=AMP2(108)+AMP(108)*DCONJG(AMP(108))
      AMP2(109)=AMP2(109)+AMP(109)*DCONJG(AMP(109))
      AMP2(110)=AMP2(110)+AMP(110)*DCONJG(AMP(110))
      AMP2(111)=AMP2(111)+AMP(111)*DCONJG(AMP(111))
      AMP2(112)=AMP2(112)+AMP(112)*DCONJG(AMP(112))
      AMP2(113)=AMP2(113)+AMP(113)*DCONJG(AMP(113))
      AMP2(114)=AMP2(114)+AMP(114)*DCONJG(AMP(114))
      AMP2(115)=AMP2(115)+AMP(115)*DCONJG(AMP(115))
      AMP2(116)=AMP2(116)+AMP(116)*DCONJG(AMP(116))
      AMP2(117)=AMP2(117)+AMP(117)*DCONJG(AMP(117))
      AMP2(118)=AMP2(118)+AMP(118)*DCONJG(AMP(118))
      AMP2(119)=AMP2(119)+AMP(119)*DCONJG(AMP(119))
      AMP2(120)=AMP2(120)+AMP(120)*DCONJG(AMP(120))
      AMP2(121)=AMP2(121)+AMP(121)*DCONJG(AMP(121))
      AMP2(122)=AMP2(122)+AMP(122)*DCONJG(AMP(122))
      AMP2(123)=AMP2(123)+AMP(123)*DCONJG(AMP(123))
      AMP2(124)=AMP2(124)+AMP(124)*DCONJG(AMP(124))
      AMP2(125)=AMP2(125)+AMP(125)*DCONJG(AMP(125))
      AMP2(126)=AMP2(126)+AMP(126)*DCONJG(AMP(126))
      AMP2(127)=AMP2(127)+AMP(127)*DCONJG(AMP(127))
      AMP2(128)=AMP2(128)+AMP(128)*DCONJG(AMP(128))
      AMP2(129)=AMP2(129)+AMP(129)*DCONJG(AMP(129))
      AMP2(130)=AMP2(130)+AMP(130)*DCONJG(AMP(130))
      AMP2(131)=AMP2(131)+AMP(131)*DCONJG(AMP(131))
      AMP2(132)=AMP2(132)+AMP(132)*DCONJG(AMP(132))
      AMP2(133)=AMP2(133)+AMP(133)*DCONJG(AMP(133))
      AMP2(134)=AMP2(134)+AMP(134)*DCONJG(AMP(134))
      AMP2(135)=AMP2(135)+AMP(135)*DCONJG(AMP(135))
      AMP2(136)=AMP2(136)+AMP(136)*DCONJG(AMP(136))
      AMP2(137)=AMP2(137)+AMP(137)*DCONJG(AMP(137))
      AMP2(138)=AMP2(138)+AMP(138)*DCONJG(AMP(138))
      AMP2(139)=AMP2(139)+AMP(139)*DCONJG(AMP(139))
      AMP2(140)=AMP2(140)+AMP(140)*DCONJG(AMP(140))
      AMP2(141)=AMP2(141)+AMP(141)*DCONJG(AMP(141))
      AMP2(142)=AMP2(142)+AMP(142)*DCONJG(AMP(142))
      AMP2(143)=AMP2(143)+AMP(143)*DCONJG(AMP(143))
      AMP2(144)=AMP2(144)+AMP(144)*DCONJG(AMP(144))
      AMP2(145)=AMP2(145)+AMP(145)*DCONJG(AMP(145))
      AMP2(146)=AMP2(146)+AMP(146)*DCONJG(AMP(146))
      AMP2(147)=AMP2(147)+AMP(147)*DCONJG(AMP(147))
      AMP2(148)=AMP2(148)+AMP(148)*DCONJG(AMP(148))
      AMP2(149)=AMP2(149)+AMP(149)*DCONJG(AMP(149))
      AMP2(150)=AMP2(150)+AMP(150)*DCONJG(AMP(150))
      AMP2(151)=AMP2(151)+AMP(151)*DCONJG(AMP(151))
      AMP2(152)=AMP2(152)+AMP(152)*DCONJG(AMP(152))
      AMP2(153)=AMP2(153)+AMP(153)*DCONJG(AMP(153))
      AMP2(154)=AMP2(154)+AMP(154)*DCONJG(AMP(154))
      AMP2(155)=AMP2(155)+AMP(155)*DCONJG(AMP(155))
      AMP2(156)=AMP2(156)+AMP(156)*DCONJG(AMP(156))
      AMP2(157)=AMP2(157)+AMP(157)*DCONJG(AMP(157))
      AMP2(158)=AMP2(158)+AMP(158)*DCONJG(AMP(158))
      AMP2(159)=AMP2(159)+AMP(159)*DCONJG(AMP(159))
      AMP2(160)=AMP2(160)+AMP(160)*DCONJG(AMP(160))
      AMP2(161)=AMP2(161)+AMP(161)*DCONJG(AMP(161))
      AMP2(162)=AMP2(162)+AMP(162)*DCONJG(AMP(162))
      AMP2(163)=AMP2(163)+AMP(163)*DCONJG(AMP(163))
      AMP2(164)=AMP2(164)+AMP(164)*DCONJG(AMP(164))
      AMP2(165)=AMP2(165)+AMP(165)*DCONJG(AMP(165))
      AMP2(166)=AMP2(166)+AMP(166)*DCONJG(AMP(166))
      AMP2(167)=AMP2(167)+AMP(167)*DCONJG(AMP(167))
      AMP2(168)=AMP2(168)+AMP(168)*DCONJG(AMP(168))
      AMP2(169)=AMP2(169)+AMP(169)*DCONJG(AMP(169))
      AMP2(170)=AMP2(170)+AMP(170)*DCONJG(AMP(170))
      AMP2(171)=AMP2(171)+AMP(171)*DCONJG(AMP(171))
      AMP2(172)=AMP2(172)+AMP(172)*DCONJG(AMP(172))
      AMP2(173)=AMP2(173)+AMP(173)*DCONJG(AMP(173))
      AMP2(174)=AMP2(174)+AMP(174)*DCONJG(AMP(174))
      AMP2(175)=AMP2(175)+AMP(175)*DCONJG(AMP(175))
      AMP2(176)=AMP2(176)+AMP(176)*DCONJG(AMP(176))
      AMP2(177)=AMP2(177)+AMP(177)*DCONJG(AMP(177))
      AMP2(178)=AMP2(178)+AMP(178)*DCONJG(AMP(178))
      AMP2(179)=AMP2(179)+AMP(179)*DCONJG(AMP(179))
      AMP2(180)=AMP2(180)+AMP(180)*DCONJG(AMP(180))
      AMP2(181)=AMP2(181)+AMP(181)*DCONJG(AMP(181))
      AMP2(182)=AMP2(182)+AMP(182)*DCONJG(AMP(182))
      AMP2(183)=AMP2(183)+AMP(183)*DCONJG(AMP(183))
      AMP2(184)=AMP2(184)+AMP(184)*DCONJG(AMP(184))
      AMP2(185)=AMP2(185)+AMP(185)*DCONJG(AMP(185))
      AMP2(186)=AMP2(186)+AMP(186)*DCONJG(AMP(186))
      AMP2(187)=AMP2(187)+AMP(187)*DCONJG(AMP(187))
      AMP2(188)=AMP2(188)+AMP(188)*DCONJG(AMP(188))
      AMP2(189)=AMP2(189)+AMP(189)*DCONJG(AMP(189))
      AMP2(190)=AMP2(190)+AMP(190)*DCONJG(AMP(190))
      AMP2(191)=AMP2(191)+AMP(191)*DCONJG(AMP(191))
      AMP2(192)=AMP2(192)+AMP(192)*DCONJG(AMP(192))
      AMP2(193)=AMP2(193)+AMP(193)*DCONJG(AMP(193))
      AMP2(194)=AMP2(194)+AMP(194)*DCONJG(AMP(194))
      AMP2(195)=AMP2(195)+AMP(195)*DCONJG(AMP(195))
      AMP2(196)=AMP2(196)+AMP(196)*DCONJG(AMP(196))
      AMP2(197)=AMP2(197)+AMP(197)*DCONJG(AMP(197))
      AMP2(198)=AMP2(198)+AMP(198)*DCONJG(AMP(198))
      AMP2(199)=AMP2(199)+AMP(199)*DCONJG(AMP(199))
      AMP2(200)=AMP2(200)+AMP(200)*DCONJG(AMP(200))
      AMP2(201)=AMP2(201)+AMP(201)*DCONJG(AMP(201))
      AMP2(202)=AMP2(202)+AMP(202)*DCONJG(AMP(202))
      AMP2(203)=AMP2(203)+AMP(203)*DCONJG(AMP(203))
      DO I = 1, NCOLOR
        JAMP2(I)=JAMP2(I)+JAMP(I)*DCONJG(JAMP(I))
      ENDDO

      END

