C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE J_Z_BOSON_v(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      COMPLEX*16 TMP1
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 OM3
      COMPLEX*16 COUP
      OM3 = 0D0
c      IF (M3.NE.0D0) OM3=1D0/M3**2
      IF (M3.NE.0D0) OM3=1D0/(M3*(M3-CI*W3))
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP1 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3))))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 
     $ -CI* W3))
      V3(1)= DENOM*-CI*(F1(3)*F2(5)+F1(4)*F2(6)-P3(0)*OM3*TMP1)
      V3(2)= DENOM*-CI*(-F1(3)*F2(6)-F1(4)*F2(5)-P3(1)*OM3*TMP1)
      V3(3)= DENOM*-CI*(-CI*(F1(3)*F2(6))+CI*(F1(4)*F2(5))-P3(2)*OM3
     $ *TMP1)
      V3(4)= DENOM*-CI*(F1(4)*F2(6)-F1(3)*F2(5)-P3(3)*OM3*TMP1)
      V3(5) = F1(1)+F2(1)
      V3(6) = F1(2)+F2(2)

      END

C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1) + 2*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE J_Z_BOSON_2(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      COMPLEX*16 TMP1
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 OM3
      COMPLEX*16 TMP4
      COMPLEX*16 COUP
      OM3 = 0D0
c      IF (M3.NE.0D0) OM3=1D0/M3**2
      IF (M3.NE.0D0) OM3=1D0/(M3*(M3-CI*W3))
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP4 = (F1(5)*(F2(3)*(P3(0)-P3(3))-F2(4)*(P3(1)+CI*(P3(2))))
     $ +F1(6)*(F2(3)*(+CI*(P3(2))-P3(1))+F2(4)*(P3(0)+P3(3))))
      TMP1 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3))))
c      print*, TMP1, TMP4
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 
     $ -CI* W3))
      V3(1)= DENOM*-2D0 * CI*(OM3*-1D0/2D0 * P3(0)*(TMP1+2D0*(TMP4))+(
     $ +1D0/2D0*(F1(3)*F2(5)+F1(4)*F2(6))+F1(5)*F2(3)+F1(6)*F2(4)))
      V3(2)= DENOM*-2D0 * CI*(OM3*-1D0/2D0 * P3(1)*(TMP1+2D0*(TMP4))
     $ +(-1D0/2D0*(F1(3)*F2(6)+F1(4)*F2(5))+F1(5)*F2(4)+F1(6)*F2(3)))
      V3(3)= DENOM*2D0 * CI*(OM3*1D0/2D0 * P3(2)*(TMP1+2D0*(TMP4))+(
     $ +1D0/2D0 * CI*(F1(3)*F2(6))-1D0/2D0 * CI*(F1(4)*F2(5))
     $ -CI*(F1(5)*F2(4))+CI*(F1(6)*F2(3))))
      V3(4)= DENOM*2D0 * CI*(OM3*1D0/2D0 * P3(3)*(TMP1+2D0*(TMP4))+(
     $ +1D0/2D0*(F1(3)*F2(5))-1D0/2D0*(F1(4)*F2(6))-F1(5)*F2(3)
     $ +F1(6)*F2(4)))
      END

C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1) - 2*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE J_Z_BOSON_3(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 TMP2
      COMPLEX*16 V3(6)
      COMPLEX*16 TMP1
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 OM3
      COMPLEX*16 DENOM
      COMPLEX*16 COUP
      OM3 = 0D0
c      IF (M3.NE.0D0) OM3=1D0/M3**2
      IF (M3.NE.0D0) OM3=1D0/(M3*(M3-CI*W3))
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP1 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3))))
      TMP2 = (F1(5)*(F2(3)*(P3(0)-P3(3))-F2(4)*(P3(1)+CI*(P3(2))))
     $ +F1(6)*(F2(3)*(+CI*(P3(2))-P3(1))+F2(4)*(P3(0)+P3(3))))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 
     $ -CI* W3))
      V3(1)= DENOM*2D0 * CI*(OM3*1D0/2D0 * P3(0)*(TMP1-2D0*(TMP2))
     $ +(-1D0/2D0*(F1(3)*F2(5)+F1(4)*F2(6))+F1(5)*F2(3)+F1(6)*F2(4)))
      V3(2)= DENOM*2D0 * CI*(OM3*1D0/2D0 * P3(1)*(TMP1-2D0*(TMP2))+(
     $ +1D0/2D0*(F1(3)*F2(6)+F1(4)*F2(5))+F1(5)*F2(4)+F1(6)*F2(3)))
      V3(3)= DENOM*-2D0 * CI*(OM3*1D0/2D0 * P3(2)*(+2D0*(TMP2)-TMP1)
     $ +(-1D0/2D0 * CI*(F1(3)*F2(6))+1D0/2D0 * CI*(F1(4)*F2(5))
     $ -CI*(F1(5)*F2(4))+CI*(F1(6)*F2(3))))
      V3(4)= DENOM*-2D0 * CI*(OM3*1D0/2D0 * P3(3)*(+2D0*(TMP2)-TMP1)
     $ +(-1D0/2D0*(F1(3)*F2(5))+1D0/2D0*(F1(4)*F2(6))-F1(5)*F2(3)
     $ +F1(6)*F2(4)))
      END

C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1) + 4*Gamma(3,2,-1)*ProjP(-1,1)
C     
      SUBROUTINE J_Z_BOSON_4(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      COMPLEX*16 TMP1
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 OM3
      COMPLEX*16 TMP4
      COMPLEX*16 COUP
      OM3 = 0D0
c      IF (M3.NE.0D0) OM3=1D0/M3**2
      IF (M3.NE.0D0) OM3=1D0/(M3*(M3-CI*W3))
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      TMP4 = (F1(5)*(F2(3)*(P3(0)-P3(3))-F2(4)*(P3(1)+CI*(P3(2))))
     $ +F1(6)*(F2(3)*(+CI*(P3(2))-P3(1))+F2(4)*(P3(0)+P3(3))))
      TMP1 = (F1(3)*(F2(5)*(P3(0)+P3(3))+F2(6)*(P3(1)+CI*(P3(2))))
     $ +F1(4)*(F2(5)*(P3(1)-CI*(P3(2)))+F2(6)*(P3(0)-P3(3))))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 
     $ -CI* W3))
      V3(1)= DENOM*-4D0 * CI*(OM3*-1D0/4D0 * P3(0)*(TMP1+4D0*(TMP4))+(
     $ +1D0/4D0*(F1(3)*F2(5)+F1(4)*F2(6))+F1(5)*F2(3)+F1(6)*F2(4)))
      V3(2)= DENOM*-4D0 * CI*(OM3*-1D0/4D0 * P3(1)*(TMP1+4D0*(TMP4))
     $ +(-1D0/4D0*(F1(3)*F2(6)+F1(4)*F2(5))+F1(5)*F2(4)+F1(6)*F2(3)))
      V3(3)= DENOM*4D0 * CI*(OM3*1D0/4D0 * P3(2)*(TMP1+4D0*(TMP4))+(
     $ +1D0/4D0 * CI*(F1(3)*F2(6))-1D0/4D0 * CI*(F1(4)*F2(5))
     $ -CI*(F1(5)*F2(4))+CI*(F1(6)*F2(3))))
      V3(4)= DENOM*4D0 * CI*(OM3*1D0/4D0 * P3(3)*(TMP1+4D0*(TMP4))+(
     $ +1D0/4D0*(F1(3)*F2(5))-1D0/4D0*(F1(4)*F2(6))-F1(5)*F2(3)
     $ +F1(6)*F2(4)))
      END




C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE J_Z_BOSON_e(F1, F2, COUP1, COUP2, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      REAL*8 OM3
      INTEGER*4 I
      COMPLEX*16 VTMP(6)
      CALL J_Z_BOSON_v(F1,F2,COUP1,M3,W3,V3)
      CALL J_Z_BOSON_2(F1,F2,COUP2,M3,W3,VTMP)
      DO I = 1, 4
        V3(I) = -V3(I) - VTMP(I)
      ENDDO
      END

C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE J_Z_BOSON_d(F1, F2, COUP1, COUP2, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      REAL*8 OM3
      INTEGER*4 I
      COMPLEX*16 VTMP(6)
      CALL J_Z_BOSON_v(F1,F2,COUP1,M3,W3,V3)
      CALL J_Z_BOSON_3(F1,F2,COUP2,M3,W3,VTMP)
      DO I = 1, 4
        V3(I) = -V3(I) - VTMP(I)
      ENDDO
      END

C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE J_Z_BOSON_u(F1, F2, COUP1, COUP2, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 DENOM
      COMPLEX*16 V3(6)
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 COUP1
      COMPLEX*16 F2(*)
      COMPLEX*16 COUP2
      REAL*8 OM3
      INTEGER*4 I
      COMPLEX*16 VTMP(6)
      CALL J_Z_BOSON_v(F1,F2,COUP1,M3,W3,V3)
      CALL J_Z_BOSON_4(F1,F2,COUP2,M3,W3,VTMP)
      DO I = 1, 4
        V3(I) = -V3(I) - VTMP(I)
      ENDDO
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE J_A_BOSON(F1, F2, COUP, M3, W3,V3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 F2(*)
      COMPLEX*16 V3(6)
      REAL*8 W3
      REAL*8 P3(0:3)
      REAL*8 M3
      COMPLEX*16 F1(*)
      COMPLEX*16 DENOM
      COMPLEX*16 COUP
      V3(1) = +F1(1)+F2(1)
      V3(2) = +F1(2)+F2(2)
      P3(0) = -DBLE(V3(1))
      P3(1) = -DBLE(V3(2))
      P3(2) = -DIMAG(V3(2))
      P3(3) = -DIMAG(V3(1))
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 
     $ -CI* W3))
      V3(1)= DENOM*-CI*(F1(3)*F2(5)+F1(4)*F2(6)+F1(5)*F2(3)+F1(6)
     $ *F2(4))
      V3(2)= DENOM*-CI*(F1(5)*F2(4)+F1(6)*F2(3)-F1(3)*F2(6)-F1(4)
     $ *F2(5))
      V3(3)= DENOM*-CI*(-CI*(F1(3)*F2(6)+F1(6)*F2(3))+CI*(F1(4)*F2(5)
     $ +F1(5)*F2(4)))
      V3(4)= DENOM*-CI*(F1(4)*F2(6)+F1(5)*F2(3)-F1(3)*F2(5)-F1(6)
     $ *F2(4))
      V3(5) = +F1(1)+F2(1)
      V3(6) = +F1(2)+F2(2)
      END
