ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of loop_sm-no_b_mass'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'UV_GQQt = ', UV_GQQT
      WRITE(*,2) 'UV_tMass = ', UV_TMASS
      WRITE(*,2) 'UVWfct_t_0 = ', UVWFCT_T_0
      WRITE(*,2) 'UVWfct_G_2 = ', UVWFCT_G_2
      WRITE(*,2) 'R2_sxcW = ', R2_SXCW
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_5 = ', GC_5
      WRITE(*,2) 'R2_GQQ = ', R2_GQQ
      WRITE(*,2) 'R2_QQq = ', R2_QQQ
      WRITE(*,2) 'R2_QQt = ', R2_QQT
      WRITE(*,2) 'UV_GQQg_1eps = ', UV_GQQG_1EPS
      WRITE(*,2) 'UV_GQQq_1eps = ', UV_GQQQ_1EPS
      WRITE(*,2) 'UV_tMass_1eps = ', UV_TMASS_1EPS
      WRITE(*,2) 'UVWfct_t_0_1eps = ', UVWFCT_T_0_1EPS
      WRITE(*,2) 'UVWfct_G_2_1eps = ', UVWFCT_G_2_1EPS
      WRITE(*,2) 'GC_47 = ', GC_47
