ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=5)

      DOUBLE PRECISION MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA

      COMMON/MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA


      DOUBLE PRECISION MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      DOUBLE COMPLEX UV_GQQT, UV_TMASS, UVWFCT_T_0, UVWFCT_G_2,
     $  R2_SXCW, GC_4, GC_5, R2_GQQ, R2_QQQ, R2_QQT, UV_GQQG_1EPS,
     $  UV_GQQQ_1EPS, UV_TMASS_1EPS, UVWFCT_T_0_1EPS, UVWFCT_G_2_1EPS,
     $  GC_47

      COMMON/COUPLINGS/ UV_GQQT, UV_TMASS, UVWFCT_T_0, UVWFCT_G_2,
     $  R2_SXCW, GC_4, GC_5, R2_GQQ, R2_QQQ, R2_QQT, UV_GQQG_1EPS,
     $  UV_GQQQ_1EPS, UV_TMASS_1EPS, UVWFCT_T_0_1EPS, UVWFCT_G_2_1EPS,
     $  GC_47

