ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      REAL*16 G
      COMMON/MP_STRONG/ G

      COMPLEX*32 GAL(2)
      COMMON/MP_WEAK/ GAL

      COMPLEX*32 MU_R
      COMMON/MP_RSCALE/ MU_R


      REAL*16 MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA

      COMMON/MP_MASSES/ MDL_MH,MDL_MZ,MDL_MT,MDL_MW,MDL_MTA


      REAL*16 MDL_WZ,MDL_WH,MDL_WW,MDL_WT

      COMMON/MP_WIDTHS/ MDL_WZ,MDL_WH,MDL_WW,MDL_WT


      COMPLEX*32 UV_GQQT,UV_TMASS,UVWFCT_T_0,UVWFCT_G_2,R2_SXCW,GC_4
     $ ,GC_5,R2_GQQ,R2_QQQ,R2_QQT,UV_GQQG_1EPS,UV_GQQQ_1EPS
     $ ,UV_TMASS_1EPS,UVWFCT_T_0_1EPS,UVWFCT_G_2_1EPS,GC_47

      COMMON/MP_COUPLINGS/ UV_GQQT,UV_TMASS,UVWFCT_T_0,UVWFCT_G_2
     $ ,R2_SXCW,GC_4,GC_5,R2_GQQ,R2_QQQ,R2_QQT,UV_GQQG_1EPS
     $ ,UV_GQQQ_1EPS,UV_TMASS_1EPS,UVWFCT_T_0_1EPS,UVWFCT_G_2_1EPS
     $ ,GC_47


