ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL


      DOUBLE PRECISION MB,MH,MT,MW,MTA,MZ

      COMMON/MASSES/ MB,MH,MT,MW,MTA,MZ


      DOUBLE PRECISION WW,WT,WZ,WH

      COMMON/WIDTHS/ WW,WT,WZ,WH


      DOUBLE COMPLEX GC_10, GC_11, GC_1, GC_2, GC_3, GC_4, GC_50
     $ , GC_51, GC_53, GC_58, GC_59, GC_62, GC_72, GC_81, GC_83, GC_100

      COMMON/COUPLINGS/ GC_10, GC_11, GC_1, GC_2, GC_3, GC_4, GC_50
     $ , GC_51, GC_53, GC_58, GC_59, GC_62, GC_72, GC_81, GC_83, GC_100

