* du_LL_renconst.h
* RC declarations
* generated by FormCalc 6.1D0 6 Dec 2011 13:56

#include "user_sqsq.h"
	double complex dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy, dZGG1Light
	double complex dZGl1, dZgs1y, dZfL1(4,1,1), dZSq1(14,2,2,1,1)
	common /du_LL_renconst/ dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy
	common /du_LL_renconst/ dZGG1Light, dZGl1, dZgs1y, dZfL1
	common /du_LL_renconst/ dZSq1

