* LL_renconst.h
* RC declarations
* generated by FormCalc 6.1D0 24 Jun 2011 11:45

#include "user_sqsq.h"
	double complex dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy, dZGG1Light
	double complex dZGl1, dZgs1y, dZfL1(3,1,1), dZSq1(13,2,2,1,1)
	common /LL_renconst/ dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy
	common /LL_renconst/ dZGG1Light, dZGl1, dZgs1y, dZfL1, dZSq1
	
	save /LL_renconst/

