* LL_vars.h
* variable declarations
* generated by FormCalc 6.1 24 Jun 2011 11:45

#include "decl.h"
#include "LL_renconst.h"
	
	double precision S, T, U
	common /LL_kinvars/ S, T, U

	integer Hel(4)
	common /LL_kinvars/ Hel

	double complex F6, F3, F7, F8
	common /LL_abbrev/ F6, F3, F7, F8

	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30, iint31, iint32, iint33, iint34, iint35, iint36
	integer iint37, iint38, iint39, iint40, iint41, iint42, iint43
	integer iint44, iint45
	common /LL_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /LL_loopint/ iint7, iint8, iint9, iint10, iint11
	common /LL_loopint/ iint12, iint13, iint14, iint15, iint16
	common /LL_loopint/ iint17, iint18, iint19, iint20, iint21
	common /LL_loopint/ iint22, iint23, iint24, iint25, iint26
	common /LL_loopint/ iint27, iint28, iint29, iint30, iint31
	common /LL_loopint/ iint32, iint33, iint34, iint35, iint36
	common /LL_loopint/ iint37, iint38, iint39, iint40, iint41
	common /LL_loopint/ iint42, iint43, iint44, iint45

	double complex MatSUN(5,5), Ctree(5), Cloop(5)
	common /LL_formfactors/ MatSUN, Ctree, Cloop

	save /LL_kinvars/
	save /LL_loopint/
	save /LL_formfactors/
