* LR_vars.h
* variable declarations
* generated by FormCalc 6.1 24 Jun 2011 11:46

#include "decl.h"
#include "LR_renconst.h"
	
	double precision S, T, U
	common /LR_kinvars/ S, T, U

	integer Hel(4)
	common /LR_kinvars/ Hel
	
	double complex F10, F9, F8, F7, F3, F4
	common /LR_abbrev/ F10, F9, F8, F7, F3, F4

	
	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30, iint31, iint32, iint33, iint34, iint35, iint36
	integer iint37, iint38, iint39, iint40, iint41, iint42, iint43
	integer iint44, iint45, iint46, iint47, iint48, iint49, iint50
	integer iint51, iint52, iint53, iint54, iint55, iint56, iint57
	integer iint58
	common /LR_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /LR_loopint/ iint7, iint8, iint9, iint10, iint11
	common /LR_loopint/ iint12, iint13, iint14, iint15, iint16
	common /LR_loopint/ iint17, iint18, iint19, iint20, iint21
	common /LR_loopint/ iint22, iint23, iint24, iint25, iint26
	common /LR_loopint/ iint27, iint28, iint29, iint30, iint31
	common /LR_loopint/ iint32, iint33, iint34, iint35, iint36
	common /LR_loopint/ iint37, iint38, iint39, iint40, iint41
	common /LR_loopint/ iint42, iint43, iint44, iint45, iint46
	common /LR_loopint/ iint47, iint48, iint49, iint50, iint51
	common /LR_loopint/ iint52, iint53, iint54, iint55, iint56
	common /LR_loopint/ iint57, iint58

	double complex MatSUN(6,6), Ctree(6), Cloop(6)
	common /LR_formfactors/ MatSUN, Ctree, Cloop
	
	save /LR_kinvars/
	save /LR_loopint/
	save /LR_formfactors/
