* ud_LR_renconst.h
* RC declarations
* generated by FormCalc 6.1D0 24 Jun 2011 11:49

#include "user_sqsq.h"
	double complex dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy, dZGG1Light
	double complex dZGl1, dZgs1y, dZfL1(3,1,1), dZfR1(4,1,1)
	double complex dZSq1(14,2,2,1,1)
	common /ud_LR_renconst/ dMGl1, dMGl1Im, dMGl1Re, dZGG1Heavy
	common /ud_LR_renconst/ dZGG1Light, dZGl1, dZgs1y, dZfL1
	common /ud_LR_renconst/ dZfR1, dZSq1
	
	save /ud_LR_renconst/

