      SUBROUTINE SDDCS(PBAR,fsign,h,ANS)
C  
C Generated by MadGraph II Version 3.0. Updated 02/19/04                
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : d c -> d s e+ ve mu+ mu-  
C  
C Crossing   1 is d c -> d s e+ ve mu+ mu-  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      Include "genps.inc"
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB= 256, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 PBAR(0:3,NEXTERNAL),ANS(NCROSS)
      integer fsign(8),h
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T
      REAL*8 DDCS
      INTEGER IHEL,IDEN(NCROSS)
      INTEGER IPROC,I
      LOGICAL GOODHEL(NCOMB,NCROSS)
      INTEGER NGRAPHS
      REAL*8 hwgt, xtot, xtry, xrej, xr, yfrac(0:ncomb)
      INTEGER idum, ngood, igood(ncomb), jhel, j
      LOGICAL warned
      REAL     xran1
      EXTERNAL xran1
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_ampsw1/  amp2,       jamp2

      character*79         hel_buff
      common/to_helicityw1/  hel_buff

      integer          isum_hel
      logical                    multi_channel
      common/to_matrixw1/isum_hel, multi_channel
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      common/to_mconfigsw1/mapconfig, iconfig
      DATA NTRY,IDUM /0,-1/
      DATA xtry, xrej, ngood /0,0,0/
      DATA warned, isum_hel/.false.,0/
      DATA multi_channel/.false./
      SAVE yfrac, igood, IDUM, jhel
      DATA NGRAPHS /  210/          
      DATA jamp2(0) /   1/          
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1,8) /-1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1,8) /-1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   3),IHEL=1,8) /-1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   4),IHEL=1,8) /-1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   5),IHEL=1,8) /-1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,   6),IHEL=1,8) /-1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1,8) /-1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1,8) /-1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,   9),IHEL=1,8) /-1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  10),IHEL=1,8) /-1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  11),IHEL=1,8) /-1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  12),IHEL=1,8) /-1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1,8) /-1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1,8) /-1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  15),IHEL=1,8) /-1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  16),IHEL=1,8) /-1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  17),IHEL=1,8) /-1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  18),IHEL=1,8) /-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1,8) /-1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1,8) /-1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  21),IHEL=1,8) /-1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  22),IHEL=1,8) /-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  23),IHEL=1,8) /-1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  24),IHEL=1,8) /-1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1,8) /-1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1,8) /-1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  27),IHEL=1,8) /-1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  28),IHEL=1,8) /-1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  29),IHEL=1,8) /-1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  30),IHEL=1,8) /-1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1,8) /-1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1,8) /-1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  33),IHEL=1,8) /-1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  34),IHEL=1,8) /-1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  35),IHEL=1,8) /-1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  36),IHEL=1,8) /-1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1,8) /-1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1,8) /-1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  39),IHEL=1,8) /-1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  40),IHEL=1,8) /-1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  41),IHEL=1,8) /-1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  42),IHEL=1,8) /-1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1,8) /-1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1,8) /-1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  45),IHEL=1,8) /-1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  46),IHEL=1,8) /-1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  47),IHEL=1,8) /-1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  48),IHEL=1,8) /-1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1,8) /-1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1,8) /-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  51),IHEL=1,8) /-1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  52),IHEL=1,8) /-1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  53),IHEL=1,8) /-1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  54),IHEL=1,8) /-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1,8) /-1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1,8) /-1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  57),IHEL=1,8) /-1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  58),IHEL=1,8) /-1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  59),IHEL=1,8) /-1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  60),IHEL=1,8) /-1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1,8) /-1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1,8) /-1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  63),IHEL=1,8) /-1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  64),IHEL=1,8) /-1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  65),IHEL=1,8) /-1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  66),IHEL=1,8) /-1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  67),IHEL=1,8) /-1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  68),IHEL=1,8) /-1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  69),IHEL=1,8) /-1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  70),IHEL=1,8) /-1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  71),IHEL=1,8) /-1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  72),IHEL=1,8) /-1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  73),IHEL=1,8) /-1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  74),IHEL=1,8) /-1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  75),IHEL=1,8) /-1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  76),IHEL=1,8) /-1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  77),IHEL=1,8) /-1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  78),IHEL=1,8) /-1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  79),IHEL=1,8) /-1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  80),IHEL=1,8) /-1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  81),IHEL=1,8) /-1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  82),IHEL=1,8) /-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  83),IHEL=1,8) /-1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  84),IHEL=1,8) /-1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  85),IHEL=1,8) /-1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  86),IHEL=1,8) /-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  87),IHEL=1,8) /-1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  88),IHEL=1,8) /-1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  89),IHEL=1,8) /-1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  90),IHEL=1,8) /-1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  91),IHEL=1,8) /-1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  92),IHEL=1,8) /-1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  93),IHEL=1,8) /-1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  94),IHEL=1,8) /-1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  95),IHEL=1,8) /-1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  96),IHEL=1,8) /-1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  97),IHEL=1,8) /-1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  98),IHEL=1,8) /-1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  99),IHEL=1,8) /-1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 100),IHEL=1,8) /-1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 101),IHEL=1,8) /-1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 102),IHEL=1,8) /-1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 103),IHEL=1,8) /-1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 104),IHEL=1,8) /-1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 105),IHEL=1,8) /-1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 106),IHEL=1,8) /-1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 107),IHEL=1,8) /-1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 108),IHEL=1,8) /-1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 109),IHEL=1,8) /-1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 110),IHEL=1,8) /-1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 111),IHEL=1,8) /-1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 112),IHEL=1,8) /-1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 113),IHEL=1,8) /-1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 114),IHEL=1,8) /-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 115),IHEL=1,8) /-1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 116),IHEL=1,8) /-1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 117),IHEL=1,8) /-1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 118),IHEL=1,8) /-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 119),IHEL=1,8) /-1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 120),IHEL=1,8) /-1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 121),IHEL=1,8) /-1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 122),IHEL=1,8) /-1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 123),IHEL=1,8) /-1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 124),IHEL=1,8) /-1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 125),IHEL=1,8) /-1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 126),IHEL=1,8) /-1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 127),IHEL=1,8) /-1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 128),IHEL=1,8) /-1, 1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 129),IHEL=1,8) / 1,-1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 130),IHEL=1,8) / 1,-1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 131),IHEL=1,8) / 1,-1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 132),IHEL=1,8) / 1,-1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 133),IHEL=1,8) / 1,-1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 134),IHEL=1,8) / 1,-1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 135),IHEL=1,8) / 1,-1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 136),IHEL=1,8) / 1,-1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 137),IHEL=1,8) / 1,-1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 138),IHEL=1,8) / 1,-1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 139),IHEL=1,8) / 1,-1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 140),IHEL=1,8) / 1,-1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 141),IHEL=1,8) / 1,-1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 142),IHEL=1,8) / 1,-1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 143),IHEL=1,8) / 1,-1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 144),IHEL=1,8) / 1,-1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 145),IHEL=1,8) / 1,-1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 146),IHEL=1,8) / 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 147),IHEL=1,8) / 1,-1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 148),IHEL=1,8) / 1,-1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 149),IHEL=1,8) / 1,-1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 150),IHEL=1,8) / 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 151),IHEL=1,8) / 1,-1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 152),IHEL=1,8) / 1,-1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 153),IHEL=1,8) / 1,-1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 154),IHEL=1,8) / 1,-1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 155),IHEL=1,8) / 1,-1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 156),IHEL=1,8) / 1,-1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 157),IHEL=1,8) / 1,-1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 158),IHEL=1,8) / 1,-1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 159),IHEL=1,8) / 1,-1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 160),IHEL=1,8) / 1,-1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 161),IHEL=1,8) / 1,-1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 162),IHEL=1,8) / 1,-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 163),IHEL=1,8) / 1,-1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 164),IHEL=1,8) / 1,-1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 165),IHEL=1,8) / 1,-1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 166),IHEL=1,8) / 1,-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 167),IHEL=1,8) / 1,-1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 168),IHEL=1,8) / 1,-1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 169),IHEL=1,8) / 1,-1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 170),IHEL=1,8) / 1,-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 171),IHEL=1,8) / 1,-1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 172),IHEL=1,8) / 1,-1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 173),IHEL=1,8) / 1,-1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 174),IHEL=1,8) / 1,-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 175),IHEL=1,8) / 1,-1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 176),IHEL=1,8) / 1,-1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 177),IHEL=1,8) / 1,-1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 178),IHEL=1,8) / 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 179),IHEL=1,8) / 1,-1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 180),IHEL=1,8) / 1,-1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 181),IHEL=1,8) / 1,-1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 182),IHEL=1,8) / 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 183),IHEL=1,8) / 1,-1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 184),IHEL=1,8) / 1,-1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 185),IHEL=1,8) / 1,-1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 186),IHEL=1,8) / 1,-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 187),IHEL=1,8) / 1,-1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 188),IHEL=1,8) / 1,-1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 189),IHEL=1,8) / 1,-1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 190),IHEL=1,8) / 1,-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 191),IHEL=1,8) / 1,-1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 192),IHEL=1,8) / 1,-1, 1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 193),IHEL=1,8) / 1, 1,-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 194),IHEL=1,8) / 1, 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 195),IHEL=1,8) / 1, 1,-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 196),IHEL=1,8) / 1, 1,-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 197),IHEL=1,8) / 1, 1,-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 198),IHEL=1,8) / 1, 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 199),IHEL=1,8) / 1, 1,-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 200),IHEL=1,8) / 1, 1,-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 201),IHEL=1,8) / 1, 1,-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 202),IHEL=1,8) / 1, 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 203),IHEL=1,8) / 1, 1,-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 204),IHEL=1,8) / 1, 1,-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 205),IHEL=1,8) / 1, 1,-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 206),IHEL=1,8) / 1, 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 207),IHEL=1,8) / 1, 1,-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 208),IHEL=1,8) / 1, 1,-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 209),IHEL=1,8) / 1, 1,-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 210),IHEL=1,8) / 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 211),IHEL=1,8) / 1, 1,-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 212),IHEL=1,8) / 1, 1,-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 213),IHEL=1,8) / 1, 1,-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 214),IHEL=1,8) / 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 215),IHEL=1,8) / 1, 1,-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 216),IHEL=1,8) / 1, 1,-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 217),IHEL=1,8) / 1, 1,-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 218),IHEL=1,8) / 1, 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 219),IHEL=1,8) / 1, 1,-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 220),IHEL=1,8) / 1, 1,-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 221),IHEL=1,8) / 1, 1,-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 222),IHEL=1,8) / 1, 1,-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 223),IHEL=1,8) / 1, 1,-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 224),IHEL=1,8) / 1, 1,-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 225),IHEL=1,8) / 1, 1, 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 226),IHEL=1,8) / 1, 1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 227),IHEL=1,8) / 1, 1, 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 228),IHEL=1,8) / 1, 1, 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 229),IHEL=1,8) / 1, 1, 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 230),IHEL=1,8) / 1, 1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 231),IHEL=1,8) / 1, 1, 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 232),IHEL=1,8) / 1, 1, 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 233),IHEL=1,8) / 1, 1, 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 234),IHEL=1,8) / 1, 1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 235),IHEL=1,8) / 1, 1, 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 236),IHEL=1,8) / 1, 1, 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 237),IHEL=1,8) / 1, 1, 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 238),IHEL=1,8) / 1, 1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 239),IHEL=1,8) / 1, 1, 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 240),IHEL=1,8) / 1, 1, 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 241),IHEL=1,8) / 1, 1, 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 242),IHEL=1,8) / 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 243),IHEL=1,8) / 1, 1, 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 244),IHEL=1,8) / 1, 1, 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 245),IHEL=1,8) / 1, 1, 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 246),IHEL=1,8) / 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 247),IHEL=1,8) / 1, 1, 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 248),IHEL=1,8) / 1, 1, 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 249),IHEL=1,8) / 1, 1, 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 250),IHEL=1,8) / 1, 1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 251),IHEL=1,8) / 1, 1, 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 252),IHEL=1,8) / 1, 1, 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 253),IHEL=1,8) / 1, 1, 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 254),IHEL=1,8) / 1, 1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 255),IHEL=1,8) / 1, 1, 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 256),IHEL=1,8) / 1, 1, 1, 1, 1, 1, 1, 1/
c      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  1/ ! remove color/spin averaging factors
C ----------
C BEGIN CODE
C ----------
      iproc =1
      NTRY=NTRY+1
      ANS(IPROC) = 0D0
      write(hel_buff,'(16i5)') (0,i=1,nexternal)
      IF (ISUM_HEL .EQ. 0 .OR. NTRY .LT. 10) THEN
          DO IHEL=1,NCOMB
              IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
                 T=DDCS(PBAR ,NHEL(1,IHEL),FSIGN(1))            
              
                  IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL,IPROC)) THEN
                      GOODHEL(IHEL,IPROC)=.TRUE.
                      NGOOD = NGOOD +1
                      IGOOD(NGOOD) = IHEL
C                     WRITE(*,*) ngood,IHEL,T
                  ENDIF

                  if (nhel(7,ihel).eq.-1.and.nhel(8,ihel).eq.-1) then 
                     h = 1
                  elseif (nhel(7,ihel).eq.+1.and.nhel(8,ihel).eq.+1) then 
                     h = 2
                  endif

	      if((h.eq.1.and.nhel(5,ihel).eq.-1.and.nhel(6,ihel).eq.-1
     #	                .and.nhel(7,ihel).eq.-1.and.nhel(8,ihel).eq.-1).or.
     #	         (h.eq.2.and.nhel(5,ihel).eq.-1.and.nhel(6,ihel).eq.-1
     #	                .and.nhel(7,ihel).eq.+1.and.nhel(8,ihel).eq.+1)) then
	      
	      
	         ANS(IPROC)=ANS(IPROC)+T
             
	      else

	         ANS(IPROC)=ANS(IPROC)
		 
	      endif	 	 		  
	      
		  
              ENDIF  !goodhel
          ENDDO !ihel
	  
          JHEL = 1
          ISUM_HEL=MIN(ISUM_HEL,NGOOD)
      ELSE              !RANDOM HELICITY
          DO J=1,ISUM_HEL
              JHEL=JHEL+1
              IF (JHEL .GT. NGOOD) JHEL=1
              HWGT = REAL(NGOOD)/REAL(ISUM_HEL)
              IHEL = IGOOD(JHEL)
              T=DDCS(PBAR ,NHEL(1,IHEL),FSIGN(1))            
           ANS(IPROC)=ANS(IPROC)+T*HWGT
          ENDDO
          IF (ISUM_HEL .EQ. 1) THEN
              WRITE(HEL_BUFF,'(16i5)')(NHEL(i,IHEL),i=1,nexternal)
          ENDIF
      ENDIF
      IF (MULTI_CHANNEL) THEN
          XTOT=0D0
          DO IHEL=1,MAPCONFIG(0)
              XTOT=XTOT+AMP2(MAPCONFIG(IHEL))
          ENDDO
          ANS(IPROC)=ANS(IPROC)*AMP2(MAPCONFIG(ICONFIG))/XTOT
      ENDIF
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))

      END
       
 
c --------------------------------------------------------------- 
 
       
      REAL*8 FUNCTION DDCS(P,NHEL,FSIGN)
C  
C Generated by MadGraph II Version 3.0. Updated 02/19/04                
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : d c -> d s e+ ve mu+ mu-  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS= 210,NEIGEN=  1) 
      include "genps.inc"
      include 'tensorw.inc'
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS= 168, NCOLOR=   1) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), FSIGN(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS),WX1(6),WX2(6)
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_ampsw1/  amp2,       jamp2
      include "coupl.inc"
     
      integer h
c      common /hcount/ h
C  
C COLOR DATA
C  
      DATA Denom(1  )/            1/                                       
      DATA (CF(i,1  ),i=1  ,1  ) /     9/                                  
C               T[3,1]T[4,2]                                               
C ----------
C BEGIN CODE
C ----------
c      CALL IXXXXX(P(0,1   ),ZERO ,NHEL(1   ),+1*IC(1   ),W(1,1   ))        
c      CALL IXXXXX(P(0,2   ),ZERO ,NHEL(2   ),+1*IC(2   ),W(1,2   ))        
c      CALL OXXXXX(P(0,3   ),ZERO ,NHEL(3   ),+1*IC(3   ),W(1,3   ))        
c      CALL OXXXXX(P(0,4   ),ZERO ,NHEL(4   ),+1*IC(4   ),W(1,4   ))        
c      CALL IXXXXX(P(0,5   ),ZERO ,NHEL(5   ),-1*IC(5   ),W(1,5   ))        
c      CALL OXXXXX(P(0,6   ),ZERO ,NHEL(6   ),+1*IC(6   ),W(1,6   ))        
c      CALL IXXXXX(P(0,7   ),ZERO ,NHEL(7   ),-1*IC(7   ),W(1,7   ))        
c      CALL OXXXXX(P(0,8   ),ZERO ,NHEL(8   ),+1*IC(8   ),W(1,8   ))        

      CALL IXXXXX(P(0,1   ),ZERO ,NHEL(1)*FSIGN(1),FSIGN(1),W(1,1   ))        
      CALL IXXXXX(P(0,3   ),ZERO ,NHEL(3)*FSIGN(3),FSIGN(3),W(1,2   ))        
      CALL OXXXXX(P(0,2   ),ZERO ,NHEL(2)*FSIGN(2),FSIGN(2),W(1,3   ))        
      CALL OXXXXX(P(0,4   ),ZERO ,NHEL(4)*FSIGN(4),FSIGN(4),W(1,4   ))        
      CALL IXXXXX(P(0,5   ),ZERO ,NHEL(5)*FSIGN(5),FSIGN(5),W(1,5   ))        
      CALL OXXXXX(P(0,6   ),ZERO ,NHEL(6)*FSIGN(6),FSIGN(6),W(1,6   ))        
      CALL IXXXXX(P(0,7   ),ZERO ,NHEL(7)*FSIGN(7),FSIGN(7),W(1,7   ))        
      CALL OXXXXX(P(0,8   ),ZERO ,NHEL(8)*FSIGN(8),FSIGN(8),W(1,8   ))        

      CALL JIOXXX(W(1,5   ),W(1,6   ),GWF ,WMASS   ,WWIDTH  ,W(1,9   ))    
      CALL JIOXXX(W(1,7   ),W(1,8   ),GAL ,ZERO    ,ZERO    ,W(1,10  ))    
      CALL FVIXXX(W(1,2   ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,11  ))    
      CALL FVIXXX(W(1,1   ),W(1,10  ),GAD ,ZERO    ,ZERO    ,W(1,12  ))    
      CALL JIOXXX(W(1,12  ),W(1,3   ),GAD ,ZERO    ,ZERO    ,W(1,13  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,13  ),GAD ,AMP(1   ))            
      CALL JIOXXX(W(1,12  ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,14  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,14  ),GZD ,AMP(2   ))            
      CALL JIOXXX(W(1,7   ),W(1,8   ),GZL ,ZMASS   ,ZWIDTH  ,W(1,15  ))    
      CALL FVIXXX(W(1,1   ),W(1,15  ),GZD ,ZERO    ,ZERO    ,W(1,16  ))    
      CALL JIOXXX(W(1,16  ),W(1,3   ),GAD ,ZERO    ,ZERO    ,W(1,17  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,17  ),GAD ,AMP(3   ))            
      CALL JIOXXX(W(1,16  ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,18  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,18  ),GZD ,AMP(4   ))            
      CALL JIOXXX(W(1,1   ),W(1,3   ),GAD ,ZERO    ,ZERO    ,W(1,19  ))    
      CALL FVOXXX(W(1,4   ),W(1,19  ),GAD ,ZERO    ,ZERO    ,W(1,20  ))    
      CALL FVOXXX(W(1,20  ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,21  ))    
      CALL IOVXXX(W(1,2   ),W(1,21  ),W(1,10  ),GAU ,AMP(5   ))            
      CALL IOVXXX(W(1,2   ),W(1,21  ),W(1,15  ),GZU ,AMP(6   ))            
      CALL JIOXXX(W(1,1   ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,22  ))    
      CALL FVOXXX(W(1,4   ),W(1,22  ),GZD ,ZERO    ,ZERO    ,W(1,23  ))    
      CALL FVOXXX(W(1,23  ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,24  ))    
      CALL IOVXXX(W(1,2   ),W(1,24  ),W(1,10  ),GAU ,AMP(7   ))            
      CALL IOVXXX(W(1,2   ),W(1,24  ),W(1,15  ),GZU ,AMP(8   ))            
      CALL FVOXXX(W(1,3   ),W(1,10  ),GAD ,ZERO    ,ZERO    ,W(1,25  ))    
      CALL JIOXXX(W(1,1   ),W(1,25  ),GAD ,ZERO    ,ZERO    ,W(1,26  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,26  ),GAD ,AMP(9   ))            
      CALL JIOXXX(W(1,1   ),W(1,25  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,27  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,27  ),GZD ,AMP(10  ))            
      CALL FVOXXX(W(1,3   ),W(1,15  ),GZD ,ZERO    ,ZERO    ,W(1,28  ))    
      CALL JIOXXX(W(1,1   ),W(1,28  ),GAD ,ZERO    ,ZERO    ,W(1,29  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,29  ),GAD ,AMP(11  ))            
      CALL JIOXXX(W(1,1   ),W(1,28  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,30  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,30  ),GZD ,AMP(12  ))            
      CALL FVOXXX(W(1,4   ),W(1,10  ),GAD ,ZERO    ,ZERO    ,W(1,31  ))    
      CALL IOVXXX(W(1,11  ),W(1,31  ),W(1,19  ),GAD ,AMP(13  ))            
      CALL FVOXXX(W(1,4   ),W(1,15  ),GZD ,ZERO    ,ZERO    ,W(1,32  ))    
      CALL IOVXXX(W(1,11  ),W(1,32  ),W(1,19  ),GAD ,AMP(14  ))            
      CALL IOVXXX(W(1,11  ),W(1,31  ),W(1,22  ),GZD ,AMP(15  ))            
      CALL IOVXXX(W(1,11  ),W(1,32  ),W(1,22  ),GZD ,AMP(16  ))            
      CALL JIOXXX(W(1,2   ),W(1,20  ),GWF ,WMASS   ,WWIDTH  ,W(1,33  ))    
      CALL FVOXXX(W(1,6   ),W(1,33  ),GWF ,ZERO    ,ZERO    ,W(1,34  ))    
      CALL JIOXXX(W(1,5   ),W(1,34  ),GAL ,ZERO    ,ZERO    ,W(1,35  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,35  ),GAL ,AMP(17  ))            
      CALL JIOXXX(W(1,5   ),W(1,34  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,36  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,36  ),GZL ,AMP(18  ))            
      CALL JIOXXX(W(1,2   ),W(1,23  ),GWF ,WMASS   ,WWIDTH  ,W(1,37  ))    
      CALL FVOXXX(W(1,6   ),W(1,37  ),GWF ,ZERO    ,ZERO    ,W(1,38  ))    
      CALL JIOXXX(W(1,5   ),W(1,38  ),GAL ,ZERO    ,ZERO    ,W(1,39  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,39  ),GAL ,AMP(19  ))            
      CALL JIOXXX(W(1,5   ),W(1,38  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,40  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,40  ),GZL ,AMP(20  ))            
      CALL FVIXXX(W(1,5   ),W(1,33  ),GWF ,ZERO    ,ZERO    ,W(1,41  ))    
      CALL JIOXXX(W(1,41  ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,42  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,42  ),GZL ,AMP(21  ))            
      CALL FVIXXX(W(1,5   ),W(1,37  ),GWF ,ZERO    ,ZERO    ,W(1,43  ))    
      CALL JIOXXX(W(1,43  ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,44  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,44  ),GZL ,AMP(22  ))            
      CALL FVIXXX(W(1,7   ),W(1,19  ),GAL ,ZERO    ,ZERO    ,W(1,45  ))    
      CALL JIOXXX(W(1,45  ),W(1,8   ),GAL ,ZERO    ,ZERO    ,W(1,46  ))    
      CALL FVOXXX(W(1,4   ),W(1,46  ),GAD ,ZERO    ,ZERO    ,W(1,47  ))    
      CALL IOVXXX(W(1,2   ),W(1,47  ),W(1,9   ),GWF ,AMP(23  ))            
      CALL JIOXXX(W(1,45  ),W(1,8   ),GZL ,ZMASS   ,ZWIDTH  ,W(1,48  ))    
      CALL FVOXXX(W(1,4   ),W(1,48  ),GZD ,ZERO    ,ZERO    ,W(1,49  ))    
      CALL IOVXXX(W(1,2   ),W(1,49  ),W(1,9   ),GWF ,AMP(24  ))            
      CALL FVIXXX(W(1,7   ),W(1,22  ),GZL ,ZERO    ,ZERO    ,W(1,50  ))    
      CALL JIOXXX(W(1,50  ),W(1,8   ),GAL ,ZERO    ,ZERO    ,W(1,51  ))    
      CALL FVOXXX(W(1,4   ),W(1,51  ),GAD ,ZERO    ,ZERO    ,W(1,52  ))    
      CALL IOVXXX(W(1,2   ),W(1,52  ),W(1,9   ),GWF ,AMP(25  ))            
      CALL JIOXXX(W(1,50  ),W(1,8   ),GZL ,ZMASS   ,ZWIDTH  ,W(1,53  ))    
      CALL FVOXXX(W(1,4   ),W(1,53  ),GZD ,ZERO    ,ZERO    ,W(1,54  ))    
      CALL IOVXXX(W(1,2   ),W(1,54  ),W(1,9   ),GWF ,AMP(26  ))            
      CALL FVOXXX(W(1,8   ),W(1,19  ),GAL ,ZERO    ,ZERO    ,W(1,55  ))    
      CALL JIOXXX(W(1,7   ),W(1,55  ),GAL ,ZERO    ,ZERO    ,W(1,56  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,56  ),GAD ,AMP(27  ))            
      CALL JIOXXX(W(1,7   ),W(1,55  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,57  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,57  ),GZD ,AMP(28  ))            
      CALL FVOXXX(W(1,8   ),W(1,22  ),GZL ,ZERO    ,ZERO    ,W(1,58  ))    
      CALL JIOXXX(W(1,7   ),W(1,58  ),GAL ,ZERO    ,ZERO    ,W(1,59  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,59  ),GAD ,AMP(29  ))            
      CALL JIOXXX(W(1,7   ),W(1,58  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,60  ))    
      CALL IOVXXX(W(1,11  ),W(1,4   ),W(1,60  ),GZD ,AMP(30  ))            
      CALL IOVXXX(W(1,11  ),W(1,20  ),W(1,10  ),GAD ,AMP(31  ))            
      CALL IOVXXX(W(1,11  ),W(1,20  ),W(1,15  ),GZD ,AMP(32  ))            
      CALL IOVXXX(W(1,11  ),W(1,23  ),W(1,10  ),GAD ,AMP(33  ))            
      CALL IOVXXX(W(1,11  ),W(1,23  ),W(1,15  ),GZD ,AMP(34  ))            
      CALL JVVXXX(W(1,33  ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     61  ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,61  ),GAL ,AMP(35  ))            
      CALL JVVXXX(W(1,33  ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     62  ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,62  ),GZL ,AMP(36  ))            
      CALL JVVXXX(W(1,37  ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     63  ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,63  ),GAL ,AMP(37  ))            
      CALL JVVXXX(W(1,37  ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     64  ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,64  ),GZL ,AMP(38  ))            
      CALL FVIXXX(W(1,7   ),W(1,33  ),GWF ,ZERO    ,ZERO    ,W(1,65  ))    
      CALL IOVXXX(W(1,65  ),W(1,8   ),W(1,9   ),GWF ,AMP(39  ))            
      CALL FVIXXX(W(1,7   ),W(1,37  ),GWF ,ZERO    ,ZERO    ,W(1,66  ))    
      CALL IOVXXX(W(1,66  ),W(1,8   ),W(1,9   ),GWF ,AMP(40  ))            
      CALL JIOXXX(W(1,2   ),W(1,4   ),GWF ,WMASS   ,WWIDTH  ,W(1,67  ))    
      CALL FVOXXX(W(1,3   ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,68  ))    
      CALL IOVXXX(W(1,12  ),W(1,68  ),W(1,67  ),GWF ,AMP(41  ))            
      CALL IOVXXX(W(1,16  ),W(1,68  ),W(1,67  ),GWF ,AMP(42  ))            
      CALL FVIXXX(W(1,2   ),W(1,10  ),GAU ,ZERO    ,ZERO    ,W(1,69  ))    
      CALL JIOXXX(W(1,1   ),W(1,68  ),GWF ,WMASS   ,WWIDTH  ,W(1,70  ))    
      CALL IOVXXX(W(1,69  ),W(1,4   ),W(1,70  ),GWF ,AMP(43  ))            
      CALL FVIXXX(W(1,2   ),W(1,15  ),GZU ,ZERO    ,ZERO    ,W(1,71  ))    
      CALL IOVXXX(W(1,71  ),W(1,4   ),W(1,70  ),GWF ,AMP(44  ))            
      CALL FVIXXX(W(1,1   ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,72  ))    
      CALL FVIXXX(W(1,72  ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,73  ))    
      CALL IOVXXX(W(1,73  ),W(1,3   ),W(1,10  ),GAD ,AMP(45  ))            
      CALL IOVXXX(W(1,73  ),W(1,3   ),W(1,15  ),GZD ,AMP(46  ))            
      CALL IOVXXX(W(1,2   ),W(1,31  ),W(1,70  ),GWF ,AMP(47  ))            
      CALL IOVXXX(W(1,2   ),W(1,32  ),W(1,70  ),GWF ,AMP(48  ))            
      CALL JIOXXX(W(1,72  ),W(1,3   ),GWF ,WMASS   ,WWIDTH  ,W(1,74  ))    
      CALL FVOXXX(W(1,6   ),W(1,74  ),GWF ,ZERO    ,ZERO    ,W(1,75  ))    
      CALL IOVXXX(W(1,5   ),W(1,75  ),W(1,10  ),GAL ,AMP(49  ))            
      CALL IOVXXX(W(1,5   ),W(1,75  ),W(1,15  ),GZL ,AMP(50  ))            
      CALL FVIXXX(W(1,5   ),W(1,74  ),GWF ,ZERO    ,ZERO    ,W(1,76  ))    
      CALL IOVXXX(W(1,76  ),W(1,6   ),W(1,15  ),GZN ,AMP(51  ))            
      CALL JVVXXX(W(1,10  ),W(1,67  ),GWWA ,WMASS   ,WWIDTH  ,W(1,         
     &     77  ))                                                          
      CALL IOVXXX(W(1,1   ),W(1,68  ),W(1,77  ),GWF ,AMP(52  ))            
      CALL JVVXXX(W(1,15  ),W(1,67  ),GWWZ ,WMASS   ,WWIDTH  ,W(1,         
     &     78  ))                                                          
      CALL IOVXXX(W(1,1   ),W(1,68  ),W(1,78  ),GWF ,AMP(53  ))            
      CALL FVIXXX(W(1,7   ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,79  ))    
      CALL JIOXXX(W(1,79  ),W(1,8   ),GWF ,WMASS   ,WWIDTH  ,W(1,80  ))    
      CALL FVIXXX(W(1,1   ),W(1,80  ),GWF ,ZERO    ,ZERO    ,W(1,81  ))    
      CALL IOVXXX(W(1,81  ),W(1,3   ),W(1,9   ),GWF ,AMP(54  ))            
      CALL IOVXXX(W(1,72  ),W(1,68  ),W(1,10  ),GAU ,AMP(55  ))            
      CALL IOVXXX(W(1,72  ),W(1,68  ),W(1,15  ),GZU ,AMP(56  ))            
      CALL VVVXXX(W(1,74  ),W(1,9   ),W(1,10  ),GWWA ,AMP(57  ))           
      CALL VVVXXX(W(1,74  ),W(1,9   ),W(1,15  ),GWWZ ,AMP(58  ))           
      CALL FVOXXX(W(1,8   ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,82  ))    
      CALL IOVXXX(W(1,7   ),W(1,82  ),W(1,74  ),GWF ,AMP(59  ))            
      CALL FVOXXX(W(1,4   ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,83  ))    
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,13  ),GAU ,AMP(60  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,14  ),GZU ,AMP(61  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,17  ),GAU ,AMP(62  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,18  ),GZU ,AMP(63  ))            
      CALL IOVXXX(W(1,69  ),W(1,83  ),W(1,19  ),GAU ,AMP(64  ))            
      CALL IOVXXX(W(1,71  ),W(1,83  ),W(1,19  ),GAU ,AMP(65  ))            
      CALL IOVXXX(W(1,69  ),W(1,83  ),W(1,22  ),GZU ,AMP(66  ))            
      CALL IOVXXX(W(1,71  ),W(1,83  ),W(1,22  ),GZU ,AMP(67  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,26  ),GAU ,AMP(68  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,27  ),GZU ,AMP(69  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,29  ),GAU ,AMP(70  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,30  ),GZU ,AMP(71  ))            
      CALL FVIXXX(W(1,2   ),W(1,19  ),GAU ,ZERO    ,ZERO    ,W(1,84  ))    
      CALL FVIXXX(W(1,84  ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,85  ))    
      CALL IOVXXX(W(1,85  ),W(1,4   ),W(1,10  ),GAD ,AMP(72  ))            
      CALL IOVXXX(W(1,85  ),W(1,4   ),W(1,15  ),GZD ,AMP(73  ))            
      CALL FVIXXX(W(1,2   ),W(1,22  ),GZU ,ZERO    ,ZERO    ,W(1,86  ))    
      CALL FVIXXX(W(1,86  ),W(1,9   ),GWF ,ZERO    ,ZERO    ,W(1,87  ))    
      CALL IOVXXX(W(1,87  ),W(1,4   ),W(1,10  ),GAD ,AMP(74  ))            
      CALL IOVXXX(W(1,87  ),W(1,4   ),W(1,15  ),GZD ,AMP(75  ))            
      CALL JIOXXX(W(1,84  ),W(1,4   ),GWF ,WMASS   ,WWIDTH  ,W(1,88  ))    
      CALL FVOXXX(W(1,6   ),W(1,88  ),GWF ,ZERO    ,ZERO    ,W(1,89  ))    
      CALL JIOXXX(W(1,5   ),W(1,89  ),GAL ,ZERO    ,ZERO    ,W(1,90  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,90  ),GAL ,AMP(76  ))            
      CALL JIOXXX(W(1,5   ),W(1,89  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,91  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,91  ),GZL ,AMP(77  ))            
      CALL JIOXXX(W(1,86  ),W(1,4   ),GWF ,WMASS   ,WWIDTH  ,W(1,92  ))    
      CALL FVOXXX(W(1,6   ),W(1,92  ),GWF ,ZERO    ,ZERO    ,W(1,93  ))    
      CALL JIOXXX(W(1,5   ),W(1,93  ),GAL ,ZERO    ,ZERO    ,W(1,94  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,94  ),GAL ,AMP(78  ))            
      CALL JIOXXX(W(1,5   ),W(1,93  ),GZL ,ZMASS   ,ZWIDTH  ,W(1,95  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,95  ),GZL ,AMP(79  ))            
      CALL FVIXXX(W(1,5   ),W(1,88  ),GWF ,ZERO    ,ZERO    ,W(1,96  ))    
      CALL JIOXXX(W(1,96  ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,97  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,97  ),GZL ,AMP(80  ))            
      CALL FVIXXX(W(1,5   ),W(1,92  ),GWF ,ZERO    ,ZERO    ,W(1,98  ))    
      CALL JIOXXX(W(1,98  ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,99  ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,99  ),GZL ,AMP(81  ))            
      CALL FVIXXX(W(1,2   ),W(1,46  ),GAU ,ZERO    ,ZERO    ,W(1,100 ))    
      CALL IOVXXX(W(1,100 ),W(1,4   ),W(1,9   ),GWF ,AMP(82  ))            
      CALL FVIXXX(W(1,2   ),W(1,48  ),GZU ,ZERO    ,ZERO    ,W(1,101 ))    
      CALL IOVXXX(W(1,101 ),W(1,4   ),W(1,9   ),GWF ,AMP(83  ))            
      CALL FVIXXX(W(1,2   ),W(1,51  ),GAU ,ZERO    ,ZERO    ,W(1,102 ))    
      CALL IOVXXX(W(1,102 ),W(1,4   ),W(1,9   ),GWF ,AMP(84  ))            
      CALL FVIXXX(W(1,2   ),W(1,53  ),GZU ,ZERO    ,ZERO    ,W(1,103 ))    
      CALL IOVXXX(W(1,103 ),W(1,4   ),W(1,9   ),GWF ,AMP(85  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,56  ),GAU ,AMP(86  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,57  ),GZU ,AMP(87  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,59  ),GAU ,AMP(88  ))            
      CALL IOVXXX(W(1,2   ),W(1,83  ),W(1,60  ),GZU ,AMP(89  ))            
      CALL IOVXXX(W(1,84  ),W(1,83  ),W(1,10  ),GAU ,AMP(90  ))            
      CALL IOVXXX(W(1,84  ),W(1,83  ),W(1,15  ),GZU ,AMP(91  ))            
      CALL IOVXXX(W(1,86  ),W(1,83  ),W(1,10  ),GAU ,AMP(92  ))            
      CALL IOVXXX(W(1,86  ),W(1,83  ),W(1,15  ),GZU ,AMP(93  ))            
      CALL JVVXXX(W(1,88  ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     104 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,104 ),GAL ,AMP(94  ))            
      CALL JVVXXX(W(1,88  ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     105 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,105 ),GZL ,AMP(95  ))            
      CALL JVVXXX(W(1,92  ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     106 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,106 ),GAL ,AMP(96  ))            
      CALL JVVXXX(W(1,92  ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     107 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,107 ),GZL ,AMP(97  ))            
      CALL FVIXXX(W(1,7   ),W(1,88  ),GWF ,ZERO    ,ZERO    ,W(1,108 ))    
      CALL IOVXXX(W(1,108 ),W(1,8   ),W(1,9   ),GWF ,AMP(98  ))            
      CALL FVIXXX(W(1,7   ),W(1,92  ),GWF ,ZERO    ,ZERO    ,W(1,109 ))    
      CALL IOVXXX(W(1,109 ),W(1,8   ),W(1,9   ),GWF ,AMP(99  ))            
      CALL JVVXXX(W(1,67  ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     110 ))                                                          
      CALL IOVXXX(W(1,12  ),W(1,3   ),W(1,110 ),GAD ,AMP(100 ))            
      CALL JVVXXX(W(1,67  ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     111 ))                                                          
      CALL IOVXXX(W(1,12  ),W(1,3   ),W(1,111 ),GZD ,AMP(101 ))            
      CALL IOVXXX(W(1,16  ),W(1,3   ),W(1,110 ),GAD ,AMP(102 ))            
      CALL IOVXXX(W(1,16  ),W(1,3   ),W(1,111 ),GZD ,AMP(103 ))            
      CALL JVVXXX(W(1,9   ),W(1,19  ),GWWA ,WMASS   ,WWIDTH  ,W(1,         
     &     112 ))                                                          
      CALL IOVXXX(W(1,69  ),W(1,4   ),W(1,112 ),GWF ,AMP(104 ))            
      CALL IOVXXX(W(1,71  ),W(1,4   ),W(1,112 ),GWF ,AMP(105 ))            
      CALL JVVXXX(W(1,9   ),W(1,22  ),GWWZ ,WMASS   ,WWIDTH  ,W(1,         
     &     113 ))                                                          
      CALL IOVXXX(W(1,69  ),W(1,4   ),W(1,113 ),GWF ,AMP(106 ))            
      CALL IOVXXX(W(1,71  ),W(1,4   ),W(1,113 ),GWF ,AMP(107 ))            
      CALL IOVXXX(W(1,1   ),W(1,25  ),W(1,110 ),GAD ,AMP(108 ))            
      CALL IOVXXX(W(1,1   ),W(1,25  ),W(1,111 ),GZD ,AMP(109 ))            
      CALL IOVXXX(W(1,1   ),W(1,28  ),W(1,110 ),GAD ,AMP(110 ))            
      CALL IOVXXX(W(1,1   ),W(1,28  ),W(1,111 ),GZD ,AMP(111 ))            
      CALL IOVXXX(W(1,2   ),W(1,31  ),W(1,112 ),GWF ,AMP(112 ))            
      CALL IOVXXX(W(1,2   ),W(1,32  ),W(1,112 ),GWF ,AMP(113 ))            
      CALL IOVXXX(W(1,2   ),W(1,31  ),W(1,113 ),GWF ,AMP(114 ))            
      CALL IOVXXX(W(1,2   ),W(1,32  ),W(1,113 ),GWF ,AMP(115 ))            
      CALL JVVXXX(W(1,19  ),W(1,67  ),GWWA ,WMASS   ,WWIDTH  ,W(1,         
     &     114 ))                                                          
      CALL FVOXXX(W(1,6   ),W(1,114 ),GWF ,ZERO    ,ZERO    ,W(1,115 ))    
      CALL JIOXXX(W(1,5   ),W(1,115 ),GAL ,ZERO    ,ZERO    ,W(1,116 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,116 ),GAL ,AMP(116 ))            
      CALL JIOXXX(W(1,5   ),W(1,115 ),GZL ,ZMASS   ,ZWIDTH  ,W(1,117 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,117 ),GZL ,AMP(117 ))            
      CALL JVVXXX(W(1,22  ),W(1,67  ),GWWZ ,WMASS   ,WWIDTH  ,W(1,         
     &     118 ))                                                          
      CALL FVOXXX(W(1,6   ),W(1,118 ),GWF ,ZERO    ,ZERO    ,W(1,119 ))    
      CALL JIOXXX(W(1,5   ),W(1,119 ),GAL ,ZERO    ,ZERO    ,W(1,120 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,120 ),GAL ,AMP(118 ))            
      CALL JIOXXX(W(1,5   ),W(1,119 ),GZL ,ZMASS   ,ZWIDTH  ,W(1,121 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,121 ),GZL ,AMP(119 ))            
      CALL FVIXXX(W(1,5   ),W(1,114 ),GWF ,ZERO    ,ZERO    ,W(1,122 ))    
      CALL JIOXXX(W(1,122 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,123 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,123 ),GZL ,AMP(120 ))            
      CALL FVIXXX(W(1,5   ),W(1,118 ),GWF ,ZERO    ,ZERO    ,W(1,124 ))    
      CALL JIOXXX(W(1,124 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,125 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,125 ),GZL ,AMP(121 ))            
      CALL VVVXXX(W(1,67  ),W(1,112 ),W(1,10  ),GWWA ,AMP(122 ))           
      CALL VVVXXX(W(1,67  ),W(1,112 ),W(1,15  ),GWWZ ,AMP(123 ))           
      CALL VVVXXX(W(1,67  ),W(1,113 ),W(1,10  ),GWWA ,AMP(124 ))           
      CALL VVVXXX(W(1,67  ),W(1,113 ),W(1,15  ),GWWZ ,AMP(125 ))           
      CALL VVVXXX(W(1,80  ),W(1,9   ),W(1,19  ),GWWA ,AMP(126 ))           
      CALL VVVXXX(W(1,80  ),W(1,9   ),W(1,22  ),GWWZ ,AMP(127 ))           
      CALL IOVXXX(W(1,79  ),W(1,55  ),W(1,9   ),GWF ,AMP(128 ))            
      CALL IOVXXX(W(1,79  ),W(1,58  ),W(1,9   ),GWF ,AMP(129 ))            
      CALL IOVXXX(W(1,79  ),W(1,82  ),W(1,22  ),GZN ,AMP(130 ))            
      CALL HVVXXX(W(1,67  ),W(1,9   ),GWWH ,HMASS   ,HWIDTH  ,W(1,         
     &     126 ))                                                          
      CALL VVSXXX(W(1,15  ),W(1,22  ),W(1,126 ),GZZH ,AMP(131 ))           
      CALL VVVXXX(W(1,67  ),W(1,9   ),W(1,46  ),GWWA ,AMP(132 ))           
      CALL VVVXXX(W(1,67  ),W(1,9   ),W(1,48  ),GWWZ ,AMP(133 ))           
      CALL VVVXXX(W(1,67  ),W(1,9   ),W(1,51  ),GWWA ,AMP(134 ))           
      CALL VVVXXX(W(1,67  ),W(1,9   ),W(1,53  ),GWWZ ,AMP(135 ))           
      CALL IOVXXX(W(1,45  ),W(1,82  ),W(1,67  ),GWF ,AMP(136 ))            
      CALL IOVXXX(W(1,50  ),W(1,82  ),W(1,67  ),GWF ,AMP(137 ))            
      CALL IOVXXX(W(1,7   ),W(1,55  ),W(1,110 ),GAL ,AMP(138 ))            
      CALL IOVXXX(W(1,7   ),W(1,55  ),W(1,111 ),GZL ,AMP(139 ))            
      CALL IOVXXX(W(1,7   ),W(1,58  ),W(1,110 ),GAL ,AMP(140 ))            
      CALL IOVXXX(W(1,7   ),W(1,58  ),W(1,111 ),GZL ,AMP(141 ))            
      CALL JVVXXX(W(1,114 ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     127 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,127 ),GAL ,AMP(142 ))            
      CALL JVVXXX(W(1,114 ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     128 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,128 ),GZL ,AMP(143 ))            
      CALL JVVXXX(W(1,118 ),W(1,9   ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     129 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,129 ),GAL ,AMP(144 ))            
      CALL JVVXXX(W(1,118 ),W(1,9   ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     130 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,130 ),GZL ,AMP(145 ))            
      CALL FVIXXX(W(1,7   ),W(1,114 ),GWF ,ZERO    ,ZERO    ,W(1,131 ))    
      CALL IOVXXX(W(1,131 ),W(1,8   ),W(1,9   ),GWF ,AMP(146 ))            
      CALL FVIXXX(W(1,7   ),W(1,118 ),GWF ,ZERO    ,ZERO    ,W(1,132 ))    
      CALL IOVXXX(W(1,132 ),W(1,8   ),W(1,9   ),GWF ,AMP(147 ))            
      CALL W3W3XX(W(1,67  ),W(1,19  ),W(1,9   ),W(1,10  ),GWWA ,GWWA ,     
     &     AMP(148 ))                                                      
      CALL W3W3XX(W(1,67  ),W(1,15  ),W(1,9   ),W(1,19  ),GWWZ ,GWWA ,     
     &     AMP(149 ))                                                      
      CALL W3W3XX(W(1,67  ),W(1,22  ),W(1,9   ),W(1,10  ),GWWZ ,GWWA ,     
     &     AMP(150 ))                                                      
      CALL W3W3XX(W(1,67  ),W(1,22  ),W(1,9   ),W(1,15  ),GWWZ ,GWWZ ,     
     &     AMP(151 ))                                                      
      CALL FVOXXX(W(1,6   ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,133 ))    
      CALL JIOXXX(W(1,5   ),W(1,133 ),GAL ,ZERO    ,ZERO    ,W(1,134 ))    
      CALL IOVXXX(W(1,12  ),W(1,3   ),W(1,134 ),GAD ,AMP(152 ))            
      CALL JIOXXX(W(1,5   ),W(1,133 ),GZL ,ZMASS   ,ZWIDTH  ,W(1,135 ))    
      CALL IOVXXX(W(1,12  ),W(1,3   ),W(1,135 ),GZD ,AMP(153 ))            
      CALL IOVXXX(W(1,16  ),W(1,3   ),W(1,134 ),GAD ,AMP(154 ))            
      CALL IOVXXX(W(1,16  ),W(1,3   ),W(1,135 ),GZD ,AMP(155 ))            
      CALL FVIXXX(W(1,5   ),W(1,19  ),GAL ,ZERO    ,ZERO    ,W(1,136 ))    
      CALL JIOXXX(W(1,136 ),W(1,6   ),GWF ,WMASS   ,WWIDTH  ,W(1,137 ))    
      CALL FVOXXX(W(1,4   ),W(1,137 ),GWF ,ZERO    ,ZERO    ,W(1,138 ))    
      CALL IOVXXX(W(1,2   ),W(1,138 ),W(1,10  ),GAU ,AMP(156 ))            
      CALL IOVXXX(W(1,2   ),W(1,138 ),W(1,15  ),GZU ,AMP(157 ))            
      CALL FVIXXX(W(1,5   ),W(1,22  ),GZL ,ZERO    ,ZERO    ,W(1,139 ))    
      CALL JIOXXX(W(1,139 ),W(1,6   ),GWF ,WMASS   ,WWIDTH  ,W(1,140 ))    
      CALL FVOXXX(W(1,4   ),W(1,140 ),GWF ,ZERO    ,ZERO    ,W(1,141 ))    
      CALL IOVXXX(W(1,2   ),W(1,141 ),W(1,10  ),GAU ,AMP(158 ))            
      CALL IOVXXX(W(1,2   ),W(1,141 ),W(1,15  ),GZU ,AMP(159 ))            
      CALL IOVXXX(W(1,1   ),W(1,25  ),W(1,134 ),GAD ,AMP(160 ))            
      CALL IOVXXX(W(1,1   ),W(1,25  ),W(1,135 ),GZD ,AMP(161 ))            
      CALL IOVXXX(W(1,1   ),W(1,28  ),W(1,134 ),GAD ,AMP(162 ))            
      CALL IOVXXX(W(1,1   ),W(1,28  ),W(1,135 ),GZD ,AMP(163 ))            
      CALL FVIXXX(W(1,2   ),W(1,137 ),GWF ,ZERO    ,ZERO    ,W(1,142 ))    
      CALL IOVXXX(W(1,142 ),W(1,4   ),W(1,10  ),GAD ,AMP(164 ))            
      CALL IOVXXX(W(1,142 ),W(1,4   ),W(1,15  ),GZD ,AMP(165 ))            
      CALL FVIXXX(W(1,2   ),W(1,140 ),GWF ,ZERO    ,ZERO    ,W(1,143 ))    
      CALL IOVXXX(W(1,143 ),W(1,4   ),W(1,10  ),GAD ,AMP(166 ))            
      CALL IOVXXX(W(1,143 ),W(1,4   ),W(1,15  ),GZD ,AMP(167 ))            
      CALL FVOXXX(W(1,133 ),W(1,19  ),GAL ,ZERO    ,ZERO    ,W(1,144 ))    
      CALL IOVXXX(W(1,5   ),W(1,144 ),W(1,10  ),GAL ,AMP(168 ))            
      CALL IOVXXX(W(1,5   ),W(1,144 ),W(1,15  ),GZL ,AMP(169 ))            
      CALL FVOXXX(W(1,133 ),W(1,22  ),GZL ,ZERO    ,ZERO    ,W(1,145 ))    
      CALL IOVXXX(W(1,5   ),W(1,145 ),W(1,10  ),GAL ,AMP(170 ))            
      CALL IOVXXX(W(1,5   ),W(1,145 ),W(1,15  ),GZL ,AMP(171 ))            
      CALL FVIXXX(W(1,136 ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,146 ))    
      CALL JIOXXX(W(1,146 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,147 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,147 ),GZL ,AMP(172 ))            
      CALL FVIXXX(W(1,139 ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,148 ))    
      CALL JIOXXX(W(1,148 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,149 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,149 ),GZL ,AMP(173 ))            
      CALL JIOXXX(W(1,136 ),W(1,133 ),GAL ,ZERO    ,ZERO    ,W(1,150 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,150 ),GAL ,AMP(174 ))            
      CALL JIOXXX(W(1,136 ),W(1,133 ),GZL ,ZMASS   ,ZWIDTH  ,W(1,151 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,151 ),GZL ,AMP(175 ))            
      CALL JIOXXX(W(1,139 ),W(1,133 ),GAL ,ZERO    ,ZERO    ,W(1,152 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,152 ),GAL ,AMP(176 ))            
      CALL JIOXXX(W(1,139 ),W(1,133 ),GZL ,ZMASS   ,ZWIDTH  ,W(1,153 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,153 ),GZL ,AMP(177 ))            
      CALL IOVXXX(W(1,5   ),W(1,133 ),W(1,46  ),GAL ,AMP(178 ))            
      CALL IOVXXX(W(1,5   ),W(1,133 ),W(1,48  ),GZL ,AMP(179 ))            
      CALL IOVXXX(W(1,5   ),W(1,133 ),W(1,51  ),GAL ,AMP(180 ))            
      CALL IOVXXX(W(1,5   ),W(1,133 ),W(1,53  ),GZL ,AMP(181 ))            
      CALL IOVXXX(W(1,7   ),W(1,55  ),W(1,134 ),GAL ,AMP(182 ))            
      CALL IOVXXX(W(1,7   ),W(1,55  ),W(1,135 ),GZL ,AMP(183 ))            
      CALL IOVXXX(W(1,7   ),W(1,58  ),W(1,134 ),GAL ,AMP(184 ))            
      CALL IOVXXX(W(1,7   ),W(1,58  ),W(1,135 ),GZL ,AMP(185 ))            
      CALL JVVXXX(W(1,67  ),W(1,137 ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     154 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,154 ),GAL ,AMP(186 ))            
      CALL JVVXXX(W(1,67  ),W(1,137 ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     155 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,155 ),GZL ,AMP(187 ))            
      CALL JVVXXX(W(1,67  ),W(1,140 ),GWWA ,ZERO    ,ZERO    ,W(1,         
     &     156 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,156 ),GAL ,AMP(188 ))            
      CALL JVVXXX(W(1,67  ),W(1,140 ),GWWZ ,ZMASS   ,ZWIDTH  ,W(1,         
     &     157 ))                                                          
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,157 ),GZL ,AMP(189 ))            
      CALL IOVXXX(W(1,79  ),W(1,8   ),W(1,137 ),GWF ,AMP(190 ))            
      CALL IOVXXX(W(1,79  ),W(1,8   ),W(1,140 ),GWF ,AMP(191 ))            
      CALL FVIXXX(W(1,5   ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,158 ))    
      CALL JIOXXX(W(1,158 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,159 ))    
      CALL FVOXXX(W(1,3   ),W(1,159 ),GZD ,ZERO    ,ZERO    ,W(1,160 ))    
      CALL IOVXXX(W(1,1   ),W(1,160 ),W(1,10  ),GAD ,AMP(192 ))            
      CALL IOVXXX(W(1,1   ),W(1,160 ),W(1,15  ),GZD ,AMP(193 ))            
      CALL FVOXXX(W(1,6   ),W(1,22  ),GZN ,ZERO    ,ZERO    ,W(1,161 ))    
      CALL JIOXXX(W(1,5   ),W(1,161 ),GWF ,WMASS   ,WWIDTH  ,W(1,162 ))    
      CALL IOVXXX(W(1,69  ),W(1,4   ),W(1,162 ),GWF ,AMP(194 ))            
      CALL IOVXXX(W(1,71  ),W(1,4   ),W(1,162 ),GWF ,AMP(195 ))            
      CALL FVIXXX(W(1,1   ),W(1,159 ),GZD ,ZERO    ,ZERO    ,W(1,163 ))    
      CALL IOVXXX(W(1,163 ),W(1,3   ),W(1,10  ),GAD ,AMP(196 ))            
      CALL IOVXXX(W(1,163 ),W(1,3   ),W(1,15  ),GZD ,AMP(197 ))            
      CALL IOVXXX(W(1,2   ),W(1,31  ),W(1,162 ),GWF ,AMP(198 ))            
      CALL IOVXXX(W(1,2   ),W(1,32  ),W(1,162 ),GWF ,AMP(199 ))            
      CALL FVOXXX(W(1,161 ),W(1,67  ),GWF ,ZERO    ,ZERO    ,W(1,164 ))    
      CALL IOVXXX(W(1,5   ),W(1,164 ),W(1,10  ),GAL ,AMP(200 ))            
      CALL IOVXXX(W(1,5   ),W(1,164 ),W(1,15  ),GZL ,AMP(201 ))            
      CALL FVIXXX(W(1,158 ),W(1,22  ),GZN ,ZERO    ,ZERO    ,W(1,165 ))    
      CALL JIOXXX(W(1,165 ),W(1,6   ),GZN ,ZMASS   ,ZWIDTH  ,W(1,166 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,166 ),GZL ,AMP(202 ))            
      CALL VVVXXX(W(1,67  ),W(1,162 ),W(1,10  ),GWWA ,AMP(203 ))           
      CALL VVVXXX(W(1,67  ),W(1,162 ),W(1,15  ),GWWZ ,AMP(204 ))           
      CALL IOVXXX(W(1,5   ),W(1,161 ),W(1,80  ),GWF ,AMP(205 ))            
      CALL JIOXXX(W(1,158 ),W(1,161 ),GZN ,ZMASS   ,ZWIDTH  ,W(1,167 ))    
      CALL IOVXXX(W(1,7   ),W(1,8   ),W(1,167 ),GZL ,AMP(206 ))            
      CALL IOVXXX(W(1,45  ),W(1,8   ),W(1,159 ),GZL ,AMP(207 ))            
      CALL IOVXXX(W(1,50  ),W(1,8   ),W(1,159 ),GZL ,AMP(208 ))            
      CALL FVIXXX(W(1,7   ),W(1,159 ),GZL ,ZERO    ,ZERO    ,W(1,168 ))    
      CALL IOVXXX(W(1,168 ),W(1,8   ),W(1,19  ),GAL ,AMP(209 ))            
      CALL IOVXXX(W(1,168 ),W(1,8   ),W(1,22  ),GZL ,AMP(210 ))            
      JAMP(   1) = -AMP(   1)-AMP(   2)-AMP(   3)-AMP(   4)-AMP(   5)
     &             -AMP(   6)-AMP(   7)-AMP(   8)-AMP(   9)-AMP(  10)
     &             -AMP(  11)-AMP(  12)-AMP(  13)-AMP(  14)-AMP(  15)
     &             -AMP(  16)-AMP(  17)-AMP(  18)-AMP(  19)-AMP(  20)
     &             -AMP(  21)-AMP(  22)-AMP(  23)-AMP(  24)-AMP(  25)
     &             -AMP(  26)-AMP(  27)-AMP(  28)-AMP(  29)-AMP(  30)
     &             -AMP(  31)-AMP(  32)-AMP(  33)-AMP(  34)-AMP(  35)
     &             -AMP(  36)-AMP(  37)-AMP(  38)-AMP(  39)-AMP(  40)
     &             -AMP(  41)-AMP(  42)-AMP(  43)-AMP(  44)-AMP(  45)
     &             -AMP(  46)-AMP(  47)-AMP(  48)-AMP(  49)-AMP(  50)
     &             -AMP(  51)-AMP(  52)-AMP(  53)-AMP(  54)-AMP(  55)
     &             -AMP(  56)-AMP(  57)-AMP(  58)-AMP(  59)-AMP(  60)
     &             -AMP(  61)-AMP(  62)-AMP(  63)-AMP(  64)-AMP(  65)
     &             -AMP(  66)-AMP(  67)-AMP(  68)-AMP(  69)-AMP(  70)
     &             -AMP(  71)-AMP(  72)-AMP(  73)-AMP(  74)-AMP(  75)
     &             -AMP(  76)-AMP(  77)-AMP(  78)-AMP(  79)-AMP(  80)
     &             -AMP(  81)-AMP(  82)-AMP(  83)-AMP(  84)-AMP(  85)
     &             -AMP(  86)-AMP(  87)-AMP(  88)-AMP(  89)-AMP(  90)
     &             -AMP(  91)-AMP(  92)-AMP(  93)-AMP(  94)-AMP(  95)
     &             -AMP(  96)-AMP(  97)-AMP(  98)-AMP(  99)-AMP( 100)
     &             -AMP( 101)-AMP( 102)-AMP( 103)-AMP( 104)-AMP( 105)
     &             -AMP( 106)-AMP( 107)-AMP( 108)-AMP( 109)-AMP( 110)
     &             -AMP( 111)-AMP( 112)-AMP( 113)-AMP( 114)-AMP( 115)
     &             -AMP( 116)-AMP( 117)-AMP( 118)-AMP( 119)-AMP( 120)
     &             -AMP( 121)-AMP( 122)-AMP( 123)-AMP( 124)-AMP( 125)
     &             -AMP( 126)-AMP( 127)-AMP( 128)-AMP( 129)-AMP( 130)
     &             -AMP( 131)-AMP( 132)-AMP( 133)-AMP( 134)-AMP( 135)
     &             -AMP( 136)-AMP( 137)-AMP( 138)-AMP( 139)-AMP( 140)
     &             -AMP( 141)-AMP( 142)-AMP( 143)-AMP( 144)-AMP( 145)
     &             -AMP( 146)-AMP( 147)-AMP( 148)-AMP( 149)-AMP( 150)
     &             -AMP( 151)-AMP( 152)-AMP( 153)-AMP( 154)-AMP( 155)
     &             -AMP( 156)-AMP( 157)-AMP( 158)-AMP( 159)-AMP( 160)
     &             -AMP( 161)-AMP( 162)-AMP( 163)-AMP( 164)-AMP( 165)
     &             -AMP( 166)-AMP( 167)-AMP( 168)-AMP( 169)-AMP( 170)
     &             -AMP( 171)-AMP( 172)-AMP( 173)-AMP( 174)-AMP( 175)
     &             -AMP( 176)-AMP( 177)-AMP( 178)-AMP( 179)-AMP( 180)
     &             -AMP( 181)-AMP( 182)-AMP( 183)-AMP( 184)-AMP( 185)
     &             -AMP( 186)-AMP( 187)-AMP( 188)-AMP( 189)-AMP( 190)
     &             -AMP( 191)-AMP( 192)-AMP( 193)-AMP( 194)-AMP( 195)
     &             -AMP( 196)-AMP( 197)-AMP( 198)-AMP( 199)-AMP( 200)
     &             -AMP( 201)-AMP( 202)-AMP( 203)-AMP( 204)-AMP( 205)
     &             -AMP( 206)-AMP( 207)-AMP( 208)-AMP( 209)-AMP( 210)


      isw1 = nhel(1)
      isw3 = nhel(3)

      if (nhel(7).eq.-1.and.nhel(8).eq.-1) then 
         h = 1
      elseif (nhel(7).eq.+1.and.nhel(8).eq.+1) then 
         h = 2
      endif
      ipw = 2 !ddcs type
            
c      if (nhel(5).eq.-1.and.nhel(6).eq.-1.and.
c     #    nhel(7).eq.-1.and.nhel(8).eq.-1) 	then	!corresp. to h=1
c       if (nhel(5).eq.-1.and.nhel(6).eq.-1.and.
c     #    nhel(7).eq.+1.and.nhel(8).eq.+1) 	then	!corresp. to h=2
    
     
      if (((h.eq.1).and.(nhel(5).eq.-1.and.nhel(6).eq.-1.and.
     #    nhel(7).eq.-1.and.nhel(8).eq.-1)) .or.	
     #    ((h.eq.2).and.(nhel(5).eq.-1.and.nhel(6).eq.-1.and.
     #    nhel(7).eq.+1.and.nhel(8).eq.+1))) 	then	
     
      	do i = 1,210
	 tampw(i,h,isw1,isw3,ipw) = -amp(i)
     	enddo
      
      endif

      DDCS = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          DDCS =DDCS+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
  
c      Do I = 1, NGRAPHS
c          amp2(i)=amp2(i)+amp(i)*dconjg(amp(i))
c      Enddo
c      Do I = 1, NCOLOR
c          Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
c      Enddo
cC      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
