C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(1,2)
C     
      SUBROUTINE MP_R2_QQ_2_0(F1, F2, COUP,VERTEX)
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 F2(*)
      COMPLEX*32 COUP
      COMPLEX*32 TMP4
      COMPLEX*32 VERTEX
      COMPLEX*32 F1(*)
      TMP4 = (F1(5)*F2(5)+F1(6)*F2(6)+F1(7)*F2(7)+F1(8)*F2(8))
      VERTEX = COUP*(-CI * TMP4)
      END


