C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     2*Epsilon(1,2,3,-1)*P(-1,1) + 2*Epsilon(1,2,3,-1)*P(-1,2)
C     
      SUBROUTINE VVV1_1(V2, V3, COUP, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 V3(*)
      REAL*8 P1(0:3)
      REAL*8 M1
      REAL*8 P2(0:3)
      COMPLEX*16 TMP45
      REAL*8 W1
      COMPLEX*16 DENOM
      COMPLEX*16 OM1
      COMPLEX*16 COUP
      COMPLEX*16 V1(6)
      OM1 = 0D0
      IF (M1.NE.0D0) OM1=1D0/(M1*(M1 - CI*W1))
c     IF (M1.NE.0D0) OM1=1D0/M1**2
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      V1(1) = +V2(1)+V3(1)
      V1(2) = +V2(2)+V3(2)
      P1(0) = -DBLE(V1(1))
      P1(1) = -DBLE(V1(2))
      P1(2) = -DIMAG(V1(2))
      P1(3) = -DIMAG(V1(1))
      TMP45 = -1D0*(P1(0)*(P2(1)*(V3(5)*V2(6)-V3(6)*V2(5))+(P2(2)
     $ *(V3(6)*V2(4)-V3(4)*V2(6))+P2(3)*(V3(4)*V2(5)-V3(5)*V2(4))))
     $ +(P1(1)*(P2(0)*(V3(6)*V2(5)-V3(5)*V2(6))+(P2(2)*(V3(3)*V2(6)
     $ -V3(6)*V2(3))+P2(3)*(V3(5)*V2(3)-V3(3)*V2(5))))+(P1(2)*(P2(0)
     $ *(V3(4)*V2(6)-V3(6)*V2(4))+(P2(1)*(V3(6)*V2(3)-V3(3)*V2(6))
     $ +P2(3)*(V3(3)*V2(4)-V3(4)*V2(3))))+P1(3)*(P2(0)*(V3(5)*V2(4)
     $ -V3(4)*V2(5))+(P2(1)*(V3(3)*V2(5)-V3(5)*V2(3))+P2(2)*(V3(4)
     $ *V2(3)-V3(3)*V2(4)))))))
      DENOM = COUP/(P1(0)**2-P1(1)**2-P1(2)**2-P1(3)**2 - M1 * (M1 
     $ -CI* W1))
      V1(3)= DENOM*2D0 * CI*(V2(4)*(V3(5)*-1D0*(P1(3)+P2(3))+V3(6)
     $ *(P1(2)+P2(2)))+(V2(5)*(V3(4)*(P1(3)+P2(3))-V3(6)*(P1(1)
     $ +P2(1)))+(V2(6)*(V3(4)*-1D0*(P1(2)+P2(2))+V3(5)*(P1(1)+P2(1)))
     $ +P1(0)*OM1*TMP45)))
      V1(4)= DENOM*-2D0 * CI*(V2(3)*(V3(5)*(P1(3)+P2(3))-V3(6)*(P1(2)
     $ +P2(2)))+(V2(5)*(V3(3)*-1D0*(P1(3)+P2(3))+V3(6)*(P1(0)+P2(0)))
     $ +(V2(6)*(V3(3)*(P1(2)+P2(2))-V3(5)*(P1(0)+P2(0)))-P1(1)*OM1
     $ *TMP45)))
      V1(5)= DENOM*-2D0 * CI*(V2(3)*(V3(4)*-1D0*(P1(3)+P2(3))
     $ +V3(6)*(P1(1)+P2(1)))+(V2(4)*(V3(3)*(P1(3)+P2(3))-V3(6)*(P1(0)
     $ +P2(0)))+(V2(6)*(V3(3)*-1D0*(P1(1)+P2(1))+V3(4)*(P1(0)
     $ +P2(0)))-P1(2)*OM1*TMP45)))
      V1(6)= DENOM*-2D0 * CI*(V2(3)*(V3(4)*(P1(2)+P2(2))-V3(5)*(P1(1)
     $ +P2(1)))+(V2(4)*(V3(3)*-1D0*(P1(2)+P2(2))+V3(5)*(P1(0)+P2(0)))
     $ +(V2(5)*(V3(3)*(P1(1)+P2(1))-V3(4)*(P1(0)+P2(0)))-P1(3)*OM1
     $ *TMP45)))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     2*Epsilon(1,2,3,-1)*P(-1,1) + 2*Epsilon(1,2,3,-1)*P(-1,2)
C     
      SUBROUTINE VVV1_10_3_5_6_7_9_1(V2, V3, COUP1, COUP2, COUP3
     $ , COUP4, COUP5, COUP6, COUP7, M1, W1,V1)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 V2(*)
      COMPLEX*16 COUP2
      COMPLEX*16 V3(*)
      COMPLEX*16 COUP6
      REAL*8 P1(0:3)
      REAL*8 M1
      COMPLEX*16 COUP5
      REAL*8 P2(0:3)
      COMPLEX*16 COUP7
      REAL*8 W1
      COMPLEX*16 COUP1
      COMPLEX*16 DENOM
      COMPLEX*16 COUP3
      COMPLEX*16 VTMP(6)
      COMPLEX*16 OM1
      INTEGER*4 I
      COMPLEX*16 V1(6)
      COMPLEX*16 COUP4
      CALL VVV1_1(V2,V3,COUP1,M1,W1,V1)
      CALL VVV10_1(V2,V3,COUP2,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVV3_1(V2,V3,COUP3,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVV5_1(V2,V3,COUP4,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVV6_1(V2,V3,COUP5,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVV7_1(V2,V3,COUP6,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      CALL VVV9_1(V2,V3,COUP7,M1,W1,VTMP)
      DO I = 3, 6
        V1(I) = V1(I) + VTMP(I)
      ENDDO
      END


