#if 0
* renconst.h
* RC declarations
* generated by FormCalc 7.5 on 13-Oct-2016 13:51
#endif

	ComplexType dCKM1(3,3), dZfL1(4,3,3), dZfR1(4,3,3),dMf1(4,3)
	common /renconst/ dCKM1, dZfL1, dZfR1,dMf1


