#!/bin/bash
PRE="subar_"

for file in *.F *.f; do
    # Dateien umbenennen -> Prefix anhängen
    echo "${PRE}${file}"
    mv "$file" "${PRE}${file}"
done
    
for file in $(find . -type f -iname "*.f" -o -iname "*.F"); do
    # alle Vorkommnisse von vars.h durch xxbar_vars.h ersetzen usw.
    sed -i "" -e "s/vars.h/${PRE}vars.h/g" $file
    sed -i "" -e "s/abbr0s/${PRE}abbr0s/g" $file
    sed -i "" -e "s/abbr1s/${PRE}abbr1s/g" $file
    sed -i "" -e "s/abbr0h/${PRE}abbr0h/g" $file
    sed -i "" -e "s/abbr1h/${PRE}abbr1h/g" $file
    sed -i "" -e "s/abbr0angle/${PRE}abbr0angle/g" $file
    sed -i "" -e "s/abbr1angle/${PRE}abbr1angle/g" $file
    sed -i "" -e "s/born/${PRE}born/g" $file
    sed -i "" -e "s/vert/${PRE}vert/g" $file
    sed -i "" -e "s/self/${PRE}self/g" $file
    sed -i "" -e "s/box/${PRE}box/g" $file
done
