#if 0
* vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Mar-2015 20:16
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 5

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub10, Sub29, Sub30, Sub33, Sub34, Sub35, Sub39
	ComplexType Sub41, Sub42, Sub5, Sub52, Sub61, Sub62, Sub92
	ComplexType Sub101(3)
	common /dbarc_abbrev1s/ Sub10, Sub29, Sub30, Sub33, Sub34, Sub35
	common /dbarc_abbrev1s/ Sub39, Sub41, Sub42, Sub5, Sub52, Sub61
	common /dbarc_abbrev1s/ Sub62, Sub92, Sub101

	ComplexType Opt4, Opt5, Sub1, Sub2, Sub3, Sub4
	common /dbarc_abbrev0angle/ Opt4, Opt5, Sub1, Sub2, Sub3, Sub4

	ComplexType Sub11, Sub37, Sub38, Sub43, Sub46, Sub6, Sub64
	ComplexType Sub65, Sub66, Sub67, Sub74, Sub75, Sub76, Sub77
	ComplexType Sub78, Sub8, Sub84, Sub85, Sub86, Sub9, Sub91
	common /dbarc_abbrev1angle/ Sub11, Sub37, Sub38, Sub43, Sub46, Sub6
	common /dbarc_abbrev1angle/ Sub64, Sub65, Sub66, Sub67, Sub74
	common /dbarc_abbrev1angle/ Sub75, Sub76, Sub77, Sub78, Sub8
	common /dbarc_abbrev1angle/ Sub84, Sub85, Sub86, Sub9, Sub91

	ComplexType Abb1, Abb10, Abb2, Abb3, Abb4, Abb5, Abb6, Abb7
	ComplexType Abb8, Abb9, AbbSum1, AbbSum2, AbbSum3, AbbSum4
	ComplexType AbbSum47, AbbSum48, AbbSum5, AbbSum6, AbbSum7
	ComplexType AbbSum72, F1, F2, F3, F4, F5, F6, Opt1, Pair1
	ComplexType Pair2, Pair3, Pair4, Pair5, Pair6, Pair7, Pair8
	ComplexType Pair9
	common /dbarc_abbrev0hel/ Abb1, Abb10, Abb2, Abb3, Abb4, Abb5, Abb6
	common /dbarc_abbrev0hel/ Abb7, Abb8, Abb9, AbbSum1, AbbSum2
	common /dbarc_abbrev0hel/ AbbSum3, AbbSum4, AbbSum47, AbbSum48
	common /dbarc_abbrev0hel/ AbbSum5, AbbSum6, AbbSum7, AbbSum72, F1
	common /dbarc_abbrev0hel/ F2, F3, F4, F5, F6, Opt1, Pair1, Pair2
	common /dbarc_abbrev0hel/ Pair3, Pair4, Pair5, Pair6, Pair7, Pair8
	common /dbarc_abbrev0hel/ Pair9

	ComplexType Abb11, Abb12, Abb13, Abb14, Abb15, Abb16, Abb17
	ComplexType Abb18, Abb19, Abb20, Abb21, Abb22, Abb23, Abb24
	ComplexType Abb25, Abb26, Abb27, Abb28, Abb29, Abb30, Abb31
	ComplexType Abb32, Abb33, Abb34, Abb35, Abb36, Abb37
	ComplexType AbbSum10, AbbSum100, AbbSum101, AbbSum102
	ComplexType AbbSum103, AbbSum104, AbbSum105, AbbSum106
	ComplexType AbbSum107, AbbSum108, AbbSum109, AbbSum11
	ComplexType AbbSum110, AbbSum111, AbbSum112, AbbSum113
	ComplexType AbbSum114, AbbSum115, AbbSum116, AbbSum117
	ComplexType AbbSum118, AbbSum119, AbbSum12, AbbSum120
	ComplexType AbbSum121, AbbSum122, AbbSum123, AbbSum124
	ComplexType AbbSum125, AbbSum126, AbbSum127, AbbSum128
	ComplexType AbbSum129, AbbSum13, AbbSum130, AbbSum131
	ComplexType AbbSum132, AbbSum133, AbbSum134, AbbSum135
	ComplexType AbbSum136, AbbSum137, AbbSum138, AbbSum139
	ComplexType AbbSum14, AbbSum140, AbbSum141, AbbSum142
	ComplexType AbbSum143, AbbSum144, AbbSum145, AbbSum146
	ComplexType AbbSum147, AbbSum148, AbbSum149, AbbSum15
	ComplexType AbbSum150, AbbSum151, AbbSum152, AbbSum153
	ComplexType AbbSum154, AbbSum155, AbbSum156, AbbSum157
	ComplexType AbbSum158, AbbSum159, AbbSum16, AbbSum160
	ComplexType AbbSum161, AbbSum162, AbbSum163, AbbSum164
	ComplexType AbbSum165, AbbSum166, AbbSum167, AbbSum168
	ComplexType AbbSum169, AbbSum17, AbbSum170, AbbSum171
	ComplexType AbbSum172, AbbSum173, AbbSum174, AbbSum175
	ComplexType AbbSum176, AbbSum177, AbbSum178, AbbSum179
	ComplexType AbbSum18, AbbSum180, AbbSum181, AbbSum182
	ComplexType AbbSum183, AbbSum184, AbbSum185, AbbSum186
	ComplexType AbbSum187, AbbSum188, AbbSum189, AbbSum19
	ComplexType AbbSum190, AbbSum191, AbbSum192, AbbSum193
	ComplexType AbbSum194, AbbSum195, AbbSum196, AbbSum197
	ComplexType AbbSum198, AbbSum199, AbbSum20, AbbSum200
	ComplexType AbbSum201, AbbSum202, AbbSum203, AbbSum204
	ComplexType AbbSum205, AbbSum206, AbbSum207, AbbSum208
	ComplexType AbbSum209, AbbSum21, AbbSum210, AbbSum22
	ComplexType AbbSum23, AbbSum24, AbbSum25, AbbSum26, AbbSum27
	ComplexType AbbSum28, AbbSum29, AbbSum30, AbbSum31, AbbSum32
	ComplexType AbbSum33, AbbSum34, AbbSum35, AbbSum36, AbbSum37
	ComplexType AbbSum38, AbbSum39, AbbSum40, AbbSum41, AbbSum42
	ComplexType AbbSum43, AbbSum44, AbbSum45, AbbSum46, AbbSum49
	ComplexType AbbSum50, AbbSum51, AbbSum52, AbbSum53, AbbSum54
	ComplexType AbbSum55, AbbSum56, AbbSum57, AbbSum58, AbbSum59
	ComplexType AbbSum60, AbbSum61, AbbSum62, AbbSum63, AbbSum64
	ComplexType AbbSum65, AbbSum66, AbbSum67, AbbSum68, AbbSum69
	ComplexType AbbSum70, AbbSum71, AbbSum73, AbbSum74, AbbSum75
	ComplexType AbbSum76, AbbSum77, AbbSum78, AbbSum79, AbbSum8
	ComplexType AbbSum80, AbbSum81, AbbSum82, AbbSum83, AbbSum84
	ComplexType AbbSum85, AbbSum86, AbbSum87, AbbSum88, AbbSum89
	ComplexType AbbSum9, AbbSum90, AbbSum91, AbbSum92, AbbSum93
	ComplexType AbbSum94, AbbSum95, AbbSum96, AbbSum97, AbbSum98
	ComplexType AbbSum99, F7, F8, F9, Opt2, Opt3, Sub112, Sub113
	ComplexType Sub114, Sub115, Sub116, Sub117, Sub118, Sub119
	ComplexType Sub12, Sub120, Sub121, Sub122, Sub123, Sub124
	ComplexType Sub125, Sub126, Sub127, Sub128, Sub129, Sub13
	ComplexType Sub130, Sub131, Sub132, Sub133, Sub134, Sub135
	ComplexType Sub136, Sub137, Sub14, Sub15, Sub16, Sub17
	ComplexType Sub18, Sub31, Sub32, Sub36, Sub40, Sub44, Sub45
	ComplexType Sub47, Sub48, Sub49, Sub50, Sub51, Sub53, Sub54
	ComplexType Sub55, Sub56, Sub57, Sub58, Sub59, Sub60, Sub63
	ComplexType Sub68, Sub69, Sub7, Sub70, Sub71, Sub72, Sub73
	ComplexType Sub79, Sub80, Sub81, Sub82, Sub83, Sub87, Sub88
	ComplexType Sub89, Sub90, Sub93, Sub94, Sub100(3), Sub102(3)
	ComplexType Sub103(3), Sub104(3), Sub105(3), Sub106(3)
	ComplexType Sub107(3), Sub108(3), Sub109(3), Sub110(3)
	ComplexType Sub111(3), Sub19(3), Sub20(3), Sub21(3)
	ComplexType Sub22(3), Sub23(3), Sub24(3), Sub25(3), Sub26(3)
	ComplexType Sub27(3), Sub28(3), Sub95(3), Sub96(3), Sub97(3)
	ComplexType Sub98(3), Sub99(3)
	common /dbarc_abbrev1hel/ Abb11, Abb12, Abb13, Abb14, Abb15, Abb16
	common /dbarc_abbrev1hel/ Abb17, Abb18, Abb19, Abb20, Abb21, Abb22
	common /dbarc_abbrev1hel/ Abb23, Abb24, Abb25, Abb26, Abb27, Abb28
	common /dbarc_abbrev1hel/ Abb29, Abb30, Abb31, Abb32, Abb33, Abb34
	common /dbarc_abbrev1hel/ Abb35, Abb36, Abb37, AbbSum10, AbbSum100
	common /dbarc_abbrev1hel/ AbbSum101, AbbSum102, AbbSum103
	common /dbarc_abbrev1hel/ AbbSum104, AbbSum105, AbbSum106
	common /dbarc_abbrev1hel/ AbbSum107, AbbSum108, AbbSum109
	common /dbarc_abbrev1hel/ AbbSum11, AbbSum110, AbbSum111
	common /dbarc_abbrev1hel/ AbbSum112, AbbSum113, AbbSum114
	common /dbarc_abbrev1hel/ AbbSum115, AbbSum116, AbbSum117
	common /dbarc_abbrev1hel/ AbbSum118, AbbSum119, AbbSum12
	common /dbarc_abbrev1hel/ AbbSum120, AbbSum121, AbbSum122
	common /dbarc_abbrev1hel/ AbbSum123, AbbSum124, AbbSum125
	common /dbarc_abbrev1hel/ AbbSum126, AbbSum127, AbbSum128
	common /dbarc_abbrev1hel/ AbbSum129, AbbSum13, AbbSum130
	common /dbarc_abbrev1hel/ AbbSum131, AbbSum132, AbbSum133
	common /dbarc_abbrev1hel/ AbbSum134, AbbSum135, AbbSum136
	common /dbarc_abbrev1hel/ AbbSum137, AbbSum138, AbbSum139
	common /dbarc_abbrev1hel/ AbbSum14, AbbSum140, AbbSum141
	common /dbarc_abbrev1hel/ AbbSum142, AbbSum143, AbbSum144
	common /dbarc_abbrev1hel/ AbbSum145, AbbSum146, AbbSum147
	common /dbarc_abbrev1hel/ AbbSum148, AbbSum149, AbbSum15
	common /dbarc_abbrev1hel/ AbbSum150, AbbSum151, AbbSum152
	common /dbarc_abbrev1hel/ AbbSum153, AbbSum154, AbbSum155
	common /dbarc_abbrev1hel/ AbbSum156, AbbSum157, AbbSum158
	common /dbarc_abbrev1hel/ AbbSum159, AbbSum16, AbbSum160
	common /dbarc_abbrev1hel/ AbbSum161, AbbSum162, AbbSum163
	common /dbarc_abbrev1hel/ AbbSum164, AbbSum165, AbbSum166
	common /dbarc_abbrev1hel/ AbbSum167, AbbSum168, AbbSum169
	common /dbarc_abbrev1hel/ AbbSum17, AbbSum170, AbbSum171
	common /dbarc_abbrev1hel/ AbbSum172, AbbSum173, AbbSum174
	common /dbarc_abbrev1hel/ AbbSum175, AbbSum176, AbbSum177
	common /dbarc_abbrev1hel/ AbbSum178, AbbSum179, AbbSum18
	common /dbarc_abbrev1hel/ AbbSum180, AbbSum181, AbbSum182
	common /dbarc_abbrev1hel/ AbbSum183, AbbSum184, AbbSum185
	common /dbarc_abbrev1hel/ AbbSum186, AbbSum187, AbbSum188
	common /dbarc_abbrev1hel/ AbbSum189, AbbSum19, AbbSum190
	common /dbarc_abbrev1hel/ AbbSum191, AbbSum192, AbbSum193
	common /dbarc_abbrev1hel/ AbbSum194, AbbSum195, AbbSum196
	common /dbarc_abbrev1hel/ AbbSum197, AbbSum198, AbbSum199
	common /dbarc_abbrev1hel/ AbbSum20, AbbSum200, AbbSum201
	common /dbarc_abbrev1hel/ AbbSum202, AbbSum203, AbbSum204
	common /dbarc_abbrev1hel/ AbbSum205, AbbSum206, AbbSum207
	common /dbarc_abbrev1hel/ AbbSum208, AbbSum209, AbbSum21
	common /dbarc_abbrev1hel/ AbbSum210, AbbSum22, AbbSum23, AbbSum24
	common /dbarc_abbrev1hel/ AbbSum25, AbbSum26, AbbSum27, AbbSum28
	common /dbarc_abbrev1hel/ AbbSum29, AbbSum30, AbbSum31, AbbSum32
	common /dbarc_abbrev1hel/ AbbSum33, AbbSum34, AbbSum35, AbbSum36
	common /dbarc_abbrev1hel/ AbbSum37, AbbSum38, AbbSum39, AbbSum40
	common /dbarc_abbrev1hel/ AbbSum41, AbbSum42, AbbSum43, AbbSum44
	common /dbarc_abbrev1hel/ AbbSum45, AbbSum46, AbbSum49, AbbSum50
	common /dbarc_abbrev1hel/ AbbSum51, AbbSum52, AbbSum53, AbbSum54
	common /dbarc_abbrev1hel/ AbbSum55, AbbSum56, AbbSum57, AbbSum58
	common /dbarc_abbrev1hel/ AbbSum59, AbbSum60, AbbSum61, AbbSum62
	common /dbarc_abbrev1hel/ AbbSum63, AbbSum64, AbbSum65, AbbSum66
	common /dbarc_abbrev1hel/ AbbSum67, AbbSum68, AbbSum69, AbbSum70
	common /dbarc_abbrev1hel/ AbbSum71, AbbSum73, AbbSum74, AbbSum75
	common /dbarc_abbrev1hel/ AbbSum76, AbbSum77, AbbSum78, AbbSum79
	common /dbarc_abbrev1hel/ AbbSum8, AbbSum80, AbbSum81, AbbSum82
	common /dbarc_abbrev1hel/ AbbSum83, AbbSum84, AbbSum85, AbbSum86
	common /dbarc_abbrev1hel/ AbbSum87, AbbSum88, AbbSum89, AbbSum9
	common /dbarc_abbrev1hel/ AbbSum90, AbbSum91, AbbSum92, AbbSum93
	common /dbarc_abbrev1hel/ AbbSum94, AbbSum95, AbbSum96, AbbSum97
	common /dbarc_abbrev1hel/ AbbSum98, AbbSum99, F7, F8, F9, Opt2
	common /dbarc_abbrev1hel/ Opt3, Sub112, Sub113, Sub114, Sub115
	common /dbarc_abbrev1hel/ Sub116, Sub117, Sub118, Sub119, Sub12
	common /dbarc_abbrev1hel/ Sub120, Sub121, Sub122, Sub123, Sub124
	common /dbarc_abbrev1hel/ Sub125, Sub126, Sub127, Sub128, Sub129
	common /dbarc_abbrev1hel/ Sub13, Sub130, Sub131, Sub132, Sub133
	common /dbarc_abbrev1hel/ Sub134, Sub135, Sub136, Sub137, Sub14
	common /dbarc_abbrev1hel/ Sub15, Sub16, Sub17, Sub18, Sub31, Sub32
	common /dbarc_abbrev1hel/ Sub36, Sub40, Sub44, Sub45, Sub47, Sub48
	common /dbarc_abbrev1hel/ Sub49, Sub50, Sub51, Sub53, Sub54, Sub55
	common /dbarc_abbrev1hel/ Sub56, Sub57, Sub58, Sub59, Sub60, Sub63
	common /dbarc_abbrev1hel/ Sub68, Sub69, Sub7, Sub70, Sub71, Sub72
	common /dbarc_abbrev1hel/ Sub73, Sub79, Sub80, Sub81, Sub82, Sub83
	common /dbarc_abbrev1hel/ Sub87, Sub88, Sub89, Sub90, Sub93, Sub94
	common /dbarc_abbrev1hel/ Sub100, Sub102, Sub103, Sub104, Sub105
	common /dbarc_abbrev1hel/ Sub106, Sub107, Sub108, Sub109, Sub110
	common /dbarc_abbrev1hel/ Sub111, Sub19, Sub20, Sub21, Sub22
	common /dbarc_abbrev1hel/ Sub23, Sub24, Sub25, Sub26, Sub27, Sub28
	common /dbarc_abbrev1hel/ Sub95, Sub96, Sub97, Sub98, Sub99

	ComplexType pave11(Ncc), pave12(Ncc), pave16(Ncc)
	ComplexType pave17(Nbb), pave2(Nbb), pave22(Ncc)
	ComplexType pave23(Ncc), pave4(Nbb), pave5(Nbb)
	common /dbarc_loopint1s/ pave11, pave12, pave16, pave17, pave2
	common /dbarc_loopint1s/ pave22, pave23, pave4, pave5

	ComplexType pave1(Nbb), pave10(Ncc), pave13(Ncc), pave14(Ncc)
	ComplexType pave15(Ncc), pave18(Ncc), pave19(Ncc)
	ComplexType pave20(Ndd), pave21(Ndd), pave24(Ndd)
	ComplexType pave25(Ndd), pave3(Nbb), pave6(Nbb), pave7(Nbb)
	ComplexType pave8(Ncc), pave9(Ncc)
	common /dbarc_loopint1angle/ pave1, pave10, pave13, pave14, pave15
	common /dbarc_loopint1angle/ pave18, pave19, pave20, pave21
	common /dbarc_loopint1angle/ pave24, pave25, pave3, pave6, pave7
	common /dbarc_loopint1angle/ pave8, pave9

	RealType S, T, T14, U, T24, S34
	common /kinvars/ S, T, T14, U, T24, S34

	integer seq(2), Hel(5)
	common /helvars/ seq, Hel

	integer Gen6, Ind1
	common /indices/ Gen6, Ind1

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /dbarc_formfactors/ Ctree, Cloop, MatSUN

#endif
