#if 0
* vars.h
* variable declarations
* generated by FormCalc 7.5 on 27-Mar-2015 20:08
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 5

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub10, Sub29, Sub30, Sub33, Sub34, Sub35, Sub39
	ComplexType Sub41, Sub42, Sub5, Sub52, Sub61, Sub62, Sub92
	ComplexType Sub101(3)
	common /sbaru_abbrev1s/ Sub10, Sub29, Sub30, Sub33, Sub34, Sub35
	common /sbaru_abbrev1s/ Sub39, Sub41, Sub42, Sub5, Sub52, Sub61
	common /sbaru_abbrev1s/ Sub62, Sub92, Sub101

	ComplexType Opt4, Opt5, Sub1, Sub2, Sub3, Sub4
	common /sbaru_abbrev0angle/ Opt4, Opt5, Sub1, Sub2, Sub3, Sub4

	ComplexType Sub11, Sub37, Sub38, Sub43, Sub46, Sub6, Sub64
	ComplexType Sub65, Sub66, Sub67, Sub74, Sub75, Sub76, Sub77
	ComplexType Sub78, Sub8, Sub84, Sub85, Sub86, Sub9, Sub91
	common /sbaru_abbrev1angle/ Sub11, Sub37, Sub38, Sub43, Sub46, Sub6
	common /sbaru_abbrev1angle/ Sub64, Sub65, Sub66, Sub67, Sub74
	common /sbaru_abbrev1angle/ Sub75, Sub76, Sub77, Sub78, Sub8
	common /sbaru_abbrev1angle/ Sub84, Sub85, Sub86, Sub9, Sub91

	ComplexType Abb1, Abb10, Abb2, Abb3, Abb4, Abb5, Abb6, Abb7
	ComplexType Abb8, Abb9, AbbSum1, AbbSum2, AbbSum3, AbbSum4
	ComplexType AbbSum47, AbbSum48, AbbSum5, AbbSum6, AbbSum7
	ComplexType AbbSum71, F1, F2, F3, F4, F5, F6, Opt1, Pair1
	ComplexType Pair2, Pair3, Pair4, Pair5, Pair6, Pair7, Pair8
	ComplexType Pair9
	common /sbaru_abbrev0hel/ Abb1, Abb10, Abb2, Abb3, Abb4, Abb5, Abb6
	common /sbaru_abbrev0hel/ Abb7, Abb8, Abb9, AbbSum1, AbbSum2
	common /sbaru_abbrev0hel/ AbbSum3, AbbSum4, AbbSum47, AbbSum48
	common /sbaru_abbrev0hel/ AbbSum5, AbbSum6, AbbSum7, AbbSum71, F1
	common /sbaru_abbrev0hel/ F2, F3, F4, F5, F6, Opt1, Pair1, Pair2
	common /sbaru_abbrev0hel/ Pair3, Pair4, Pair5, Pair6, Pair7, Pair8
	common /sbaru_abbrev0hel/ Pair9

	ComplexType Abb11, Abb12, Abb13, Abb14, Abb15, Abb16, Abb17
	ComplexType Abb18, Abb19, Abb20, Abb21, Abb22, Abb23, Abb24
	ComplexType Abb25, Abb26, Abb27, Abb28, Abb29, Abb30, Abb31
	ComplexType Abb32, Abb33, Abb34, Abb35, Abb36, Abb37
	ComplexType AbbSum10, AbbSum100, AbbSum101, AbbSum102
	ComplexType AbbSum103, AbbSum104, AbbSum105, AbbSum106
	ComplexType AbbSum107, AbbSum108, AbbSum109, AbbSum11
	ComplexType AbbSum110, AbbSum111, AbbSum112, AbbSum113
	ComplexType AbbSum114, AbbSum115, AbbSum116, AbbSum117
	ComplexType AbbSum118, AbbSum119, AbbSum12, AbbSum120
	ComplexType AbbSum121, AbbSum122, AbbSum123, AbbSum124
	ComplexType AbbSum125, AbbSum126, AbbSum127, AbbSum128
	ComplexType AbbSum129, AbbSum13, AbbSum130, AbbSum131
	ComplexType AbbSum132, AbbSum133, AbbSum134, AbbSum135
	ComplexType AbbSum136, AbbSum137, AbbSum138, AbbSum139
	ComplexType AbbSum14, AbbSum140, AbbSum141, AbbSum142
	ComplexType AbbSum143, AbbSum144, AbbSum145, AbbSum146
	ComplexType AbbSum147, AbbSum148, AbbSum149, AbbSum15
	ComplexType AbbSum150, AbbSum151, AbbSum152, AbbSum153
	ComplexType AbbSum154, AbbSum155, AbbSum156, AbbSum157
	ComplexType AbbSum158, AbbSum159, AbbSum16, AbbSum160
	ComplexType AbbSum161, AbbSum162, AbbSum163, AbbSum164
	ComplexType AbbSum165, AbbSum166, AbbSum167, AbbSum168
	ComplexType AbbSum169, AbbSum17, AbbSum170, AbbSum171
	ComplexType AbbSum172, AbbSum173, AbbSum174, AbbSum175
	ComplexType AbbSum176, AbbSum177, AbbSum178, AbbSum179
	ComplexType AbbSum18, AbbSum180, AbbSum181, AbbSum182
	ComplexType AbbSum183, AbbSum184, AbbSum185, AbbSum186
	ComplexType AbbSum187, AbbSum188, AbbSum189, AbbSum19
	ComplexType AbbSum190, AbbSum191, AbbSum192, AbbSum193
	ComplexType AbbSum194, AbbSum195, AbbSum196, AbbSum197
	ComplexType AbbSum198, AbbSum199, AbbSum20, AbbSum200
	ComplexType AbbSum201, AbbSum202, AbbSum203, AbbSum204
	ComplexType AbbSum205, AbbSum206, AbbSum207, AbbSum208
	ComplexType AbbSum209, AbbSum21, AbbSum210, AbbSum211
	ComplexType AbbSum22, AbbSum23, AbbSum24, AbbSum25, AbbSum26
	ComplexType AbbSum27, AbbSum28, AbbSum29, AbbSum30, AbbSum31
	ComplexType AbbSum32, AbbSum33, AbbSum34, AbbSum35, AbbSum36
	ComplexType AbbSum37, AbbSum38, AbbSum39, AbbSum40, AbbSum41
	ComplexType AbbSum42, AbbSum43, AbbSum44, AbbSum45, AbbSum46
	ComplexType AbbSum49, AbbSum50, AbbSum51, AbbSum52, AbbSum53
	ComplexType AbbSum54, AbbSum55, AbbSum56, AbbSum57, AbbSum58
	ComplexType AbbSum59, AbbSum60, AbbSum61, AbbSum62, AbbSum63
	ComplexType AbbSum64, AbbSum65, AbbSum66, AbbSum67, AbbSum68
	ComplexType AbbSum69, AbbSum70, AbbSum72, AbbSum73, AbbSum74
	ComplexType AbbSum75, AbbSum76, AbbSum77, AbbSum78, AbbSum79
	ComplexType AbbSum8, AbbSum80, AbbSum81, AbbSum82, AbbSum83
	ComplexType AbbSum84, AbbSum85, AbbSum86, AbbSum87, AbbSum88
	ComplexType AbbSum89, AbbSum9, AbbSum90, AbbSum91, AbbSum92
	ComplexType AbbSum93, AbbSum94, AbbSum95, AbbSum96, AbbSum97
	ComplexType AbbSum98, AbbSum99, F7, F8, F9, Opt2, Opt3
	ComplexType Sub112, Sub113, Sub114, Sub115, Sub116, Sub117
	ComplexType Sub118, Sub119, Sub12, Sub120, Sub121, Sub122
	ComplexType Sub123, Sub124, Sub125, Sub126, Sub127, Sub128
	ComplexType Sub129, Sub13, Sub130, Sub131, Sub132, Sub133
	ComplexType Sub134, Sub135, Sub136, Sub137, Sub14, Sub15
	ComplexType Sub16, Sub17, Sub18, Sub31, Sub32, Sub36, Sub40
	ComplexType Sub44, Sub45, Sub47, Sub48, Sub49, Sub50, Sub51
	ComplexType Sub53, Sub54, Sub55, Sub56, Sub57, Sub58, Sub59
	ComplexType Sub60, Sub63, Sub68, Sub69, Sub7, Sub70, Sub71
	ComplexType Sub72, Sub73, Sub79, Sub80, Sub81, Sub82, Sub83
	ComplexType Sub87, Sub88, Sub89, Sub90, Sub93, Sub94
	ComplexType Sub100(3), Sub102(3), Sub103(3), Sub104(3)
	ComplexType Sub105(3), Sub106(3), Sub107(3), Sub108(3)
	ComplexType Sub109(3), Sub110(3), Sub111(3), Sub19(3)
	ComplexType Sub20(3), Sub21(3), Sub22(3), Sub23(3), Sub24(3)
	ComplexType Sub25(3), Sub26(3), Sub27(3), Sub28(3), Sub95(3)
	ComplexType Sub96(3), Sub97(3), Sub98(3), Sub99(3)
	common /sbaru_abbrev1hel/ Abb11, Abb12, Abb13, Abb14, Abb15, Abb16
	common /sbaru_abbrev1hel/ Abb17, Abb18, Abb19, Abb20, Abb21, Abb22
	common /sbaru_abbrev1hel/ Abb23, Abb24, Abb25, Abb26, Abb27, Abb28
	common /sbaru_abbrev1hel/ Abb29, Abb30, Abb31, Abb32, Abb33, Abb34
	common /sbaru_abbrev1hel/ Abb35, Abb36, Abb37, AbbSum10, AbbSum100
	common /sbaru_abbrev1hel/ AbbSum101, AbbSum102, AbbSum103
	common /sbaru_abbrev1hel/ AbbSum104, AbbSum105, AbbSum106
	common /sbaru_abbrev1hel/ AbbSum107, AbbSum108, AbbSum109
	common /sbaru_abbrev1hel/ AbbSum11, AbbSum110, AbbSum111
	common /sbaru_abbrev1hel/ AbbSum112, AbbSum113, AbbSum114
	common /sbaru_abbrev1hel/ AbbSum115, AbbSum116, AbbSum117
	common /sbaru_abbrev1hel/ AbbSum118, AbbSum119, AbbSum12
	common /sbaru_abbrev1hel/ AbbSum120, AbbSum121, AbbSum122
	common /sbaru_abbrev1hel/ AbbSum123, AbbSum124, AbbSum125
	common /sbaru_abbrev1hel/ AbbSum126, AbbSum127, AbbSum128
	common /sbaru_abbrev1hel/ AbbSum129, AbbSum13, AbbSum130
	common /sbaru_abbrev1hel/ AbbSum131, AbbSum132, AbbSum133
	common /sbaru_abbrev1hel/ AbbSum134, AbbSum135, AbbSum136
	common /sbaru_abbrev1hel/ AbbSum137, AbbSum138, AbbSum139
	common /sbaru_abbrev1hel/ AbbSum14, AbbSum140, AbbSum141
	common /sbaru_abbrev1hel/ AbbSum142, AbbSum143, AbbSum144
	common /sbaru_abbrev1hel/ AbbSum145, AbbSum146, AbbSum147
	common /sbaru_abbrev1hel/ AbbSum148, AbbSum149, AbbSum15
	common /sbaru_abbrev1hel/ AbbSum150, AbbSum151, AbbSum152
	common /sbaru_abbrev1hel/ AbbSum153, AbbSum154, AbbSum155
	common /sbaru_abbrev1hel/ AbbSum156, AbbSum157, AbbSum158
	common /sbaru_abbrev1hel/ AbbSum159, AbbSum16, AbbSum160
	common /sbaru_abbrev1hel/ AbbSum161, AbbSum162, AbbSum163
	common /sbaru_abbrev1hel/ AbbSum164, AbbSum165, AbbSum166
	common /sbaru_abbrev1hel/ AbbSum167, AbbSum168, AbbSum169
	common /sbaru_abbrev1hel/ AbbSum17, AbbSum170, AbbSum171
	common /sbaru_abbrev1hel/ AbbSum172, AbbSum173, AbbSum174
	common /sbaru_abbrev1hel/ AbbSum175, AbbSum176, AbbSum177
	common /sbaru_abbrev1hel/ AbbSum178, AbbSum179, AbbSum18
	common /sbaru_abbrev1hel/ AbbSum180, AbbSum181, AbbSum182
	common /sbaru_abbrev1hel/ AbbSum183, AbbSum184, AbbSum185
	common /sbaru_abbrev1hel/ AbbSum186, AbbSum187, AbbSum188
	common /sbaru_abbrev1hel/ AbbSum189, AbbSum19, AbbSum190
	common /sbaru_abbrev1hel/ AbbSum191, AbbSum192, AbbSum193
	common /sbaru_abbrev1hel/ AbbSum194, AbbSum195, AbbSum196
	common /sbaru_abbrev1hel/ AbbSum197, AbbSum198, AbbSum199
	common /sbaru_abbrev1hel/ AbbSum20, AbbSum200, AbbSum201
	common /sbaru_abbrev1hel/ AbbSum202, AbbSum203, AbbSum204
	common /sbaru_abbrev1hel/ AbbSum205, AbbSum206, AbbSum207
	common /sbaru_abbrev1hel/ AbbSum208, AbbSum209, AbbSum21
	common /sbaru_abbrev1hel/ AbbSum210, AbbSum211, AbbSum22, AbbSum23
	common /sbaru_abbrev1hel/ AbbSum24, AbbSum25, AbbSum26, AbbSum27
	common /sbaru_abbrev1hel/ AbbSum28, AbbSum29, AbbSum30, AbbSum31
	common /sbaru_abbrev1hel/ AbbSum32, AbbSum33, AbbSum34, AbbSum35
	common /sbaru_abbrev1hel/ AbbSum36, AbbSum37, AbbSum38, AbbSum39
	common /sbaru_abbrev1hel/ AbbSum40, AbbSum41, AbbSum42, AbbSum43
	common /sbaru_abbrev1hel/ AbbSum44, AbbSum45, AbbSum46, AbbSum49
	common /sbaru_abbrev1hel/ AbbSum50, AbbSum51, AbbSum52, AbbSum53
	common /sbaru_abbrev1hel/ AbbSum54, AbbSum55, AbbSum56, AbbSum57
	common /sbaru_abbrev1hel/ AbbSum58, AbbSum59, AbbSum60, AbbSum61
	common /sbaru_abbrev1hel/ AbbSum62, AbbSum63, AbbSum64, AbbSum65
	common /sbaru_abbrev1hel/ AbbSum66, AbbSum67, AbbSum68, AbbSum69
	common /sbaru_abbrev1hel/ AbbSum70, AbbSum72, AbbSum73, AbbSum74
	common /sbaru_abbrev1hel/ AbbSum75, AbbSum76, AbbSum77, AbbSum78
	common /sbaru_abbrev1hel/ AbbSum79, AbbSum8, AbbSum80, AbbSum81
	common /sbaru_abbrev1hel/ AbbSum82, AbbSum83, AbbSum84, AbbSum85
	common /sbaru_abbrev1hel/ AbbSum86, AbbSum87, AbbSum88, AbbSum89
	common /sbaru_abbrev1hel/ AbbSum9, AbbSum90, AbbSum91, AbbSum92
	common /sbaru_abbrev1hel/ AbbSum93, AbbSum94, AbbSum95, AbbSum96
	common /sbaru_abbrev1hel/ AbbSum97, AbbSum98, AbbSum99, F7, F8, F9
	common /sbaru_abbrev1hel/ Opt2, Opt3, Sub112, Sub113, Sub114
	common /sbaru_abbrev1hel/ Sub115, Sub116, Sub117, Sub118, Sub119
	common /sbaru_abbrev1hel/ Sub12, Sub120, Sub121, Sub122, Sub123
	common /sbaru_abbrev1hel/ Sub124, Sub125, Sub126, Sub127, Sub128
	common /sbaru_abbrev1hel/ Sub129, Sub13, Sub130, Sub131, Sub132
	common /sbaru_abbrev1hel/ Sub133, Sub134, Sub135, Sub136, Sub137
	common /sbaru_abbrev1hel/ Sub14, Sub15, Sub16, Sub17, Sub18, Sub31
	common /sbaru_abbrev1hel/ Sub32, Sub36, Sub40, Sub44, Sub45, Sub47
	common /sbaru_abbrev1hel/ Sub48, Sub49, Sub50, Sub51, Sub53, Sub54
	common /sbaru_abbrev1hel/ Sub55, Sub56, Sub57, Sub58, Sub59, Sub60
	common /sbaru_abbrev1hel/ Sub63, Sub68, Sub69, Sub7, Sub70, Sub71
	common /sbaru_abbrev1hel/ Sub72, Sub73, Sub79, Sub80, Sub81, Sub82
	common /sbaru_abbrev1hel/ Sub83, Sub87, Sub88, Sub89, Sub90, Sub93
	common /sbaru_abbrev1hel/ Sub94, Sub100, Sub102, Sub103, Sub104
	common /sbaru_abbrev1hel/ Sub105, Sub106, Sub107, Sub108, Sub109
	common /sbaru_abbrev1hel/ Sub110, Sub111, Sub19, Sub20, Sub21
	common /sbaru_abbrev1hel/ Sub22, Sub23, Sub24, Sub25, Sub26, Sub27
	common /sbaru_abbrev1hel/ Sub28, Sub95, Sub96, Sub97, Sub98, Sub99

	ComplexType pave10(Ncc), pave12(Ncc), pave16(Ncc)
	ComplexType pave17(Nbb), pave18(Ncc), pave19(Ncc)
	ComplexType pave2(Nbb), pave4(Nbb), pave5(Nbb)
	common /sbaru_loopint1s/ pave10, pave12, pave16, pave17, pave18
	common /sbaru_loopint1s/ pave19, pave2, pave4, pave5

	ComplexType pave1(Nbb), pave11(Ncc), pave13(Ncc), pave14(Ncc)
	ComplexType pave15(Ncc), pave20(Ndd), pave21(Ndd)
	ComplexType pave22(Ncc), pave23(Ncc), pave24(Ndd)
	ComplexType pave25(Ndd), pave3(Nbb), pave6(Nbb), pave7(Nbb)
	ComplexType pave8(Ncc), pave9(Ncc)
	common /sbaru_loopint1angle/ pave1, pave11, pave13, pave14, pave15
	common /sbaru_loopint1angle/ pave20, pave21, pave22, pave23
	common /sbaru_loopint1angle/ pave24, pave25, pave3, pave6, pave7
	common /sbaru_loopint1angle/ pave8, pave9

	RealType S, T, T14, U, T24, S34
	common /kinvars/ S, T, T14, U, T24, S34

	integer seq(2), Hel(5)
	common /helvars/ seq, Hel

	integer Gen6, Ind1
	common /indices/ Gen6, Ind1

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /sbaru_formfactors/ Ctree, Cloop, MatSUN

#endif
