#if 0
* specs.h
* process specifications
* generated by FormCalc 8.4 on 9-Sep-2016 18:40
#endif

#define TYPE1 PHOTON
#define ANTI1 1
#define MASS1 0

#define TYPE2 PHOTON
#define ANTI2 1
#define MASS2 0

#define TYPE3 SCALAR
#define ANTI3 1
#define MASS3 MH

#define TYPE4 VECTOR
#define ANTI4 1
#define MASS4 MZ

#define TYPE5 VECTOR
#define ANTI5 1
#define MASS5 MZ

#define LEGS_IN 2
#define LEGS_OUT 3
#define LEGS 5

#define KIN "2to3.F"
