#if 0
* renconst.h
* RC declarations
* generated by FormCalc 7.5 on 9-Mar-2015 10:26
#endif

	ComplexType dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1, dZZA1
	ComplexType dZZZ1, dMf1(4,1), dZfL1(4,1,1), dZfR1(4,1,1)
	common /renconst/ dMWsq1, dMZsq1, dSW1, dZAA1, dZAZ1, dZe1
	common /renconst/ dZZA1, dZZZ1, dMf1, dZfL1, dZfR1


