* LLgg_vars.h
* variable declarations
* generated by FormCalc 6.1 24 Sep 2013 14:22

#include "decl.h"
#include "sqantisq_renconst.h" 
	double precision S, T, U
	common /LLgg_kinvars/ S, T, U

	integer Hel(4)
	common /LLgg_kinvars/ Hel

	double complex Pair55, Pair56, Pair58, Pair65, Pair59, Pair57
	double complex Pair63, Eps121, Eps130, Eps123, Eps126, Eps128
	double complex Eps188, Eps183, Eps144, Eps457, Eps132, Eps153
	double complex Eps145, Eps458, Eps133, Abb218, Abb146, Abb204
	double complex Abb288, Abb184, Abb459, Abb60, Abb134, Abb154
	double complex Abb73, Abb328, Abb190, Abb85, Abb61, Abb135
	double complex Abb147, Abb69, Abb64, Abb219, Abb148, Abb460
	double complex Abb66, Abb70, Abb79, AbbSum136, AbbSum209
	double complex AbbSum149, AbbSum162, AbbSum177, AbbSum174
	double complex AbbSum229, AbbSum433, AbbSum185, AbbSum191
	double complex AbbSum343, AbbSum357, AbbSum205, AbbSum418
	double complex AbbSum319, AbbSum301, AbbSum424, AbbSum307
	double complex AbbSum296, AbbSum220, AbbSum289, AbbSum329
	double complex AbbSum461, AbbSum267, AbbSum268, AbbSum62
	double complex AbbSum118, AbbSum477, AbbSum478, AbbSum404
	double complex AbbSum506, AbbSum468, AbbSum274, AbbSum405
	double complex AbbSum125, AbbSum500, AbbSum88, AbbSum255
	double complex AbbSum257, AbbSum256, AbbSum252, AbbSum279
	double complex AbbSum280, AbbSum384, AbbSum383, AbbSum454
	double complex AbbSum72, AbbSum71, AbbSum380, AbbSum212
	double complex AbbSum486, AbbSum196, AbbSum382, AbbSum398
	double complex AbbSum373, AbbSum248, AbbSum308, AbbSum321
	double complex AbbSum169, AbbSum503, AbbSum475, AbbSum112
	double complex AbbSum106, AbbSum111, AbbSum105, AbbSum495
	double complex AbbSum247, AbbSum372, AbbSum422, AbbSum95
	double complex AbbSum90, AbbSum505, AbbSum476, AbbSum364
	double complex AbbSum242, AbbSum302, AbbSum483, AbbSum235
	double complex AbbSum365, AbbSum243, AbbSum291, AbbSum138
	double complex AbbSum74, AbbSum75, AbbSum77, AbbSum76
	double complex AbbSum78, AbbSum339, AbbSum453, AbbSum389
	double complex AbbSum391, AbbSum275, AbbSum390, AbbSum276
	double complex AbbSum344, AbbSum377, AbbSum479, AbbSum480
	double complex AbbSum481, AbbSum490, AbbSum273, AbbSum472
	double complex AbbSum466, AbbSum491, AbbSum482, AbbSum157
	double complex AbbSum165, AbbSum474, AbbSum120, AbbSum473
	double complex AbbSum152, AbbSum223, AbbSum282, AbbSum309
	double complex AbbSum368, AbbSum406, AbbSum360, AbbSum361
	double complex AbbSum502, AbbSum465, AbbSum119, AbbSum186
	double complex AbbSum366, AbbSum501, AbbSum240, AbbSum507
	double complex AbbSum467, AbbSum113, AbbSum107, AbbSum181
	double complex AbbSum379, AbbSum504, AbbSum245, AbbSum376
	double complex AbbSum238, AbbSum163, AbbSum176, AbbSum314
	double complex AbbSum178, AbbSum115, AbbSum109, AbbSum114
	double complex AbbSum244, AbbSum108, AbbSum375, AbbSum236
	double complex AbbSum370, AbbSum155, AbbSum362, AbbSum237
	double complex AbbSum371, AbbSum233, AbbSum311, AbbSum156
	double complex AbbSum80, AbbSum81, AbbSum83, AbbSum82
	double complex AbbSum84, AbbSum363, AbbSum202, AbbSum96
	double complex AbbSum271, AbbSum396, AbbSum87, AbbSum234
	double complex AbbSum283, AbbSum303, AbbSum264, AbbSum241
	double complex AbbSum266, AbbSum400, AbbSum265, AbbSum401
	double complex AbbSum166, AbbSum210, AbbSum249, AbbSum117
	double complex AbbSum399, AbbSum397, AbbSum94, AbbSum93
	double complex AbbSum164, AbbSum281, AbbSum374, AbbSum367
	double complex AbbSum408, AbbSum352, AbbSum369, AbbSum98
	double complex AbbSum102, AbbSum231, AbbSum116, AbbSum324
	double complex AbbSum110, AbbSum92, AbbSum246, AbbSum310
	double complex AbbSum239, AbbSum407, AbbSum251, AbbSum272
	double complex AbbSum100, AbbSum385, AbbSum342, AbbSum262
	double complex AbbSum207, AbbSum494, AbbSum103, AbbSum395
	double complex AbbSum101, AbbSum89, AbbSum260, AbbSum378
	double complex AbbSum206, AbbSum250, AbbSum258, AbbSum261
	double complex AbbSum387, AbbSum341, AbbSum386, AbbSum259
	double complex AbbSum86, AbbSum99, AbbSum97, AbbSum208
	double complex AbbSum91, AbbSum497, AbbSum393, AbbSum392
	double complex AbbSum253, AbbSum493, AbbSum499, AbbSum484
	double complex AbbSum489, AbbSum470, AbbSum496, AbbSum498
	double complex AbbSum488, AbbSum485, AbbSum471, AbbSum464
	double complex AbbSum278, AbbSum359, AbbSum469, AbbSum403
	double complex AbbSum388, AbbSum232, AbbSum463, AbbSum254
	double complex AbbSum492, AbbSum381, AbbSum277, AbbSum402
	double complex AbbSum297, AbbSum304, AbbSum270, AbbSum211
	double complex AbbSum263, AbbSum487, AbbSum269, AbbSum394
	double complex AbbSum158, AbbSum222, AbbSum410, AbbSum440
	double complex AbbSum221, AbbSum203, AbbSum122, AbbSum417
	double complex AbbSum351, AbbSum340, AbbSum350, AbbSum284
	double complex AbbSum213, AbbSum447, AbbSum446, AbbSum409
	double complex AbbSum412, AbbSum332, AbbSum124, AbbSum197
	double complex AbbSum172, AbbSum353, AbbSum306, AbbSum168
	double complex AbbSum167, AbbSum187, AbbSum201, AbbSum300
	double complex AbbSum299, AbbSum420, AbbSum315, AbbSum151
	double complex AbbSum230, AbbSum150, AbbSum354, AbbSum292
	double complex AbbSum179, AbbSum355, AbbSum356, AbbSum287
	double complex AbbSum462, AbbSum320, AbbSum419, AbbSum451
	double complex AbbSum416, AbbSum193, AbbSum127, AbbSum450
	double complex AbbSum182, AbbSum439, AbbSum192, AbbSum298
	double complex AbbSum421, AbbSum295, AbbSum294, AbbSum305
	double complex AbbSum180, AbbSum159, AbbSum323, AbbSum216
	double complex AbbSum346, AbbSum348, AbbSum331, AbbSum286
	double complex AbbSum325, AbbSum330, AbbSum171, AbbSum335
	double complex AbbSum349, AbbSum175, AbbSum226, AbbSum228
	double complex AbbSum129, AbbSum173, AbbSum141, AbbSum322
	double complex AbbSum338, AbbSum161, AbbSum170, AbbSum214
	double complex AbbSum217, AbbSum326, AbbSum160, AbbSum313
	double complex AbbSum312, AbbSum347, AbbSum215, AbbSum316
	double complex AbbSum427, AbbSum414, AbbSum224, AbbSum437
	double complex AbbSum411, AbbSum195, AbbSum198, AbbSum200
	double complex AbbSum137, AbbSum131, AbbSum337, AbbSum290
	double complex AbbSum194, AbbSum432, AbbSum285, AbbSum334
	double complex AbbSum429, AbbSum431, AbbSum434, AbbSum333
	double complex AbbSum435, AbbSum445, AbbSum318, AbbSum425
	double complex AbbSum448, AbbSum140, AbbSum345, AbbSum428
	double complex AbbSum423, AbbSum336, AbbSum199, AbbSum358
	double complex AbbSum139, AbbSum293, AbbSum449, AbbSum317
	double complex AbbSum452, AbbSum225, AbbSum143, AbbSum142
	double complex AbbSum430, AbbSum415, AbbSum442, AbbSum441
	double complex AbbSum436, AbbSum327, AbbSum438, AbbSum189
	double complex AbbSum443, AbbSum455, AbbSum413, AbbSum456
	double complex AbbSum426, AbbSum227, AbbSum444
	common /LLgg_abbrev/ Pair55, Pair56, Pair58, Pair65, Pair59
	common /LLgg_abbrev/ Pair57, Pair63, Eps121, Eps130, Eps123
	common /LLgg_abbrev/ Eps126, Eps128, Eps188, Eps183, Eps144
	common /LLgg_abbrev/ Eps457, Eps132, Eps153, Eps145, Eps458
	common /LLgg_abbrev/ Eps133, Abb218, Abb146, Abb204, Abb288
	common /LLgg_abbrev/ Abb184, Abb459, Abb60, Abb134, Abb154
	common /LLgg_abbrev/ Abb73, Abb328, Abb190, Abb85, Abb61
	common /LLgg_abbrev/ Abb135, Abb147, Abb69, Abb64, Abb219
	common /LLgg_abbrev/ Abb148, Abb460, Abb66, Abb70, Abb79
	common /LLgg_abbrev/ AbbSum136, AbbSum209, AbbSum149
	common /LLgg_abbrev/ AbbSum162, AbbSum177, AbbSum174
	common /LLgg_abbrev/ AbbSum229, AbbSum433, AbbSum185
	common /LLgg_abbrev/ AbbSum191, AbbSum343, AbbSum357
	common /LLgg_abbrev/ AbbSum205, AbbSum418, AbbSum319
	common /LLgg_abbrev/ AbbSum301, AbbSum424, AbbSum307
	common /LLgg_abbrev/ AbbSum296, AbbSum220, AbbSum289
	common /LLgg_abbrev/ AbbSum329, AbbSum461, AbbSum267
	common /LLgg_abbrev/ AbbSum268, AbbSum62, AbbSum118, AbbSum477
	common /LLgg_abbrev/ AbbSum478, AbbSum404, AbbSum506
	common /LLgg_abbrev/ AbbSum468, AbbSum274, AbbSum405
	common /LLgg_abbrev/ AbbSum125, AbbSum500, AbbSum88, AbbSum255
	common /LLgg_abbrev/ AbbSum257, AbbSum256, AbbSum252
	common /LLgg_abbrev/ AbbSum279, AbbSum280, AbbSum384
	common /LLgg_abbrev/ AbbSum383, AbbSum454, AbbSum72, AbbSum71
	common /LLgg_abbrev/ AbbSum380, AbbSum212, AbbSum486
	common /LLgg_abbrev/ AbbSum196, AbbSum382, AbbSum398
	common /LLgg_abbrev/ AbbSum373, AbbSum248, AbbSum308
	common /LLgg_abbrev/ AbbSum321, AbbSum169, AbbSum503
	common /LLgg_abbrev/ AbbSum475, AbbSum112, AbbSum106
	common /LLgg_abbrev/ AbbSum111, AbbSum105, AbbSum495
	common /LLgg_abbrev/ AbbSum247, AbbSum372, AbbSum422, AbbSum95
	common /LLgg_abbrev/ AbbSum90, AbbSum505, AbbSum476, AbbSum364
	common /LLgg_abbrev/ AbbSum242, AbbSum302, AbbSum483
	common /LLgg_abbrev/ AbbSum235, AbbSum365, AbbSum243
	common /LLgg_abbrev/ AbbSum291, AbbSum138, AbbSum74, AbbSum75
	common /LLgg_abbrev/ AbbSum77, AbbSum76, AbbSum78, AbbSum339
	common /LLgg_abbrev/ AbbSum453, AbbSum389, AbbSum391
	common /LLgg_abbrev/ AbbSum275, AbbSum390, AbbSum276
	common /LLgg_abbrev/ AbbSum344, AbbSum377, AbbSum479
	common /LLgg_abbrev/ AbbSum480, AbbSum481, AbbSum490
	common /LLgg_abbrev/ AbbSum273, AbbSum472, AbbSum466
	common /LLgg_abbrev/ AbbSum491, AbbSum482, AbbSum157
	common /LLgg_abbrev/ AbbSum165, AbbSum474, AbbSum120
	common /LLgg_abbrev/ AbbSum473, AbbSum152, AbbSum223
	common /LLgg_abbrev/ AbbSum282, AbbSum309, AbbSum368
	common /LLgg_abbrev/ AbbSum406, AbbSum360, AbbSum361
	common /LLgg_abbrev/ AbbSum502, AbbSum465, AbbSum119
	common /LLgg_abbrev/ AbbSum186, AbbSum366, AbbSum501
	common /LLgg_abbrev/ AbbSum240, AbbSum507, AbbSum467
	common /LLgg_abbrev/ AbbSum113, AbbSum107, AbbSum181
	common /LLgg_abbrev/ AbbSum379, AbbSum504, AbbSum245
	common /LLgg_abbrev/ AbbSum376, AbbSum238, AbbSum163
	common /LLgg_abbrev/ AbbSum176, AbbSum314, AbbSum178
	common /LLgg_abbrev/ AbbSum115, AbbSum109, AbbSum114
	common /LLgg_abbrev/ AbbSum244, AbbSum108, AbbSum375
	common /LLgg_abbrev/ AbbSum236, AbbSum370, AbbSum155
	common /LLgg_abbrev/ AbbSum362, AbbSum237, AbbSum371
	common /LLgg_abbrev/ AbbSum233, AbbSum311, AbbSum156, AbbSum80
	common /LLgg_abbrev/ AbbSum81, AbbSum83, AbbSum82, AbbSum84
	common /LLgg_abbrev/ AbbSum363, AbbSum202, AbbSum96, AbbSum271
	common /LLgg_abbrev/ AbbSum396, AbbSum87, AbbSum234, AbbSum283
	common /LLgg_abbrev/ AbbSum303, AbbSum264, AbbSum241
	common /LLgg_abbrev/ AbbSum266, AbbSum400, AbbSum265
	common /LLgg_abbrev/ AbbSum401, AbbSum166, AbbSum210
	common /LLgg_abbrev/ AbbSum249, AbbSum117, AbbSum399
	common /LLgg_abbrev/ AbbSum397, AbbSum94, AbbSum93, AbbSum164
	common /LLgg_abbrev/ AbbSum281, AbbSum374, AbbSum367
	common /LLgg_abbrev/ AbbSum408, AbbSum352, AbbSum369, AbbSum98
	common /LLgg_abbrev/ AbbSum102, AbbSum231, AbbSum116
	common /LLgg_abbrev/ AbbSum324, AbbSum110, AbbSum92, AbbSum246
	common /LLgg_abbrev/ AbbSum310, AbbSum239, AbbSum407
	common /LLgg_abbrev/ AbbSum251, AbbSum272, AbbSum100
	common /LLgg_abbrev/ AbbSum385, AbbSum342, AbbSum262
	common /LLgg_abbrev/ AbbSum207, AbbSum494, AbbSum103
	common /LLgg_abbrev/ AbbSum395, AbbSum101, AbbSum89, AbbSum260
	common /LLgg_abbrev/ AbbSum378, AbbSum206, AbbSum250
	common /LLgg_abbrev/ AbbSum258, AbbSum261, AbbSum387
	common /LLgg_abbrev/ AbbSum341, AbbSum386, AbbSum259, AbbSum86
	common /LLgg_abbrev/ AbbSum99, AbbSum97, AbbSum208, AbbSum91
	common /LLgg_abbrev/ AbbSum497, AbbSum393, AbbSum392
	common /LLgg_abbrev/ AbbSum253, AbbSum493, AbbSum499
	common /LLgg_abbrev/ AbbSum484, AbbSum489, AbbSum470
	common /LLgg_abbrev/ AbbSum496, AbbSum498, AbbSum488
	common /LLgg_abbrev/ AbbSum485, AbbSum471, AbbSum464
	common /LLgg_abbrev/ AbbSum278, AbbSum359, AbbSum469
	common /LLgg_abbrev/ AbbSum403, AbbSum388, AbbSum232
	common /LLgg_abbrev/ AbbSum463, AbbSum254, AbbSum492
	common /LLgg_abbrev/ AbbSum381, AbbSum277, AbbSum402
	common /LLgg_abbrev/ AbbSum297, AbbSum304, AbbSum270
	common /LLgg_abbrev/ AbbSum211, AbbSum263, AbbSum487
	common /LLgg_abbrev/ AbbSum269, AbbSum394, AbbSum158
	common /LLgg_abbrev/ AbbSum222, AbbSum410, AbbSum440
	common /LLgg_abbrev/ AbbSum221, AbbSum203, AbbSum122
	common /LLgg_abbrev/ AbbSum417, AbbSum351, AbbSum340
	common /LLgg_abbrev/ AbbSum350, AbbSum284, AbbSum213
	common /LLgg_abbrev/ AbbSum447, AbbSum446, AbbSum409
	common /LLgg_abbrev/ AbbSum412, AbbSum332, AbbSum124
	common /LLgg_abbrev/ AbbSum197, AbbSum172, AbbSum353
	common /LLgg_abbrev/ AbbSum306, AbbSum168, AbbSum167
	common /LLgg_abbrev/ AbbSum187, AbbSum201, AbbSum300
	common /LLgg_abbrev/ AbbSum299, AbbSum420, AbbSum315
	common /LLgg_abbrev/ AbbSum151, AbbSum230, AbbSum150
	common /LLgg_abbrev/ AbbSum354, AbbSum292, AbbSum179
	common /LLgg_abbrev/ AbbSum355, AbbSum356, AbbSum287
	common /LLgg_abbrev/ AbbSum462, AbbSum320, AbbSum419
	common /LLgg_abbrev/ AbbSum451, AbbSum416, AbbSum193
	common /LLgg_abbrev/ AbbSum127, AbbSum450, AbbSum182
	common /LLgg_abbrev/ AbbSum439, AbbSum192, AbbSum298
	common /LLgg_abbrev/ AbbSum421, AbbSum295, AbbSum294
	common /LLgg_abbrev/ AbbSum305, AbbSum180, AbbSum159
	common /LLgg_abbrev/ AbbSum323, AbbSum216, AbbSum346
	common /LLgg_abbrev/ AbbSum348, AbbSum331, AbbSum286
	common /LLgg_abbrev/ AbbSum325, AbbSum330, AbbSum171
	common /LLgg_abbrev/ AbbSum335, AbbSum349, AbbSum175
	common /LLgg_abbrev/ AbbSum226, AbbSum228, AbbSum129
	common /LLgg_abbrev/ AbbSum173, AbbSum141, AbbSum322
	common /LLgg_abbrev/ AbbSum338, AbbSum161, AbbSum170
	common /LLgg_abbrev/ AbbSum214, AbbSum217, AbbSum326
	common /LLgg_abbrev/ AbbSum160, AbbSum313, AbbSum312
	common /LLgg_abbrev/ AbbSum347, AbbSum215, AbbSum316
	common /LLgg_abbrev/ AbbSum427, AbbSum414, AbbSum224
	common /LLgg_abbrev/ AbbSum437, AbbSum411, AbbSum195
	common /LLgg_abbrev/ AbbSum198, AbbSum200, AbbSum137
	common /LLgg_abbrev/ AbbSum131, AbbSum337, AbbSum290
	common /LLgg_abbrev/ AbbSum194, AbbSum432, AbbSum285
	common /LLgg_abbrev/ AbbSum334, AbbSum429, AbbSum431
	common /LLgg_abbrev/ AbbSum434, AbbSum333, AbbSum435
	common /LLgg_abbrev/ AbbSum445, AbbSum318, AbbSum425
	common /LLgg_abbrev/ AbbSum448, AbbSum140, AbbSum345
	common /LLgg_abbrev/ AbbSum428, AbbSum423, AbbSum336
	common /LLgg_abbrev/ AbbSum199, AbbSum358, AbbSum139
	common /LLgg_abbrev/ AbbSum293, AbbSum449, AbbSum317
	common /LLgg_abbrev/ AbbSum452, AbbSum225, AbbSum143
	common /LLgg_abbrev/ AbbSum142, AbbSum430, AbbSum415
	common /LLgg_abbrev/ AbbSum442, AbbSum441, AbbSum436
	common /LLgg_abbrev/ AbbSum327, AbbSum438, AbbSum189
	common /LLgg_abbrev/ AbbSum443, AbbSum455, AbbSum413
	common /LLgg_abbrev/ AbbSum456, AbbSum426, AbbSum227
	common /LLgg_abbrev/ AbbSum444

	double complex cint1, cint2, cint3, cint4, cint5, cint6, cint7
	double complex cint8, cint9, cint10, cint11, cint12, cint13
	double complex cint14, cint15, cint16, cint17, cint18, cint19
	double complex cint20
	common /LLgg_loopint/ cint1, cint2, cint3, cint4, cint5, cint6
	common /LLgg_loopint/ cint7, cint8, cint9, cint10, cint11
	common /LLgg_loopint/ cint12, cint13, cint14, cint15, cint16
	common /LLgg_loopint/ cint17, cint18, cint19, cint20

	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30, iint31, iint32, iint33, iint34, iint35, iint36
	integer iint37, iint38, iint39, iint40, iint41, iint42, iint43
	integer iint44, iint45, iint46, iint47, iint48, iint49, iint50
	integer iint51, iint52, iint53, iint54, iint55, iint56, iint57
	integer iint58, iint59, iint60, iint61, iint62, iint63, iint64
	integer iint65, iint66, iint67, iint68, iint69, iint70, iint71
	integer iint72, iint73, iint74, iint75, iint76, iint77, iint78
	integer iint79, iint80, iint81, iint82, iint83, iint84, iint85
	integer iint86, iint87, iint88, iint89, iint90
	common /LLgg_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /LLgg_loopint/ iint7, iint8, iint9, iint10, iint11
	common /LLgg_loopint/ iint12, iint13, iint14, iint15, iint16
	common /LLgg_loopint/ iint17, iint18, iint19, iint20, iint21
	common /LLgg_loopint/ iint22, iint23, iint24, iint25, iint26
	common /LLgg_loopint/ iint27, iint28, iint29, iint30, iint31
	common /LLgg_loopint/ iint32, iint33, iint34, iint35, iint36
	common /LLgg_loopint/ iint37, iint38, iint39, iint40, iint41
	common /LLgg_loopint/ iint42, iint43, iint44, iint45, iint46
	common /LLgg_loopint/ iint47, iint48, iint49, iint50, iint51
	common /LLgg_loopint/ iint52, iint53, iint54, iint55, iint56
	common /LLgg_loopint/ iint57, iint58, iint59, iint60, iint61
	common /LLgg_loopint/ iint62, iint63, iint64, iint65, iint66
	common /LLgg_loopint/ iint67, iint68, iint69, iint70, iint71
	common /LLgg_loopint/ iint72, iint73, iint74, iint75, iint76
	common /LLgg_loopint/ iint77, iint78, iint79, iint80, iint81
	common /LLgg_loopint/ iint82, iint83, iint84, iint85, iint86
	common /LLgg_loopint/ iint87, iint88, iint89, iint90

	double complex MatSUN(3,2), Ctree(2), Cloop(3)
	common /LLgg_formfactors/ MatSUN, Ctree, Cloop

