* LLsf_vars.h
* variable declarations
* generated by FormCalc 6.1 24 Sep 2013 14:22

#include "decl.h"
#include "sqantisq_renconst.h" 
	double precision S, T, U
	common /LLsf_kinvars/ S, T, U

	integer Hel(4)
	common /LLsf_kinvars/ Hel

	double complex F9, F8, F3, F4, AbbSum5
	common /LLsf_abbrev/ F9, F8, F3, F4, AbbSum5

	double complex cint1, cint2, cint3, cint4, cint5, cint6, cint7
	double complex cint8, cint9, cint10, cint11, cint12, cint13
	double complex cint14, cint15, cint16, cint17, cint18, cint19
	common /LLsf_loopint/ cint1, cint2, cint3, cint4, cint5, cint6
	common /LLsf_loopint/ cint7, cint8, cint9, cint10, cint11
	common /LLsf_loopint/ cint12, cint13, cint14, cint15, cint16
	common /LLsf_loopint/ cint17, cint18, cint19

	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30, iint31, iint32, iint33, iint34, iint35, iint36
	integer iint37, iint38, iint39, iint40, iint41, iint42, iint43
	integer iint44, iint45, iint46, iint47, iint48, iint49, iint50
	integer iint51, iint52, iint53, iint54, iint55, iint56, iint57
	integer iint58
	common /LLsf_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /LLsf_loopint/ iint7, iint8, iint9, iint10, iint11
	common /LLsf_loopint/ iint12, iint13, iint14, iint15, iint16
	common /LLsf_loopint/ iint17, iint18, iint19, iint20, iint21
	common /LLsf_loopint/ iint22, iint23, iint24, iint25, iint26
	common /LLsf_loopint/ iint27, iint28, iint29, iint30, iint31
	common /LLsf_loopint/ iint32, iint33, iint34, iint35, iint36
	common /LLsf_loopint/ iint37, iint38, iint39, iint40, iint41
	common /LLsf_loopint/ iint42, iint43, iint44, iint45, iint46
	common /LLsf_loopint/ iint47, iint48, iint49, iint50, iint51
	common /LLsf_loopint/ iint52, iint53, iint54, iint55, iint56
	common /LLsf_loopint/ iint57, iint58

	double complex MatSUN(2,2), Ctree(2), Cloop(2)
	common /LLsf_formfactors/ MatSUN, Ctree, Cloop

