* LR_vars.h
* variable declarations
* generated by FormCalc 6 Nov 2013 10:58

#include "decl.h"
#include "sqantisq_renconst.h" 
	double precision S, T, U
	common /LR_kinvars/ S, T, U

	integer Hel(4)
	common /LR_kinvars/ Hel

	double complex F19, F22, F23, AbbSum24
	common /LR_abbrev/ F19, F22, F23, AbbSum24

	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30
	common /LR_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /LR_loopint/ iint7, iint8, iint9, iint10, iint11
	common /LR_loopint/ iint12, iint13, iint14, iint15, iint16
	common /LR_loopint/ iint17, iint18, iint19, iint20, iint21
	common /LR_loopint/ iint22, iint23, iint24, iint25, iint26
	common /LR_loopint/ iint27, iint28, iint29, iint30

	double complex MatSUN(2,2), Ctree(2), Cloop(2)
	common /LR_formfactors/ MatSUN, Ctree, Cloop

