* uLdR_vars.h
* variable declarations
* generated by FormCalc 6.1 24 Sep 2013 14:44

#include "decl.h"
#include "sqantisq_renconst.h" 
	double precision S, T, U
	common /uLdR_kinvars/ S, T, U

	integer Hel(4)
	common /uLdR_kinvars/ Hel

	double complex F1524, F1529, F1530
	common /uLdR_abbrev/ F1524, F1529, F1530

	integer iint1, iint2, iint3, iint4, iint5, iint6, iint7, iint8
	integer iint9, iint10, iint11, iint12, iint13, iint14, iint15
	integer iint16, iint17, iint18, iint19, iint20, iint21, iint22
	integer iint23, iint24, iint25, iint26, iint27, iint28, iint29
	integer iint30
	common /uLdR_loopint/ iint1, iint2, iint3, iint4, iint5, iint6
	common /uLdR_loopint/ iint7, iint8, iint9, iint10, iint11
	common /uLdR_loopint/ iint12, iint13, iint14, iint15, iint16
	common /uLdR_loopint/ iint17, iint18, iint19, iint20, iint21
	common /uLdR_loopint/ iint22, iint23, iint24, iint25, iint26
	common /uLdR_loopint/ iint27, iint28, iint29, iint30

	double complex MatSUN(2,2), Ctree(2), Cloop(2)
	common /uLdR_formfactors/ MatSUN, Ctree, Cloop

