#if 0
* specs.h
* process specifications
* generated by FormCalc 8.4 on 9-Sep-2016 0:43
#endif

#define TYPE1 PHOTON
#define ANTI1 1
#define MASS1 0
#define Charge1 0

#define TYPE2 PHOTON
#define ANTI2 1
#define MASS2 0
#define Charge2 0

#define TYPE3 SCALAR
#define ANTI3 1
#define MASS3 MH
#define Charge3 0

#define TYPE4 VECTOR
#define ANTI4 -1
#define MASS4 MW
#define Charge4 1

#define TYPE5 VECTOR
#define ANTI5 1
#define MASS5 MW
#define Charge5 -1

#define LEGS_IN 2
#define LEGS_OUT 3
#define LEGS 5

#define KIN "2to3.F"
