#if 0
* bbbar_vars.h
* variable declarations
* generated by FormCalc 7.5 on 17-Oct-2016 13:26
#endif

#ifndef VARS_H
#define VARS_H

#define LEGS 5

#include "decl.h"

#else

#include "decl.h"

	ComplexType Sub100, Sub13, Sub23, Sub73, Sub88
	common /bbbar_abbrev1s/ Sub100, Sub13, Sub23, Sub73, Sub88

	ComplexType Sub2, Sub22, Sub4, Sub7
	common /bbbar_abbrev0angle/ Sub2, Sub22, Sub4, Sub7

	ComplexType Sub106, Sub107, Sub114, Sub12, Sub127, Sub131
	ComplexType Sub151, Sub18, Sub193, Sub196, Sub212, Sub28
	ComplexType Sub31, Sub34, Sub43, Sub48, Sub49, Sub52, Sub62
	ComplexType Sub64, Sub68, Sub69, Sub77, Sub78, Sub8, Sub89
	ComplexType Sub90, Sub95, Sub96
	common /bbbar_abbrev1angle/ Sub106, Sub107, Sub114, Sub12, Sub127
	common /bbbar_abbrev1angle/ Sub131, Sub151, Sub18, Sub193, Sub196
	common /bbbar_abbrev1angle/ Sub212, Sub28, Sub31, Sub34, Sub43
	common /bbbar_abbrev1angle/ Sub48, Sub49, Sub52, Sub62, Sub64
	common /bbbar_abbrev1angle/ Sub68, Sub69, Sub77, Sub78, Sub8
	common /bbbar_abbrev1angle/ Sub89, Sub90, Sub95, Sub96

	ComplexType Abb1, Abb10, Abb11, Abb12, Abb13, Abb14, Abb15
	ComplexType Abb16, Abb2, Abb3, Abb4, Abb5, Abb6, Abb7, Abb8
	ComplexType Abb9, AbbSum1, AbbSum116, AbbSum166, AbbSum2
	ComplexType AbbSum3, AbbSum347, AbbSum374, AbbSum4, AbbSum5
	ComplexType AbbSum6, AbbSum7, AbbSum8, AbbSum87, AbbSum92
	ComplexType F1, F10, F11, F12, F2, F3, F4, F5, F6, F7, F8
	ComplexType F9, Pair1, Pair2, Pair3, Pair4, Pair5, Pair6
	ComplexType Pair7, Sub1, Sub3, Sub5, Sub6
	common /bbbar_abbrev0hel/ Abb1, Abb10, Abb11, Abb12, Abb13, Abb14
	common /bbbar_abbrev0hel/ Abb15, Abb16, Abb2, Abb3, Abb4, Abb5
	common /bbbar_abbrev0hel/ Abb6, Abb7, Abb8, Abb9, AbbSum1
	common /bbbar_abbrev0hel/ AbbSum116, AbbSum166, AbbSum2, AbbSum3
	common /bbbar_abbrev0hel/ AbbSum347, AbbSum374, AbbSum4, AbbSum5
	common /bbbar_abbrev0hel/ AbbSum6, AbbSum7, AbbSum8, AbbSum87
	common /bbbar_abbrev0hel/ AbbSum92, F1, F10, F11, F12, F2, F3, F4
	common /bbbar_abbrev0hel/ F5, F6, F7, F8, F9, Pair1, Pair2, Pair3
	common /bbbar_abbrev0hel/ Pair4, Pair5, Pair6, Pair7, Sub1, Sub3
	common /bbbar_abbrev0hel/ Sub5, Sub6

	ComplexType Abb17, Abb18, Abb19, Abb20, Abb21, Abb22, Abb23
	ComplexType Abb24, Abb25, Abb26, Abb27, Abb28, Abb29, Abb30
	ComplexType Abb31, Abb32, Abb33, Abb34, Abb35, Abb36, Abb37
	ComplexType Abb38, Abb39, Abb40, Abb41, Abb42, Abb43, Abb44
	ComplexType Abb45, Abb46, Abb47, Abb48, Abb49, Abb50, Abb51
	ComplexType Abb52, Abb53, Abb54, Abb55, Abb56, Abb57, Abb58
	ComplexType Abb59, Abb60, Abb61, Abb62, Abb63, Abb64, Abb65
	ComplexType Abb66, Abb67, Abb68, Abb69, Abb70, Abb71, Abb72
	ComplexType Abb73, Abb74, AbbSum10, AbbSum100, AbbSum101
	ComplexType AbbSum102, AbbSum103, AbbSum104, AbbSum105
	ComplexType AbbSum106, AbbSum107, AbbSum108, AbbSum109
	ComplexType AbbSum11, AbbSum110, AbbSum111, AbbSum112
	ComplexType AbbSum113, AbbSum114, AbbSum115, AbbSum117
	ComplexType AbbSum118, AbbSum119, AbbSum12, AbbSum120
	ComplexType AbbSum121, AbbSum122, AbbSum123, AbbSum124
	ComplexType AbbSum125, AbbSum126, AbbSum127, AbbSum128
	ComplexType AbbSum129, AbbSum13, AbbSum130, AbbSum131
	ComplexType AbbSum132, AbbSum133, AbbSum134, AbbSum135
	ComplexType AbbSum136, AbbSum137, AbbSum138, AbbSum139
	ComplexType AbbSum14, AbbSum140, AbbSum141, AbbSum142
	ComplexType AbbSum143, AbbSum144, AbbSum145, AbbSum146
	ComplexType AbbSum147, AbbSum148, AbbSum149, AbbSum15
	ComplexType AbbSum150, AbbSum151, AbbSum152, AbbSum153
	ComplexType AbbSum154, AbbSum155, AbbSum156, AbbSum157
	ComplexType AbbSum158, AbbSum159, AbbSum16, AbbSum160
	ComplexType AbbSum161, AbbSum162, AbbSum163, AbbSum164
	ComplexType AbbSum165, AbbSum167, AbbSum168, AbbSum169
	ComplexType AbbSum17, AbbSum170, AbbSum171, AbbSum172
	ComplexType AbbSum173, AbbSum174, AbbSum175, AbbSum176
	ComplexType AbbSum177, AbbSum178, AbbSum179, AbbSum18
	ComplexType AbbSum180, AbbSum181, AbbSum182, AbbSum183
	ComplexType AbbSum184, AbbSum185, AbbSum186, AbbSum187
	ComplexType AbbSum188, AbbSum189, AbbSum19, AbbSum190
	ComplexType AbbSum191, AbbSum192, AbbSum193, AbbSum194
	ComplexType AbbSum195, AbbSum196, AbbSum197, AbbSum198
	ComplexType AbbSum199, AbbSum20, AbbSum200, AbbSum201
	ComplexType AbbSum202, AbbSum203, AbbSum204, AbbSum205
	ComplexType AbbSum206, AbbSum207, AbbSum208, AbbSum209
	ComplexType AbbSum21, AbbSum210, AbbSum211, AbbSum212
	ComplexType AbbSum213, AbbSum214, AbbSum215, AbbSum216
	ComplexType AbbSum217, AbbSum218, AbbSum219, AbbSum22
	ComplexType AbbSum220, AbbSum221, AbbSum222, AbbSum223
	ComplexType AbbSum224, AbbSum225, AbbSum226, AbbSum227
	ComplexType AbbSum228, AbbSum229, AbbSum23, AbbSum230
	ComplexType AbbSum231, AbbSum232, AbbSum233, AbbSum234
	ComplexType AbbSum235, AbbSum236, AbbSum237, AbbSum238
	ComplexType AbbSum239, AbbSum24, AbbSum240, AbbSum241
	ComplexType AbbSum242, AbbSum243, AbbSum244, AbbSum245
	ComplexType AbbSum246, AbbSum247, AbbSum248, AbbSum249
	ComplexType AbbSum25, AbbSum250, AbbSum251, AbbSum252
	ComplexType AbbSum253, AbbSum254, AbbSum255, AbbSum256
	ComplexType AbbSum257, AbbSum258, AbbSum259, AbbSum26
	ComplexType AbbSum260, AbbSum261, AbbSum262, AbbSum263
	ComplexType AbbSum264, AbbSum265, AbbSum266, AbbSum267
	ComplexType AbbSum268, AbbSum269, AbbSum27, AbbSum270
	ComplexType AbbSum271, AbbSum272, AbbSum273, AbbSum274
	ComplexType AbbSum275, AbbSum276, AbbSum277, AbbSum278
	ComplexType AbbSum279, AbbSum28, AbbSum280, AbbSum281
	ComplexType AbbSum282, AbbSum283, AbbSum284, AbbSum285
	ComplexType AbbSum286, AbbSum287, AbbSum288, AbbSum289
	ComplexType AbbSum29, AbbSum290, AbbSum291, AbbSum292
	ComplexType AbbSum293, AbbSum294, AbbSum295, AbbSum296
	ComplexType AbbSum297, AbbSum298, AbbSum299, AbbSum30
	ComplexType AbbSum300, AbbSum301, AbbSum302, AbbSum303
	ComplexType AbbSum304, AbbSum305, AbbSum306, AbbSum307
	ComplexType AbbSum308, AbbSum309, AbbSum31, AbbSum310
	ComplexType AbbSum311, AbbSum312, AbbSum313, AbbSum314
	ComplexType AbbSum315, AbbSum316, AbbSum317, AbbSum318
	ComplexType AbbSum319, AbbSum32, AbbSum320, AbbSum321
	ComplexType AbbSum322, AbbSum323, AbbSum324, AbbSum325
	ComplexType AbbSum326, AbbSum327, AbbSum328, AbbSum329
	ComplexType AbbSum33, AbbSum330, AbbSum331, AbbSum332
	ComplexType AbbSum333, AbbSum334, AbbSum335, AbbSum336
	ComplexType AbbSum337, AbbSum338, AbbSum339, AbbSum34
	ComplexType AbbSum340, AbbSum341, AbbSum342, AbbSum343
	ComplexType AbbSum344, AbbSum345, AbbSum346, AbbSum348
	ComplexType AbbSum349, AbbSum35, AbbSum350, AbbSum351
	ComplexType AbbSum352, AbbSum353, AbbSum354, AbbSum355
	ComplexType AbbSum356, AbbSum357, AbbSum358, AbbSum359
	ComplexType AbbSum36, AbbSum360, AbbSum361, AbbSum362
	ComplexType AbbSum363, AbbSum364, AbbSum365, AbbSum366
	ComplexType AbbSum367, AbbSum368, AbbSum369, AbbSum37
	ComplexType AbbSum370, AbbSum371, AbbSum372, AbbSum373
	ComplexType AbbSum375, AbbSum376, AbbSum377, AbbSum378
	ComplexType AbbSum379, AbbSum38, AbbSum380, AbbSum381
	ComplexType AbbSum382, AbbSum39, AbbSum40, AbbSum41
	ComplexType AbbSum42, AbbSum43, AbbSum44, AbbSum45, AbbSum46
	ComplexType AbbSum47, AbbSum48, AbbSum49, AbbSum50, AbbSum51
	ComplexType AbbSum52, AbbSum53, AbbSum54, AbbSum55, AbbSum56
	ComplexType AbbSum57, AbbSum58, AbbSum59, AbbSum60, AbbSum61
	ComplexType AbbSum62, AbbSum63, AbbSum64, AbbSum65, AbbSum66
	ComplexType AbbSum67, AbbSum68, AbbSum69, AbbSum70, AbbSum71
	ComplexType AbbSum72, AbbSum73, AbbSum74, AbbSum75, AbbSum76
	ComplexType AbbSum77, AbbSum78, AbbSum79, AbbSum80, AbbSum81
	ComplexType AbbSum82, AbbSum83, AbbSum84, AbbSum85, AbbSum86
	ComplexType AbbSum88, AbbSum89, AbbSum9, AbbSum90, AbbSum91
	ComplexType AbbSum93, AbbSum94, AbbSum95, AbbSum96, AbbSum97
	ComplexType AbbSum98, AbbSum99, F13, F14, F15, F16, Opt1
	ComplexType Opt2, Opt3, Opt4, Opt5, Pair8, Pair9, Sub10
	ComplexType Sub101, Sub102, Sub103, Sub104, Sub105, Sub108
	ComplexType Sub109, Sub11, Sub110, Sub111, Sub112, Sub113
	ComplexType Sub115, Sub116, Sub117, Sub118, Sub119, Sub120
	ComplexType Sub121, Sub122, Sub123, Sub124, Sub125, Sub126
	ComplexType Sub128, Sub129, Sub130, Sub132, Sub133, Sub134
	ComplexType Sub135, Sub136, Sub137, Sub138, Sub139, Sub14
	ComplexType Sub140, Sub141, Sub142, Sub143, Sub144, Sub145
	ComplexType Sub146, Sub147, Sub148, Sub149, Sub15, Sub150
	ComplexType Sub152, Sub153, Sub154, Sub155, Sub156, Sub157
	ComplexType Sub158, Sub159, Sub16, Sub160, Sub161, Sub162
	ComplexType Sub163, Sub164, Sub165, Sub166, Sub167, Sub168
	ComplexType Sub169, Sub17, Sub170, Sub171, Sub172, Sub173
	ComplexType Sub174, Sub175, Sub176, Sub177, Sub178, Sub179
	ComplexType Sub180, Sub181, Sub182, Sub183, Sub184, Sub185
	ComplexType Sub186, Sub187, Sub188, Sub189, Sub19, Sub190
	ComplexType Sub191, Sub192, Sub194, Sub195, Sub197, Sub198
	ComplexType Sub199, Sub20, Sub200, Sub201, Sub202, Sub203
	ComplexType Sub204, Sub205, Sub206, Sub207, Sub208, Sub209
	ComplexType Sub21, Sub210, Sub211, Sub213, Sub214, Sub215
	ComplexType Sub216, Sub217, Sub218, Sub219, Sub220, Sub221
	ComplexType Sub222, Sub223, Sub224, Sub225, Sub226, Sub227
	ComplexType Sub228, Sub229, Sub230, Sub231, Sub232, Sub233
	ComplexType Sub234, Sub235, Sub236, Sub237, Sub238, Sub24
	ComplexType Sub25, Sub26, Sub27, Sub29, Sub30, Sub32, Sub33
	ComplexType Sub35, Sub36, Sub37, Sub38, Sub39, Sub40, Sub41
	ComplexType Sub42, Sub44, Sub45, Sub46, Sub47, Sub50, Sub51
	ComplexType Sub53, Sub54, Sub55, Sub56, Sub57, Sub58, Sub59
	ComplexType Sub60, Sub61, Sub63, Sub65, Sub66, Sub67, Sub70
	ComplexType Sub71, Sub72, Sub74, Sub75, Sub76, Sub79, Sub80
	ComplexType Sub81, Sub82, Sub83, Sub84, Sub85, Sub86, Sub87
	ComplexType Sub9, Sub91, Sub92, Sub93, Sub94, Sub97, Sub98
	ComplexType Sub99
	common /bbbar_abbrev1hel/ Abb17, Abb18, Abb19, Abb20, Abb21, Abb22
	common /bbbar_abbrev1hel/ Abb23, Abb24, Abb25, Abb26, Abb27, Abb28
	common /bbbar_abbrev1hel/ Abb29, Abb30, Abb31, Abb32, Abb33, Abb34
	common /bbbar_abbrev1hel/ Abb35, Abb36, Abb37, Abb38, Abb39, Abb40
	common /bbbar_abbrev1hel/ Abb41, Abb42, Abb43, Abb44, Abb45, Abb46
	common /bbbar_abbrev1hel/ Abb47, Abb48, Abb49, Abb50, Abb51, Abb52
	common /bbbar_abbrev1hel/ Abb53, Abb54, Abb55, Abb56, Abb57, Abb58
	common /bbbar_abbrev1hel/ Abb59, Abb60, Abb61, Abb62, Abb63, Abb64
	common /bbbar_abbrev1hel/ Abb65, Abb66, Abb67, Abb68, Abb69, Abb70
	common /bbbar_abbrev1hel/ Abb71, Abb72, Abb73, Abb74, AbbSum10
	common /bbbar_abbrev1hel/ AbbSum100, AbbSum101, AbbSum102
	common /bbbar_abbrev1hel/ AbbSum103, AbbSum104, AbbSum105
	common /bbbar_abbrev1hel/ AbbSum106, AbbSum107, AbbSum108
	common /bbbar_abbrev1hel/ AbbSum109, AbbSum11, AbbSum110
	common /bbbar_abbrev1hel/ AbbSum111, AbbSum112, AbbSum113
	common /bbbar_abbrev1hel/ AbbSum114, AbbSum115, AbbSum117
	common /bbbar_abbrev1hel/ AbbSum118, AbbSum119, AbbSum12
	common /bbbar_abbrev1hel/ AbbSum120, AbbSum121, AbbSum122
	common /bbbar_abbrev1hel/ AbbSum123, AbbSum124, AbbSum125
	common /bbbar_abbrev1hel/ AbbSum126, AbbSum127, AbbSum128
	common /bbbar_abbrev1hel/ AbbSum129, AbbSum13, AbbSum130
	common /bbbar_abbrev1hel/ AbbSum131, AbbSum132, AbbSum133
	common /bbbar_abbrev1hel/ AbbSum134, AbbSum135, AbbSum136
	common /bbbar_abbrev1hel/ AbbSum137, AbbSum138, AbbSum139
	common /bbbar_abbrev1hel/ AbbSum14, AbbSum140, AbbSum141
	common /bbbar_abbrev1hel/ AbbSum142, AbbSum143, AbbSum144
	common /bbbar_abbrev1hel/ AbbSum145, AbbSum146, AbbSum147
	common /bbbar_abbrev1hel/ AbbSum148, AbbSum149, AbbSum15
	common /bbbar_abbrev1hel/ AbbSum150, AbbSum151, AbbSum152
	common /bbbar_abbrev1hel/ AbbSum153, AbbSum154, AbbSum155
	common /bbbar_abbrev1hel/ AbbSum156, AbbSum157, AbbSum158
	common /bbbar_abbrev1hel/ AbbSum159, AbbSum16, AbbSum160
	common /bbbar_abbrev1hel/ AbbSum161, AbbSum162, AbbSum163
	common /bbbar_abbrev1hel/ AbbSum164, AbbSum165, AbbSum167
	common /bbbar_abbrev1hel/ AbbSum168, AbbSum169, AbbSum17
	common /bbbar_abbrev1hel/ AbbSum170, AbbSum171, AbbSum172
	common /bbbar_abbrev1hel/ AbbSum173, AbbSum174, AbbSum175
	common /bbbar_abbrev1hel/ AbbSum176, AbbSum177, AbbSum178
	common /bbbar_abbrev1hel/ AbbSum179, AbbSum18, AbbSum180
	common /bbbar_abbrev1hel/ AbbSum181, AbbSum182, AbbSum183
	common /bbbar_abbrev1hel/ AbbSum184, AbbSum185, AbbSum186
	common /bbbar_abbrev1hel/ AbbSum187, AbbSum188, AbbSum189
	common /bbbar_abbrev1hel/ AbbSum19, AbbSum190, AbbSum191
	common /bbbar_abbrev1hel/ AbbSum192, AbbSum193, AbbSum194
	common /bbbar_abbrev1hel/ AbbSum195, AbbSum196, AbbSum197
	common /bbbar_abbrev1hel/ AbbSum198, AbbSum199, AbbSum20
	common /bbbar_abbrev1hel/ AbbSum200, AbbSum201, AbbSum202
	common /bbbar_abbrev1hel/ AbbSum203, AbbSum204, AbbSum205
	common /bbbar_abbrev1hel/ AbbSum206, AbbSum207, AbbSum208
	common /bbbar_abbrev1hel/ AbbSum209, AbbSum21, AbbSum210
	common /bbbar_abbrev1hel/ AbbSum211, AbbSum212, AbbSum213
	common /bbbar_abbrev1hel/ AbbSum214, AbbSum215, AbbSum216
	common /bbbar_abbrev1hel/ AbbSum217, AbbSum218, AbbSum219
	common /bbbar_abbrev1hel/ AbbSum22, AbbSum220, AbbSum221
	common /bbbar_abbrev1hel/ AbbSum222, AbbSum223, AbbSum224
	common /bbbar_abbrev1hel/ AbbSum225, AbbSum226, AbbSum227
	common /bbbar_abbrev1hel/ AbbSum228, AbbSum229, AbbSum23
	common /bbbar_abbrev1hel/ AbbSum230, AbbSum231, AbbSum232
	common /bbbar_abbrev1hel/ AbbSum233, AbbSum234, AbbSum235
	common /bbbar_abbrev1hel/ AbbSum236, AbbSum237, AbbSum238
	common /bbbar_abbrev1hel/ AbbSum239, AbbSum24, AbbSum240
	common /bbbar_abbrev1hel/ AbbSum241, AbbSum242, AbbSum243
	common /bbbar_abbrev1hel/ AbbSum244, AbbSum245, AbbSum246
	common /bbbar_abbrev1hel/ AbbSum247, AbbSum248, AbbSum249
	common /bbbar_abbrev1hel/ AbbSum25, AbbSum250, AbbSum251
	common /bbbar_abbrev1hel/ AbbSum252, AbbSum253, AbbSum254
	common /bbbar_abbrev1hel/ AbbSum255, AbbSum256, AbbSum257
	common /bbbar_abbrev1hel/ AbbSum258, AbbSum259, AbbSum26
	common /bbbar_abbrev1hel/ AbbSum260, AbbSum261, AbbSum262
	common /bbbar_abbrev1hel/ AbbSum263, AbbSum264, AbbSum265
	common /bbbar_abbrev1hel/ AbbSum266, AbbSum267, AbbSum268
	common /bbbar_abbrev1hel/ AbbSum269, AbbSum27, AbbSum270
	common /bbbar_abbrev1hel/ AbbSum271, AbbSum272, AbbSum273
	common /bbbar_abbrev1hel/ AbbSum274, AbbSum275, AbbSum276
	common /bbbar_abbrev1hel/ AbbSum277, AbbSum278, AbbSum279
	common /bbbar_abbrev1hel/ AbbSum28, AbbSum280, AbbSum281
	common /bbbar_abbrev1hel/ AbbSum282, AbbSum283, AbbSum284
	common /bbbar_abbrev1hel/ AbbSum285, AbbSum286, AbbSum287
	common /bbbar_abbrev1hel/ AbbSum288, AbbSum289, AbbSum29
	common /bbbar_abbrev1hel/ AbbSum290, AbbSum291, AbbSum292
	common /bbbar_abbrev1hel/ AbbSum293, AbbSum294, AbbSum295
	common /bbbar_abbrev1hel/ AbbSum296, AbbSum297, AbbSum298
	common /bbbar_abbrev1hel/ AbbSum299, AbbSum30, AbbSum300
	common /bbbar_abbrev1hel/ AbbSum301, AbbSum302, AbbSum303
	common /bbbar_abbrev1hel/ AbbSum304, AbbSum305, AbbSum306
	common /bbbar_abbrev1hel/ AbbSum307, AbbSum308, AbbSum309
	common /bbbar_abbrev1hel/ AbbSum31, AbbSum310, AbbSum311
	common /bbbar_abbrev1hel/ AbbSum312, AbbSum313, AbbSum314
	common /bbbar_abbrev1hel/ AbbSum315, AbbSum316, AbbSum317
	common /bbbar_abbrev1hel/ AbbSum318, AbbSum319, AbbSum32
	common /bbbar_abbrev1hel/ AbbSum320, AbbSum321, AbbSum322
	common /bbbar_abbrev1hel/ AbbSum323, AbbSum324, AbbSum325
	common /bbbar_abbrev1hel/ AbbSum326, AbbSum327, AbbSum328
	common /bbbar_abbrev1hel/ AbbSum329, AbbSum33, AbbSum330
	common /bbbar_abbrev1hel/ AbbSum331, AbbSum332, AbbSum333
	common /bbbar_abbrev1hel/ AbbSum334, AbbSum335, AbbSum336
	common /bbbar_abbrev1hel/ AbbSum337, AbbSum338, AbbSum339
	common /bbbar_abbrev1hel/ AbbSum34, AbbSum340, AbbSum341
	common /bbbar_abbrev1hel/ AbbSum342, AbbSum343, AbbSum344
	common /bbbar_abbrev1hel/ AbbSum345, AbbSum346, AbbSum348
	common /bbbar_abbrev1hel/ AbbSum349, AbbSum35, AbbSum350
	common /bbbar_abbrev1hel/ AbbSum351, AbbSum352, AbbSum353
	common /bbbar_abbrev1hel/ AbbSum354, AbbSum355, AbbSum356
	common /bbbar_abbrev1hel/ AbbSum357, AbbSum358, AbbSum359
	common /bbbar_abbrev1hel/ AbbSum36, AbbSum360, AbbSum361
	common /bbbar_abbrev1hel/ AbbSum362, AbbSum363, AbbSum364
	common /bbbar_abbrev1hel/ AbbSum365, AbbSum366, AbbSum367
	common /bbbar_abbrev1hel/ AbbSum368, AbbSum369, AbbSum37
	common /bbbar_abbrev1hel/ AbbSum370, AbbSum371, AbbSum372
	common /bbbar_abbrev1hel/ AbbSum373, AbbSum375, AbbSum376
	common /bbbar_abbrev1hel/ AbbSum377, AbbSum378, AbbSum379
	common /bbbar_abbrev1hel/ AbbSum38, AbbSum380, AbbSum381
	common /bbbar_abbrev1hel/ AbbSum382, AbbSum39, AbbSum40, AbbSum41
	common /bbbar_abbrev1hel/ AbbSum42, AbbSum43, AbbSum44, AbbSum45
	common /bbbar_abbrev1hel/ AbbSum46, AbbSum47, AbbSum48, AbbSum49
	common /bbbar_abbrev1hel/ AbbSum50, AbbSum51, AbbSum52, AbbSum53
	common /bbbar_abbrev1hel/ AbbSum54, AbbSum55, AbbSum56, AbbSum57
	common /bbbar_abbrev1hel/ AbbSum58, AbbSum59, AbbSum60, AbbSum61
	common /bbbar_abbrev1hel/ AbbSum62, AbbSum63, AbbSum64, AbbSum65
	common /bbbar_abbrev1hel/ AbbSum66, AbbSum67, AbbSum68, AbbSum69
	common /bbbar_abbrev1hel/ AbbSum70, AbbSum71, AbbSum72, AbbSum73
	common /bbbar_abbrev1hel/ AbbSum74, AbbSum75, AbbSum76, AbbSum77
	common /bbbar_abbrev1hel/ AbbSum78, AbbSum79, AbbSum80, AbbSum81
	common /bbbar_abbrev1hel/ AbbSum82, AbbSum83, AbbSum84, AbbSum85
	common /bbbar_abbrev1hel/ AbbSum86, AbbSum88, AbbSum89, AbbSum9
	common /bbbar_abbrev1hel/ AbbSum90, AbbSum91, AbbSum93, AbbSum94
	common /bbbar_abbrev1hel/ AbbSum95, AbbSum96, AbbSum97, AbbSum98
	common /bbbar_abbrev1hel/ AbbSum99, F13, F14, F15, F16, Opt1, Opt2
	common /bbbar_abbrev1hel/ Opt3, Opt4, Opt5, Pair8, Pair9, Sub10
	common /bbbar_abbrev1hel/ Sub101, Sub102, Sub103, Sub104, Sub105
	common /bbbar_abbrev1hel/ Sub108, Sub109, Sub11, Sub110, Sub111
	common /bbbar_abbrev1hel/ Sub112, Sub113, Sub115, Sub116, Sub117
	common /bbbar_abbrev1hel/ Sub118, Sub119, Sub120, Sub121, Sub122
	common /bbbar_abbrev1hel/ Sub123, Sub124, Sub125, Sub126, Sub128
	common /bbbar_abbrev1hel/ Sub129, Sub130, Sub132, Sub133, Sub134
	common /bbbar_abbrev1hel/ Sub135, Sub136, Sub137, Sub138, Sub139
	common /bbbar_abbrev1hel/ Sub14, Sub140, Sub141, Sub142, Sub143
	common /bbbar_abbrev1hel/ Sub144, Sub145, Sub146, Sub147, Sub148
	common /bbbar_abbrev1hel/ Sub149, Sub15, Sub150, Sub152, Sub153
	common /bbbar_abbrev1hel/ Sub154, Sub155, Sub156, Sub157, Sub158
	common /bbbar_abbrev1hel/ Sub159, Sub16, Sub160, Sub161, Sub162
	common /bbbar_abbrev1hel/ Sub163, Sub164, Sub165, Sub166, Sub167
	common /bbbar_abbrev1hel/ Sub168, Sub169, Sub17, Sub170, Sub171
	common /bbbar_abbrev1hel/ Sub172, Sub173, Sub174, Sub175, Sub176
	common /bbbar_abbrev1hel/ Sub177, Sub178, Sub179, Sub180, Sub181
	common /bbbar_abbrev1hel/ Sub182, Sub183, Sub184, Sub185, Sub186
	common /bbbar_abbrev1hel/ Sub187, Sub188, Sub189, Sub19, Sub190
	common /bbbar_abbrev1hel/ Sub191, Sub192, Sub194, Sub195, Sub197
	common /bbbar_abbrev1hel/ Sub198, Sub199, Sub20, Sub200, Sub201
	common /bbbar_abbrev1hel/ Sub202, Sub203, Sub204, Sub205, Sub206
	common /bbbar_abbrev1hel/ Sub207, Sub208, Sub209, Sub21, Sub210
	common /bbbar_abbrev1hel/ Sub211, Sub213, Sub214, Sub215, Sub216
	common /bbbar_abbrev1hel/ Sub217, Sub218, Sub219, Sub220, Sub221
	common /bbbar_abbrev1hel/ Sub222, Sub223, Sub224, Sub225, Sub226
	common /bbbar_abbrev1hel/ Sub227, Sub228, Sub229, Sub230, Sub231
	common /bbbar_abbrev1hel/ Sub232, Sub233, Sub234, Sub235, Sub236
	common /bbbar_abbrev1hel/ Sub237, Sub238, Sub24, Sub25, Sub26
	common /bbbar_abbrev1hel/ Sub27, Sub29, Sub30, Sub32, Sub33, Sub35
	common /bbbar_abbrev1hel/ Sub36, Sub37, Sub38, Sub39, Sub40, Sub41
	common /bbbar_abbrev1hel/ Sub42, Sub44, Sub45, Sub46, Sub47, Sub50
	common /bbbar_abbrev1hel/ Sub51, Sub53, Sub54, Sub55, Sub56, Sub57
	common /bbbar_abbrev1hel/ Sub58, Sub59, Sub60, Sub61, Sub63, Sub65
	common /bbbar_abbrev1hel/ Sub66, Sub67, Sub70, Sub71, Sub72, Sub74
	common /bbbar_abbrev1hel/ Sub75, Sub76, Sub79, Sub80, Sub81, Sub82
	common /bbbar_abbrev1hel/ Sub83, Sub84, Sub85, Sub86, Sub87, Sub9
	common /bbbar_abbrev1hel/ Sub91, Sub92, Sub93, Sub94, Sub97, Sub98
	common /bbbar_abbrev1hel/ Sub99

	ComplexType pave11(Ncc), pave2(Nbb), pave21(Ncc), pave22(Ncc)
	ComplexType pave3(Nbb), pave4(Nbb), pave7(Ncc)
	common /bbbar_loopint1s/ pave11, pave2, pave21, pave22, pave3
	common /bbbar_loopint1s/ pave4, pave7

	ComplexType pave1(Nbb), pave10(Ncc), pave12(Ncc), pave13(Ncc)
	ComplexType pave14(Ncc), pave15(Ndd), pave16(Ndd)
	ComplexType pave17(Ndd), pave18(Ndd), pave19(Ncc)
	ComplexType pave20(Ncc), pave5(Nbb), pave6(Nbb), pave8(Ncc)
	ComplexType pave9(Ncc)
	common /bbbar_loopint1angle/ pave1, pave10, pave12, pave13, pave14
	common /bbbar_loopint1angle/ pave15, pave16, pave17, pave18
	common /bbbar_loopint1angle/ pave19, pave20, pave5, pave6, pave8
	common /bbbar_loopint1angle/ pave9

	RealType S, T, T14, U, T24, S34
	common /kinvars/ S, T, T14, U, T24, S34

	integer seq(2), Hel(5)
	common /helvars/ seq, Hel

	ComplexType Ctree(1), Cloop(1), MatSUN(1,1)
	common /bbbar_formfactors/ Ctree, Cloop, MatSUN


#endif
